### ISSUE TITLE
When using your example settings, I cannot unit test code which uses Angular2 ?

### ISSUE THREAD

**Issue by StefH** [monounity/karma-typescript#10]
**karma.conf.js**

``` js
files: [
    { pattern: "src/**/*.ts" }
],

preprocessors: {
    "**/*.ts": [ 'coverage', 'karma-typescript', 'sourcemap' ]
},
```

And the error message:

> Chrome 53.0.2785 (Windows 10 0.0.0) ERROR
>   Uncaught Error: Could not find module '@angular/core' from 'C:/Github/_forks/angular2-odata/src/config.js'
>   at node_modules/karma-commonjs/client/commonjs_bridge.js:85

**Comment by monounity** [comment]
At first glance it looks like you need to add the angular files to the karma file list, but I suspect you will run into this karma-commonjs issue: karma-runner/karma-commonjs#29. I'll take a look, it's probably easy to reproduce this error.

**Comment by StefH** [comment]
Thanks for the investigation. Really helpful.

If I get this working, I do not need to use the web solution.

Other question : Did you also get debugging in vscode?

**Comment by monounity** [comment]
I'm using Atom mostly, do you mean debugging unit tests?

**Comment by StefH** [comment]
Yes indeed. Debugging unit tests.

If Atom is working for you, I guess VS Code will also be ok. 

-----Oorspronkelijk bericht-----
Van: "monounity" <notifications@github.com>
Verzonden: ‎19-‎9-‎2016 04:14
Aan: "monounity/karma-typescript" <karma-typescript@noreply.github.com>
CC: "Stef Heyenrath" <Stef.Heyenrath@gmail.com>; "Author" <author@noreply.github.com>
Onderwerp: Re: [monounity/karma-typescript] When using your example settings, Icannot unit test code which uses Angular2 ? (#10)

I'm using Atom mostly, do you mean debugging unit tests?

**Comment by monounity** [comment]
As I suspected this was easy to reproduce, I'll try to create a working example!

**Comment by monounity** [comment]
This is a commojs bridge issue, it wasn't designed to load from node_modules. I'm trying to create a custom module loader at the moment, it's the same issue as in #11.

**Comment by jtesser** [comment]
is there are workaround here?  I am using latest karma-typescript and having the same issues? 

Can I add something to the files in karma config for node_modules?

getting this which I think is the same error

```
  Uncaught Error: Could not find module '@angular/core' from '/Users/jasontesser/dev/git/dotJS/core/app.config.js'
  at node_modules/karma-commonjs/client/commonjs_bridge.js:85

Chrome 53.0.2785 (Mac OS X 10.12.0) ERROR
  Uncaught Error: Could not find module '@angular/core' from '/Users/jasontesser/dev/git/dotJS/core/app.config.js'
  at node_modules/karma-commonjs/client/commonjs_bridge.js:85
```

**Comment by monounity** [comment]
@jtesser: There is support for angular2 and automatic loading of imported modules from node_modules in the upcoming [2.1](https://github.com/monounity/karma-typescript/tree/2.1) release, if you want to try it out you can pull in the latest from this repo in your package.json:

`"karma-typescript": "git://github.com/monounity/karma-typescript.git#2.1"`

There are examples for running unit tests with angular2 in the integration tests, please look at the karma.conf.angular2.js and the package.json files.

[Integration tests for Typescript@1.8.10](https://github.com/monounity/karma-typescript/tree/2.1/integration-tests%401.8.10)
[Integration tests for Typescript@latest](https://github.com/monounity/karma-typescript/tree/2.1/integration-tests%40latest)

A beta release for 2.1 is expected within the next week or two, you can follow progress and status in the [wiki](https://github.com/monounity/karma-typescript/wiki).

Please report any bugs you find as separate issues, that way I can keep track of everything, and give you credit in the release notes.
