### ISSUE TITLE
Usage with webpack

### ISSUE THREAD

**Issue by QuantumInformation** [monounity/karma-typescript#107]
I first tried to run my test by using my existing webpack config with karma:

https://github.com/QuantumInformation/vanilla-typescript-component-boilerplate/blob/master/karma.conf.js

```js
module.exports = (config) => {
  const tests = 'src/**/*.test.js';

  config.set({
    frameworks: ['mocha'],

    files: [
      {
        pattern: tests,
      },
    ],

    // Preprocess through webpack
    preprocessors: {
      [tests]: ['webpack'],
    },

    singleRun: true,
  });
};
```

however when running karma I get:
![image](https://cloud.githubusercontent.com/assets/216566/24372659/906b0474-1326-11e7-870f-9c5202f87768.png)
any ideas how I can best integrate karma-typescript with this??

**Comment by QuantumInformation** [comment]
I tried this but the console crashes:

![image](https://cloud.githubusercontent.com/assets/216566/24379281/5774497e-133e-11e7-848c-102c8edcede6.png)

**Comment by erikbarke** [comment]
Hey @QuantumInformation, try this:

Install a few missing modules and the latest version of `karma-typescript` from the master branch:

```bash
npm install --save-dev expect.js karma-chrome-launcher @types/expect.js @types/mocha github:monounity/karma-typescript
```

Rename "src/tests/TypeScriptComponent.test.**js**" to "src/tests/TypeScriptComponent.test.**ts**" and change its content to this:

```js
/* global describe, it, beforeEach */

import TypeScriptComponent from '../TypeScriptComponent'

let tempElement = document.createElement('DIV')
tempElement.className = 'container'
document.body.appendChild(tempElement)

let selector = '.container'
let component = new TypeScriptComponent(selector)
component.attach()

describe('Basic tests', () => {
  it('Renders', () => {
    expect(document.querySelectorAll('.typescript-component').length).to.equal(1)
  })
})
```

Change the content of `demo/src/index.ts` to this:

```js
import TypeScriptComponent from '../../src/TypeScriptComponent'

function init () {
  let selector = '.container'
  let component = new TypeScriptComponent(selector)
  component.attach()
}

init()
```

Change the content of `karma.conf.js` to this:

```js
module.exports = (config) => {

  config.set({

    frameworks: ["mocha", "karma-typescript"],

    files: [
      { pattern: "node_modules/expect.js/index.js" },
      { pattern: "src/**/*.ts" }
    ],

    preprocessors: {
      "**/*.ts": ["karma-typescript"]
    },

    reporters: ["progress", "karma-typescript"],

    browsers: ["Chrome"],

    singleRun: true
  });
};
```

Then the command `./node_modules/.bin/karma start` (or similar) should compile the project without errors and run one test successfully!

**Comment by QuantumInformation** [comment]
Thanks so much @erikbarke! Works as expected, super support!

just a minor issue ;)
![image](https://cloud.githubusercontent.com/assets/216566/24380283/86df2b9e-1342-11e7-9084-11ba19930a45.png)


One other question I have is what about all my webpack configuration? Lets say I have a lot more complex stuff required for the build, can karma ignore that?

**Comment by QuantumInformation** [comment]
looks like a recursive issue

**Comment by erikbarke** [comment]
Yeah, it's probably caused by my fix in `demo/src/index.ts`, revert to your version with `import TypeScriptComponent from '../../'` and include only the `src` folder in `karma.conf.js`:

```js
module.exports = (config) => {

  config.set({

    frameworks: ["mocha", "karma-typescript"],

    files: [
      { pattern: "node_modules/expect.js/index.js" },
      { pattern: "src/**/*.ts" }
    ],

    preprocessors: {
      "**/*.ts": ["karma-typescript"]
    },

    karmaTypescriptConfig: {
      include: ["src/**/*.ts"]
    },

    reporters: ["progress", "karma-typescript"],

    browsers: ["Chrome"],

    singleRun: true
  });
};
```

**Comment by QuantumInformation** [comment]
works good thanks!

**Comment by QuantumInformation** [comment]
One last thing, in the test, it passes regardless of the assertion here:

https://github.com/QuantumInformation/vanilla-typescript-component-boilerplate/blob/master/src/tests/TypeScriptComponent.test.ts#L25

**Comment by erikbarke** [comment]
The `setTimeout` makes the test asynchronous, so the whole test finishes before the `assert` is executed, [here's the documentation for testing asynchronous code with Mocha](https://mochajs.org/#asynchronous-code).

**Comment by QuantumInformation** [comment]
great thanks
