### ISSUE TITLE
How to use when there are separate src and test directories

### ISSUE THREAD

**Issue by mattyork** [monounity/karma-typescript#11]
Hey!

I have files in `./src/**/*.(ts|tsx)` and `./test/**/*.(ts|tsx)`. I can't figure out how to configure karma-typescript to work in this case. Halp?

Thanks!

**Comment by StefH** [comment]
I had same issue, and I just moved the test folder to `src\test`.

**Comment by monounity** [comment]
@mattyork, are you compiling your tsx files using `react` or `preserve`?

**Comment by mattyork** [comment]
@monounity using `react`

**Comment by monounity** [comment]
The commonjs bridge apparently wasn't designed to handle loading from node_modules at all, so I'm experimenting with creating a custom module loader and have had some success actually. The code is way to experimental (doesn't even work on windows yet) to share here, I'll get back as soon as possible!

**Comment by mattyork** [comment]
Sounds good. Thanks @monounity

**Comment by monounity** [comment]
@mattyork: There is support for React and automatic loading of imported modules from node_modules in the upcoming [2.1](https://github.com/monounity/karma-typescript/tree/2.1) release, if you want to try it out you can pull in the latest from this repo in your package.json:

`"karma-typescript": "git://github.com/monounity/karma-typescript.git#2.1"`

There are examples for running unit tests with angular2 in the integration tests, please look at the karma.conf.angular2.js and the package.json files.

[Integration tests for Typescript@1.8.10](https://github.com/monounity/karma-typescript/tree/2.1/integration-tests%401.8.10)
[Integration tests for Typescript@latest](https://github.com/monounity/karma-typescript/tree/2.1/integration-tests%40latest)

A beta release for 2.1 is expected within the next week or two, you can follow progress and status in the [wiki](https://github.com/monounity/karma-typescript/wiki).

Please report any bugs you find as separate issues, that way I can keep track of everything, and give you credit in the release notes.
