### ISSUE TITLE
Coverage report for concurrent tasks

### ISSUE THREAD

**Issue by afterbangx** [monounity/karma-typescript#112]
I have a pretty large suite of unit tests that I just recently broke out into separate gulp tasks based on the area of the app they are testing. I'm using gulp to kick off the tests with karma. The problem I'm running into is that if I run each task individually the coverage reports are generated perfectly. However, If I run them concurrently I only get a coverage report for the last task that is run. I thought maybe it was combining them for some reason but I checked and that is not the case. What I mean is this...

If I have two gulp tasks `one` and `two` and then I have `gulp.task("both", ["one", "two"])`. Lets say the reports are setup to go to `coverage/one` and `coverage/two`. When I run `both` I will only get a coverage report for `two`.  Was thinking of using the `run-sequence` package to get around this but the whole reason I set them up to run concurrently is we are trying to reduce build times. Any idea on what I can do to get the other reports to work?

**Comment by erikbarke** [comment]
Hey @afterbangx, are you using the Karma Server api from your gulp tasks, like in the [gulp example](https://github.com/monounity/karma-typescript/tree/master/examples/gulp)?
If so, are you reusing the same server instance between the tasks?

**Comment by afterbangx** [comment]
Yes, My setup is very similar to the example. The only exception is that I am reusing the same karma config for all tasks and I'm defining some of the config properties when launching the server. Like so,

```
exports.usersListUnitTests = (done) => {
	new Server({
		configFile: karmaConfigPath,
		singleRun: true,
		files: commonFiles.concat(ulFiles),
		frameworks: tsFrameworks,
		reporters: tsReporters,
		preprocessors: tsPreprocessors,
		karmaTypescriptConfig: {
			coverageOptions: coverageOptions,
			reports: getKarmaTypeScriptReporterOptions("UsersList"),
			tsConfig: tsConfigPath
		}
	}, function () { done(); }).start();
};

exports.billingUnitTests = (done) => {
	new Server({
		configFile: karmaConfigPath,
		singleRun: true,
		files: commonFiles.concat(billingFiles),
		frameworks: tsFrameworks,
		reporters: tsReporters,
		preprocessors: tsPreprocessors,
		karmaTypescriptConfig: {
			coverageOptions: coverageOptions,
			reports: getKarmaTypeScriptReporterOptions("Billing"),
			tsConfig: tsConfigPath
		}
	}, function () { done(); }).start();
};
```

In the snippet above frameworks, reporters, preprocessors, karmaTypeScriptConfig etc. are what you would expect them to be. And then my tasks are setup like this: 

```
gulp.task("test:UserList", testTasks.usersListUnitTests);
gulp.task("test:Billing", testTasks.billingUnitTests);
gulp.task("test", ["test:UserList", "test:Billing"]);
```

**Comment by erikbarke** [comment]
I suspect this happens because of how Node.js works; every require of a module returns [the same instance](https://nodejs.org/api/modules.html#modules_caching). So when you run the gulp task  `gulp.task("test", ["test:UserList", "test:Billing"]);` both `UserList` and `Billing` are executed in the same process using the same instances of `istanbul`, `remap-istanbul`, internal Karma stuff etc, last wins.

Does it work if you run each gulp task separately in different terminal windows? If so, maybe this could be solved with some creative scripting by spawning unique Node.js processes in a shell or bat script.

**Comment by afterbangx** [comment]
Yeah, it works fine if I run them separately. I'll look into some of your suggestions. Thanks for the tips!
