### ISSUE TITLE
Does this support JSX and *.tsx files?

### ISSUE THREAD

**Issue by RickCarlino** [monounity/karma-typescript#12]
Hi,

I'm running this plugin on a React/JSX project and am getting the usual `"Unexpected token <"` errors because TypeScript does not expect JSX tags.

Is there a way to configure the plugin to run TSX files?

**Comment by RickCarlino** [comment]
Was able to fix the issue by modifying the source in `preprocessor.js` as follows:

```javascript
    var transpileOutput = tsc.transpileModule(
            content, {
                compilerOptions: {
                    target: tsc.ScriptTarget.ES5,
                    module: tsc.ModuleKind.CommonJS,
                    sourceMap: true,
                    jsx: "react" // <=== I added this.
                }
            }
        );
```

This won't be perfect for people who use other JSX libraries (eg: Mithril with MSX), but it will solve the problem for most JSX users.

Please let me know if you would like to merge this or make it an optional setting. I could submit a PR.

**Comment by monounity** [comment]
Hey @RickCarlino, thanks! There's already rudimentary support for react/jsx together with automatic loading of modules from node_modules [in this dev branch](https://github.com/monounity/karma-typescript/tree/moduleloading).

It runs jasmine tests with react on osx and produces remapped coverage, but it's still kind of shaky and haven't been tested on windows so there are probably windows path backslash issues still to be wrinkled out.

Any help testing it would be much appreciated, so feel free to clone it and try running the react example :)

I'll keep this issue open until the jsx/node_module loading features are released.

**Comment by monounity** [comment]
Oh, and any help actually fixing issues in the dev branch is also welcome of course!

**Comment by monounity** [comment]
@RickCarlino: There is support for React and automatic loading of imported modules from node_modules in the upcoming [2.1](https://github.com/monounity/karma-typescript/tree/2.1) release, if you want to try it out you can pull in the latest from this repo in your package.json:

`"karma-typescript": "git://github.com/monounity/karma-typescript.git#2.1"`

There are examples for running unit tests with angular2 in the integration tests, please look at the karma.conf.angular2.js and the package.json files.

[Integration tests for Typescript@1.8.10](https://github.com/monounity/karma-typescript/tree/2.1/integration-tests%401.8.10)
[Integration tests for Typescript@latest](https://github.com/monounity/karma-typescript/tree/2.1/integration-tests%40latest)

A beta release for 2.1 is expected within the next week or two, you can follow progress and status in the [wiki](https://github.com/monounity/karma-typescript/wiki).

Please report any bugs you find as separate issues, that way I can keep track of everything, and give you credit in the release notes.
