### ISSUE TITLE
Occasional 'double compiles' and 'uncaughtException: Cannot read property 'filename' of undefined TypeError: Cannot read property 'filename' of undefined'

### ISSUE THREAD

**Issue by awk** [monounity/karma-typescript#121]
With karma-typescript 3.0.0 and typescript 2.2.1 I'm seeing occasional occurrences of the following output.

```
Running "karma:ci" (karma) task
03 05 2017 08:00:06.553:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.2.1
03 05 2017 08:00:16.181:INFO [compiler.karma-typescript]: Compiled 530 files in 9210 ms.
03 05 2017 08:00:18.888:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.2.1
03 05 2017 08:00:23.646:INFO [compiler.karma-typescript]: Compiled 530 files in 4491 ms.
03 05 2017 08:00:24.394:INFO [bundler.karma-typescript]: Bundled imports for 70 file(s) in 5738 ms.
Wed, 03 May 2017 12:00:24 GMT uncaughtException: Cannot read property 'filename' of undefined
TypeError: Cannot read property 'filename' of undefined
    at Bundler.addLoaderFunction (/Development/belmont/newton/node_modules/karma-typescript/dist/bundler/bundler.js:125:72)
    at /Development/belmont/newton/node_modules/karma-typescript/dist/bundler/bundler.js:115:43
    at Array.forEach (native)
    at /Development/belmont/newton/node_modules/karma-typescript/dist/bundler/bundler.js:114:35
    at /Development/belmont/newton/node_modules/karma-typescript/dist/bundler/bundler.js:177:13
    at /Development/belmont/newton/node_modules/bower-json/node_modules/graceful-fs/graceful-fs.js:104:5
    at /Development/belmont/newton/node_modules/plato/node_modules/graceful-fs/graceful-fs.js:90:5
    at /Development/belmont/newton/node_modules/bower/lib/node_modules/graceful-fs/graceful-fs.js:43:10
    at /Development/belmont/newton/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15)
```

My tsconfig.json is:
```
{
  "compilerOptions": {
    "outDir": "../../../dist",
    "module": "commonjs",
    "target": "es5",
    "noImplicitAny": false,
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "typeRoots": [
      "serialize-ext/",
      "serialize/",
      "woolsthorpeTypes/",
      "../../../node_modules/@types"
    ],
    "baseUrl": ".",
    "lib": [
      "es5",
      "es2015",
      "dom"
    ]
  }
}
```

The karma.conf.js is unfortunately not easy to post here 8-( 

Many times repeating the karma run will work fine the second time, occasionally it requires a third attempt.

It looks like karma-typescript is deciding to compile twice and then stepping on itself in someway (successful karma runs only build once). 

Can anyone suggest some techniques for trying to debug this locally or get closer to the source of the problem?

**Comment by erikbarke** [comment]
Hey @awk, the Karma preprocessor feeds the compiler with files asynchronously and the compiler in `karma-typescript@3.0.0` collects files for 250ms before firing. I suspect this delay isn't enough in your case, so I've increased the delay to 500ms on the dev branch.

Does the problem go away if you install from the dev branch, `npm i github:monounity/karma-typescript#next`?

**Comment by awk** [comment]
I pulled the branch. I had the problem one time (after 3 runs) with the delay at 500ms. I hacked my local install to make it 1000ms and ran a bunch of times (around 10 so far) and haven't had it fail yet.

Is it feasible to make this value part of the karma-typescript config in the karma.conf? The 500 files we currently build is about 1/4 of the total number of files that will probably be in this project eventually.

**Comment by awk** [comment]
That'd be great! If you do that with a default that matches todays value (250) then it won't interfere with anyone else and I can use it to keep my tests running (which keeps my colleagues happy :-)

**Comment by erikbarke** [comment]
The compiler delay is configurable now (default 250ms):

```js
karmaTypescriptConfig: {
    compilerDelay: 1000
},
```

Hope this keeps your coworkers happy 😃

**Comment by awk** [comment]
Awesome! I'll watch for 3.0.2 in the coming weeks.

**Comment by erikbarke** [comment]
3.0.2 is on npm now!

**Comment by Nel75** [comment]
@erikbarke, @awk Thanks for this new option! 

We were having this same issue - consistently getting 2+ simultaneous compiles, occasionally  resulting in an uncaught fatal exception "Cannot read property 'source' of undefined". Found this issue after noticing the new compilerDelay option and looking for more info. Setting the option to 1500 did the trick for us.  

P.S. Would be great if the implementation was enhanced to not have this vulnerability (i.e., for the compiler to automatically wait for all files or to gracefully handle them in batches).
