### ISSUE TITLE
Typechecking error reporting

### ISSUE THREAD

**Issue by ValeryLosik** [monounity/karma-typescript#124]
Hi guys!There is some question that I'd like to ask: is it possible to setup unit-tests environment to get
typechecking errors reporting? I'd like to see unit-tests failed if there was some typescript error.But currently,even if I have expression like that
`const a:boolean = 'string';`
my tests are passing successfully.And all example configuration that I have found works the same,it just swallow types error and runs tests.Maybe,I fully don't understand unit-testing with typescript involved,but I think it is useful to be notified about type errors inside tests.Thanks in advance

**Comment by erikbarke** [comment]
Hey @ValeryLosik, compilation errors should be reported on command line, are you not getting these reports? If you want the test run to stop on compilation errors, try setting `noEmitOnError` to true in either `tsconfig.json` or in `karmaTypescriptConfig.compilerOptions`!
