### ISSUE TITLE
ts.getOptionNameMap no longer marked as `export`

### ISSUE THREAD

**Issue by chrish619** [monounity/karma-typescript#126]
Changes in Typescript 2.3.4 breaks existing Karma-Typescript functionality https://github.com/Microsoft/TypeScript/issues/16168
In [src/shared/project.ts](https://github.com/monounity/karma-typescript/blob/2a7aff62861d0f571030a3c32144610228a1feb9/src/shared/project.ts#L229)

**Comment by erikbarke** [comment]
Hey @chrish619, @Nodonisko, I've committed a fix now, does it work if you install from the development branch, `npm i github:monounity/karma-typescript#next`?

**Comment by cyberhck** [comment]
@erikbarke I can verify that dev branch is working on github. I hope to see a new release soon. When do you think we can release a patch? Considering milestone doesn't have anything left to do.

I'm desperately waiting for this one.

**Comment by erikbarke** [comment]
@cyberhck, awesome 😃 If nothing else comes up I should be able to release within days!

**Comment by cary-smith** [comment]
Good to see this one is already being handled! We just ran into it. 

Thanks for the great work!

**Comment by nfantone** [comment]
Just stumbled upon this error.

```sh
02 06 2017 16:54:33.100:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.3.4
02 06 2017 16:54:33.133:ERROR [karma]: TypeError: ts.getOptionNameMap is not a function
``

Really good to know this is fixed now!

**Comment by erikbarke** [comment]
v3.0.3 is on npm now!
