### ISSUE TITLE
Can not load "karma-typescript"

### ISSUE THREAD

**Issue by mdvorscak** [monounity/karma-typescript#128]
When attempting to run tests I get the warning: 

>    [reporter]: Can not load "karma-typescript"!
>     TypeError: Cannot read property 'karmaTypescriptConfig' of undefined
>     at Configuration.initialize (C:\MyDirectory\node_modules\karma-typescript\dist\shared\configuration.js:12:44)
>     at new Reporter.create (C:\MyDirectory\node_modules\karma-typescript\dist\karma\reporter.js:17:20)
>     at invoke (C:\MyDirectory\node_modules\di\lib\injector.js:75:15)
>     at Array.instantiate (C:\MyDirectory\node_modules\di\lib\injector.js:59:20)
>     at Injector.get (C:\MyDirectory\node_modules\di\lib\injector.js:48:43)
>     at C:\MyDirectory\node_modules\karma\lib\reporter.js:104:75
>     at Array.forEach (native)
>     at createReporters (C:\MyDirectory\node_modules\karma\lib\reporter.js:92:9)
>     at Array.invoke (C:\MyDirectory\node_modules\di\lib\injector.js:75:15)
>     at Injector.get (C:\MyDirectory\node_modules\di\lib\injector.js:48:43)
>     at get (C:\MyDirectory\node_modules\di\lib\injector.js:54:19)
>     at C:\MyDirectory\node_modules\di\lib\injector.js:71:14
>     at Array.map (native)
>     at Injector.invoke (C:\MyDirectory\node_modules\di\lib\injector.js:70:31)
>     at createWebServer (C:\MyDirectory\node_modules\karma\lib\web-server.js:58:19)
>     at Array.invoke (C:\MyDirectory\node_modules\di\lib\injector.js:75:15)

This only began after 3.0.2, appears to be related to 7678cece5d32da5165dbcc771594485bfbea1966. Note: this does not prevent the tests from running, only the coverage is not run.

Here is the relevant part of the config file: 
```
    frameworks: ['jasmine', 'karma-typescript'],
    preprocessors: {
        '**/*.ts': ['karma-typescript']
    },

    reporters: ['nested', 'karma-typescript', 'tfs'],
    karmaTypescriptConfig: {
        coverageOptions: {
            exclude: /(d|spec|test)\.ts$/i
        },
        reports: {
            html: {
                directory:'coverage',
                subdirectory: 'ts'
            }
        }
    }
```

**Comment by erikbarke** [comment]
Hey @mdvorscak, this looks like race conditions, I'll take a look!

**Comment by erikbarke** [comment]
This is weird, the stack trace you posted shows lines from `karma-typecript@3.0.1`:

```bash
TypeError: Cannot read property 'karmaTypescriptConfig' of undefined
at Configuration.initialize (C:\MyDirectory\node_modules\karma-typescript\dist\shared\configuration.js:12:44)
at new Reporter.create (C:\MyDirectory\node_modules\karma-typescript\dist\karma\reporter.js:17:20)
```

Calling `Configuration.initialize` on line 17 in reporter.js was removed in the 7678cec so if you're on `karma-typecript@3.0.2`, has the files in the `dist`folder been mixed up somehow...? Does the problem go away if you make  clean install of your `node_modules` folder?

**Comment by mdvorscak** [comment]
You're correct, after reinstalling @3.0.2 a different trace appears:

   

>  [reporter]: Can not load "karma-typescript"!
>     TypeError: Cannot read property 'reporters' of undefined
>     at Configuration.hasReporter (C:\MyDirectory\node_modules\karma-typescript\dist\shared\configuration.js:42:26)
>     at new Reporter.create (C:\MyDirectory\node_modules\karma-typescript\dist\karma\reporter.js:17:25)
>     at invoke (C:\MyDirectory\node_modules\di\lib\injector.js:75:15)
>     at Array.instantiate (C:\MyDirectory\node_modules\di\lib\injector.js:59:20)
>     at Injector.get (C:\MyDirectory\node_modules\di\lib\injector.js:48:43)
>     at C:\MyDirectory\node_modules\karma\lib\reporter.js:104:75
>     at Array.forEach (native)
> 	at createReporters (C:\MyDirectory\node_modules\karma\lib\reporter.js:92:9)
>     at Array.invoke (C:\MyDirectory\node_modules\di\lib\injector.js:75:15)
>     at Injector.get (C:\MyDirectory\node_modules\di\lib\injector.js:48:43)
>     at get (C:\MyDirectory\node_modules\di\lib\injector.js:54:19)
>     at C:\MyDirectory\node_modules\di\lib\injector.js:71:14
>     at Array.map (native)
>     at Injector.invoke (C:\MyDirectory\node_modules\di\lib\injector.js:70:31)
>     at createWebServer (C:\MyDirectory\node_modules\karma\lib\web-server.js:58:19)
>     at Array.invoke (C:\MyDirectory\node_modules\di\lib\injector.js:75:15)

**Comment by mdvorscak** [comment]
I've created a boiled down version of the environment where this issue is reproduced: https://github.com/mdvorscak/ts-karma-issue

after cloning, run npm i and npm test

**Comment by erikbarke** [comment]
A repro project, thanks 😃
I got the same error running your project and it works with the fix in 67a4e61, does it work for you too if you install the latest from the dev branch, `npm i github:monounity/karma-typescript#next`?

**Comment by mdvorscak** [comment]
The fix works for me, thanks for the quick turnaround!

**Comment by erikbarke** [comment]
Ok, closing!
