### ISSUE TITLE
Double-printing of console log and error messages

### ISSUE THREAD

**Issue by dinvlad** [monounity/karma-typescript#13]
Great package - I have only one concern, in that it appears to double-print every result, be it a simple `console.log('hello')` (with nothing else, just a single file without a spec) or a Typescript error (e.g. by having a single file with a single typo). Is there a reason why it would do so?

Also of note, the second result is not colored.

I'm using just the basic config from the README with nothing else in that file.

Edit: I see the same behavior with the stock example project from this repo.
Edit2: I also verified that only one browser instance is running Karma at the time.

**Comment by dinvlad** [comment]
Hmm, the appears to be some strange mixup between instances and installations of the Karma module. I reinstalled Karma globally and now it works correctly for my project. However, I still see dual printing when I run 'npm test' from a subfolder with this repo. So the issue appear to be intermittent.

**Comment by dinvlad** [comment]
It looks like printing is happening twice when I specify 'karma-typescript' both in the list of frameworks and the list of reporters, as suggested in the default config. So it appears that TSC is getting run twice. Is that the intended behavior? Would it be possible to somehow avoid it?

Thanks

**Comment by monounity** [comment]
Hey @dinvlad, this should be easy to reproduce, I'll investigate!

**Comment by monounity** [comment]
This will fix will be released in the upcoming 3.0 release!
