### ISSUE TITLE
compiler does not catch empty compilerHost

### ISSUE THREAD

**Issue by ChristophAtAdlos** [monounity/karma-typescript#130]
The error when running karma-typescript:  
`Fatal error: Cannot read property 'getNewLine' of undefined`

In compiler.js at outputDiagnostics(), the host is an empty Object.  
At setupRecompile(), the host was created with the following output from `getTsconfig().options`:

```json
{
  "emitDecoratorMetadata": true,
  "experimentalDecorators": true,
  "jsx" :2,
  "module": 1,
  "sourceMap": true,
  "target": 1,
  "noImplicitAny": false,
  "configFilePath": "",
  "lib": ["lib.es2015.d.ts","lib.dom.d.ts"],
  "suppressOutputPathCheck": true
}
```
this results in an empty Object.
A specific error message would be helpfully.

In karma config, settings are `target: "ES5"` and `module: "commonjs"`.   
From where is the configFilePath collected?

**Comment by erikbarke** [comment]
Hey @ChristophAtAdlos, could you attach a file with the complete debug log output here please?

**Comment by ChristophAtAdlos** [comment]
You will find the debug log at [Gist](https://gist.github.com/ChristophAtAdlos/201391c6c04aa1833bbe46c534881a71).

**Comment by ChristophAtAdlos** [comment]
#19 helped to go further ([declare tsconfig.json](https://github.com/monounity/karma-typescript/issues/19#issuecomment-257444995))
Added tsconfig: "./tsconfig-testing.json" in karmaTypescriptConfig, now it compiles. A meaningful error message in case of empty files array would help to resolve faster.   

Now it hangs on `Error: Cannot find module 'inherits' from '.'`.

**Comment by ChristophAtAdlos** [comment]
In the meantime, I got karma-typescript running. I updated npm itself to latest version and rebuilt node_modules from scratch. Tho only thing I had to make is apply the patch from #129 .

**Comment by erikbarke** [comment]
I'm gonna have to chalk this one up as a botched installation issue, I tried using the compiler options you listed and that doesn't result in an empty host. Also, the debug log you provided has a quite specific Typescript error message about not finding any files using the include paths, I'm not sure I can improve anything here.
