### ISSUE TITLE
Missing source map in remap-istanbul

### ISSUE THREAD

**Issue by netzzwerg** [monounity/karma-typescript#132]
You can find my example setup here: https://github.com/netzzwerg/typescript-webpack-karma-mocha
The example is working but for the `src/helper/dom.ts` file I'm getting an error message from `remap-istanbul`:

    Error: Could not find source map for: "/typescript-webpack-karma-mocha/src/helper/dom.ts"

All other files working and also the coverage report looks good.

**Comment by erikbarke** [comment]
Hey @netzzwerg, it seems Typescript doesn't resolve the `baseUrl` path when set from the Karma config, I've created a fix for this and your project runs just fine now on my laptop!

Does it work for you too if you install from the development branch, `npm i github:monounity/karma-typescript#next`?

**Comment by netzzwerg** [comment]
Hey @erikbarke crazy how fast you are and yes you nailed it again. Thank you!
