### ISSUE TITLE
Following instructions doesn't work

### ISSUE THREAD

**Issue by megamindbrian** [monounity/karma-typescript#134]
webpack: Compiling...
12 06 2017 11:31:43.460:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.3.4
12 06 2017 11:31:46.352:ERROR [compiler.karma-typescript]: node_modules/@angular/common/src/directives/ng_class.d.ts(48,34): error TS2304: Cannot find name 'Set'.

12 06 2017 11:31:46.353:ERROR [compiler.karma-typescript]: node_modules/@angular/compiler/src/aot/compiler.d.ts(48,32): error TS2304: Cannot find name 'Map'.

12 06 2017 11:31:46.354:ERROR [compiler.karma-typescript]: node_modules/@angular/compiler/src/compile_metadata.d.ts(369,20): error TS2304: Cannot find name 'Set'.

12 06 2017 11:31:46.354:ERROR [compiler.karma-typescript]: node_modules/@angular/compiler/src/compile_metadata.d.ts(371,28): error TS2304: Cannot find name 'Set'.

12 06 2017 11:31:46.355:ERROR [compiler.karma-typescript]: node_modules/@angular/compiler/src/compile_metadata.d.ts(373,15): error TS2304: Cannot find name 'Set'.

12 06 2017 11:31:46.355:ERROR [compiler.karma-typescript]: node_modules/@angular/compiler/src/compile_metadata.d.ts(375,23): error TS2304: Cannot find name 'Set'.

12 06 2017 11:31:46.355:ERROR [compiler.karma-typescript]: node_modules/@angular/compiler/src/compile_metadata.d.ts(377,17): error TS2304: Cannot find name 'Set'.

12 06 2017 11:31:46.356:ERROR [compiler.karma-typescript]: node_modules/@angular/compiler/src/compile_metadata.d.ts(379,25): error TS2304: Cannot find name 'Set'.

12 06 2017 11:31:46.356:ERROR [compiler.karma-typescript]: node_modules/@angular/compiler/src/output/output_ast.d.ts(444,63): error TS2304: Cannot find name 'Set'.

12 06 2017 11:31:46.356:ERROR [compiler.karma-typescript]: node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,16): error TS2304: Cannot find name 'Map'.

12 06 2017 11:31:46.356:ERROR [compiler.karma-typescript]: node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(32,16): error TS2304: Cannot find name 'Map'.

12 06 2017 11:31:46.356:ERROR [compiler.karma-typescript]: node_modules/@angular/core/src/change_detection/differs/keyvalue_differs.d.ts(23,18): error TS2304: Cannot find name 'Map'.

12 06 2017 11:31:46.356:ERROR [compiler.karma-typescript]: node_modules/@angular/core/src/di/reflective_provider.d.ts(87,123): error TS2304: Cannot find name 'Map'.

12 06 2017 11:31:46.357:ERROR [compiler.karma-typescript]: node_modules/@angular/core/src/di/reflective_provider.d.ts(87,165): error TS2304: Cannot find name 'Map'.

12 06 2017 11:31:46.357:ERROR [compiler.karma-typescript]: node_modules/@angular/http/src/headers.d.ts(52,71): error TS2304: Cannot find name 'Map'.

12 06 2017 11:31:46.357:ERROR [compiler.karma-typescript]: node_modules/@angular/http/src/url_search_params.d.ts(46,16): error TS2304: Cannot find name 'Map'.

12 06 2017 11:31:46.357:ERROR [compiler.karma-typescript]: node_modules/@angular/material/typings/core/overlay/scroll/scroll-dispatcher.d.ts(29,27): error TS2304: Cannot find name 'Map'.

12 06 2017 11:31:46.358:ERROR [compiler.karma-typescript]: node_modules/@angular/material/typings/core/platform/features.d.ts(2,51): error TS2304: Cannot find name 'Set'.

12 06 2017 11:31:46.358:ERROR [compiler.karma-typescript]: node_modules/@angular/material/typings/core/portal/dom-portal-host.d.ts(24,51): error TS2304: Cannot find name 'Map'.

12 06 2017 11:31:46.358:ERROR [compiler.karma-typescript]: node_modules/@angular/material/typings/core/portal/portal-directives.d.ts(43,51): error TS2304: Cannot find name 'Map'.

**Comment by erikbarke** [comment]
Hey @megamindbrian, could you run your project with Karma in debug mode, `logLevel: config.LOG_DEBUG` and attach the log output here please? It looks like some typings are missing.

**Comment by megamindbrian** [comment]
Sure. I did switch to istanbul-instrumenter-loader and made some progress on a proper config, all these related project should probably list that step, it isn't clear which parts this module controls since the instructions say to add it to frameworks, add another config section to karma.conf, plus adding something entirely different to webpack...

**Comment by erikbarke** [comment]
Which step should "these related projects" list? Which are "these related projects"? Karma-typescript consists of a Karma framework, preprocessor and a reporter, you need to add all of those to the Karma config, otherwise it won't work. Webpack isn't needed at all when running karma-typescript, so you can leave that out of the Karma config.

I take it that you moved on to another way of getting coverage, so I'm closing this.

**Comment by megamindbrian** [comment]
Got it working with webpack-instanbul-loader. But the line numbers are off,
probably because the source map points to the transpired version. I'll try
to get this working again with more configuration.
