### ISSUE TITLE
Error: Cannot find module 'base64-js' from '.'

### ISSUE THREAD

**Issue by AdrianMarinica** [monounity/karma-typescript#136]
When running `karma`, I am getting this error:

`Fatal error: Unable to resolve module [base64-js] from [/src/main/node_modules/karma-typescript/node_modules/buffer/index.js]`

Everything seems to be configured properly, am I missing something?

**Comment by erikbarke** [comment]
Hey @AdrianMarinica, has the module `base64-js` been installed properly by `npm`, does it exist in your `node_modules` folder?

**Comment by AdrianMarinica** [comment]
Hey @erikbarke!

I am sorry, it was my fault. I am using Bitbucket Pipelines for running my tests through karma-typescript. Locally it worked great, but when building I kept getting this error. I was not aware that Bitbucket Pipeline's default image uses a very old version of NPM, `npm: 2.14.7`. Then after I read the entire README for the project, I figured I should check that.

So there's nothing wrong with karma-typescript, I was just trying to use an unsupported version of NPM. 

I guess you can add `npm: 2.14.7` with Ubuntu to the list as well. 

Sorry again. Thanks for the quick response!

**Comment by erikbarke** [comment]
No worries, I'll add that to the list, what's your node version and ubuntu version?

**Comment by AdrianMarinica** [comment]
Ubuntu is at `ubuntu 14.04` and node is at `node: 4.2.1`

**Comment by erikbarke** [comment]
Added your version to the list, thanks for reporting 😃
