### ISSUE TITLE
.tsconfig is not loaded by default

### ISSUE THREAD

**Issue by QuantumInformation** [monounity/karma-typescript#138]
Is it really necessary to have this if the karma config is in the same dir as the tsconfig?
```js
  karmaTypescriptConfig: {
            tsconfig: "./tsconfig.json"
        },
```

**Comment by erikbarke** [comment]
Hey @QuantumInformation, as a matter of fact, yes! This lets users choose whether to include the project tsconfig,json and override/add to it in the Karma config. Users may choose not to include it and configure Typescript for production and testing in completely different ways, hope this answers your question 😃

**Comment by QuantumInformation** [comment]
Yes, sounds good.
