### ISSUE TITLE
Cannot find source when it exists

### ISSUE THREAD

**Issue by QuantumInformation** [monounity/karma-typescript#139]
My config has:

https://github.com/quantumjs/solar-popup/blob/master/karma.conf.js#L8

but when running `karma start` I get `Error: No source found for /Users/nikos/WebstormProjects/solar-popup/src/tests/SolarPopup.test.ts!`

![image](https://user-images.githubusercontent.com/216566/27188080-f9d6ff2e-51e4-11e7-87a5-a54b0a0c8781.png)

**Comment by erikbarke** [comment]
Ok, I've cloned your project and there are two instances of `karmaTypescriptConfig` in the karma config. The last one overwrites the first one and includes the tsconfig.json where "**/*.test.ts" are excluded, which excludes `SolarPopup.test.ts`.

If you want to use the tsconfig and override what's excluded, I'm working on a solution for that, #127!

**Comment by QuantumInformation** [comment]
Whoops! thx for that.

Is it still necessary to have the files prop if you have the include, I guess karma needs that?

**Comment by QuantumInformation** [comment]
I still have the same error:

![image](https://user-images.githubusercontent.com/216566/27233425-546c65d8-52b1-11e7-872c-db8f9fe45df4.png)

**Comment by erikbarke** [comment]
Yes, the `files` property is needed by karma, without it there would be nothing to run.

Did you remove the duplicated `karmaTypescriptConfig` sections and did you remove the `karmaTypescriptConfig.tsconfig` since your tsconfig.json excludes all ".test.ts" files?

Could you post your karma config here please?

**Comment by QuantumInformation** [comment]
Sure:

```js
module.exports = (config) => {

  config.set({

    frameworks: ["mocha", "karma-typescript"],

    files: [
      { pattern: "src/**/*.ts" }
    ],

    preprocessors: {
      "**/*.ts": ["karma-typescript"]
    },

    karmaTypescriptConfig: {
      include: ["src/**/*.ts"],
      tsconfig: "./tsconfig.json"
    },

    reporters: ["progress", "karma-typescript"],

    browsers: ["Chrome"],

    singleRun: false
  });
};
```

**Comment by erikbarke** [comment]
Ok, your tsconfig.json excludes "**/*.test.ts", which excludes `SolarPopup.test.ts`, which causes this error.

**Comment by QuantumInformation** [comment]
Ah thanks for that.
