### ISSUE TITLE
How to test single file without CommonJS wrapping code

### ISSUE THREAD

**Issue by mbarakaja** [monounity/karma-typescript#14]
I am working with Typescript files that doesn't export anything. Just flat codes that runs in the global namespace. When I run my tests (also written in TypeScript) `karma-typescript` output a wrapped code and the test is unable to find the global declared variables, functions, etc.

Is there a way to use this plugin with TypeScript code that doesn't need CommonJS or just use namespaces? Like:

``` JS
namespace MyNameSpace {

}
```

I am trying to make a library with Typescript, without using `SystemJS` or other module loaders.

**Comment by monounity** [comment]
@mbarakaja, there's now support for running the plugin without wrapping the transpiled code, it's in the [dev branch for the upcoming 2.1 release](https://github.com/monounity/karma-typescript/tree/2.1). If the compiler reports that no imports were found, no module loading code will be added to the transpiled sources.

If you want to try it out you can pull in the latest from this repo in your package.json:

`"karma-typescript": "git://github.com/monounity/karma-typescript.git#2.1"`

**Comment by mbarakaja** [comment]
Thanks for the quick response. I will try that branch and report here any issue.

**Comment by mbarakaja** [comment]
Hello @monounity 

After trying the branch 2.1 I can say it works pretty well. Each compiled code isn't wrapped and the tests can reach the tested code. The test coverage works awesome too. :+1:
