### ISSUE TITLE
Cannot read property 'debug' of undefined

### ISSUE THREAD

**Issue by mariposaben** [monounity/karma-typescript#143]
Hello, I am receiving the following error when running karma-typescript as an npm test task:

ERROR [karma]: TypeError: Cannot read property 'debug' of undefined
    at Coverage.instrument (C:\CEBTSource\Main\CodeExamples\NetSuiteTypeScriptCI
CD\node_modules\karma-typescript\dist\istanbul\coverage.js:20:21)
    at Object.callback (C:\CEBTSource\Main\CodeExamples\NetSuiteTypeScriptCICD\n
ode_modules\karma-typescript\dist\karma\preprocessor.js:23:42)
    at C:\CEBTSource\Main\CodeExamples\NetSuiteTypeScriptCICD\node_modules\karma
-typescript\dist\bundler\bundler.js:109:28
    at Array.forEach (native)
    at C:\CEBTSource\Main\CodeExamples\NetSuiteTypeScriptCICD\node_modules\karma
-typescript\dist\bundler\bundler.js:108:35
    at C:\CEBTSource\Main\CodeExamples\NetSuiteTypeScriptCICD\node_modules\karma
-typescript\dist\bundler\bundler.js:183:13
    at FSReqWrap.oncomplete (fs.js:123:15)
npm ERR! Test failed.  See above for more details.

karma configuration file:

module.exports = function (config)
{
	config.set(
	{
		/*
         * By default, Karma loads all sibling NPM modules which have a name
         * starting with karma-*. You can also explicitly list plugins you want
         * to load via the plugins configuration setting.
         */
        plugins: [
            "karma-*"
        ],
		// list of files / patterns to load in the browser
		files: [
			'spec/*.ts'
		],
		preprocessors:
		{			
			'src/**/*.ts': ['karma-typescript', 'coverage'],
			'spec/*.ts': ['karma-typescript']
		},		
		// level of logging
		// possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
		logLevel: config.LOG_INFO,
		// start these browsers
		// available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
		browsers: ['PhantomJS'],
		// frameworks to use
		// available frameworks: https://npmjs.org/browse/keyword/karma-adapter
		frameworks: ['jasmine', 'karma-typescript'],
		reporters: ['progress', 'trx', 'karma-typescript'],
		// the default configuration
		trxReporter:
		{
			outputFile: 'test-results.trx',
			shortTestName: false
		}
	}
	);
};

TypeScript configuration file:

{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "sourceMap": true,
        "allowJs": true
    },
	"include": [
        "src/**/*"
    ]
}

NPM configuration file:

{
  "name": "customerlanguage",
  "version": "1.0.0",
  "description": "",
  "main": "main.ts",
  "scripts": {
    "test": "karma start"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/node": "^7.0.5",
    "babel-core": "^6.22.1",
    "babel-loader": "^6.2.10",
    "glob": "^7.1.1",
    "jasmine-core": "^2.6.4",
    "karma": "^1.5.0",
    "karma-phantomjs-launcher": "^1.0.4",
    "karma-jasmine": "^1.1.0",
    "karma-trx-reporter": "~0.1",
	"karma-typescript": "^3.0.4",
    "script-loader": "^0.7.0",
    "tslint": "^5.2.0",
    "typescript": "^2.3.2",
    "webpack": "^2.5.1"
  },
  "scriptType": "scheduledscript",
  "signature": "Main()",
  "parameters": "",
  "targetFunction": ""
}

Thanks in advance for any help you can provide.

**Comment by erikbarke** [comment]
Hey @mariposaben, try including the source files in the karma config file section:

```js
files: [
   'src/**/.ts',
   'spec/.ts'
]
```

If that doesn't work, could you run your project with debug logging enabled in the karma config, `logLevel: config.LOG_DEBUG`, and attach the output as a file here please?

**Comment by mariposaben** [comment]
Erik, Thanks for the quick response. I added the source files to the file section but still get the same error. I turned debug on and the error is:

DEBUG [karma]: A browser has connected on socket AI9tKpQoGLjdspDQT_kZ
INFO [PhantomJS 2.1.1 (Windows 7)]: Connected on socket AI9tKpQoGLjdspDQT_kZ
DEBUG [bundler.karma-typescript]: Project has 64 import/require statements, code
 will be bundled
INFO [bundler.karma-typescript]: Bundled imports for 26 file(s) in 181 ms.
ERROR [karma]: TypeError: Cannot read property 'debug' of undefined
    at Coverage.instrument (C:\CEBTSource\Main\CodeExamples\NetSuiteTypeScriptCI
CD\node_modules\karma-typescript\dist\istanbul\coverage.js:20:21)
    at Object.callback (C:\CEBTSource\Main\CodeExamples\NetSuiteTypeScriptCICD\n
ode_modules\karma-typescript\dist\karma\preprocessor.js:23:42)
    at C:\CEBTSource\Main\CodeExamples\NetSuiteTypeScriptCICD\node_modules\karma
-typescript\dist\bundler\bundler.js:121:28
    at Array.forEach (native)
    at C:\CEBTSource\Main\CodeExamples\NetSuiteTypeScriptCICD\node_modules\karma
-typescript\dist\bundler\bundler.js:120:35
    at C:\CEBTSource\Main\CodeExamples\NetSuiteTypeScriptCICD\node_modules\karma
-typescript\dist\bundler\bundler.js:183:13
    at FSReqWrap.oncomplete (fs.js:123:15)
Let me know if you need more of the log? It looks to me like it is something to do with the Istanbul coverage class not having an instantiated logging object?

**Comment by erikbarke** [comment]
The logger is now initialized as early as possible and I've also added more debug logging in the code surrounding this issue. To test it on your end you can install from the development branch, `npm i github:monounity/karma-typescript#next`. If it still doesn't work, attach the entire debug log out as a file here please, that gives me a ton of information like your config etc, what gets initialized in what order etc.
