### ISSUE TITLE
feat: add source maps to libraries bundle

### ISSUE THREAD

**Issue by wawyed** [monounity/karma-typescript#144]
It would be nice if the karma-typescript-bundle was mapped back to the original files. so when debugging in unit tests is easier to know where the errors come from.

**Comment by erikbarke** [comment]
Hey @wawyed, awesome idea! This shouldn't be too hard to implement, all the pieces are already there.

**Comment by erikbarke** [comment]
There's basic support for source maps for the bundled packages now:

```js
karmaTypescriptConfig: {
    bundlerOptions: {
        sourceMap: true
    }
}
```

To try it out you can install from the dev branch, `npm i github:monounity/karma-typescript#next` ☺️

**Comment by wawyed** [comment]
You sir are on fire. I'll give it a try ^^

_Sent from my Samsung SM-G935F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by wawyed** [comment]
I just tried it, it works but it doesn't seem to keep the sourcemap comment for the original js. So if it had a map to typescript it doesn't show the original typescript code.

**Comment by erikbarke** [comment]
Source maps for the original code are now loaded (only first level) and it works for packages like `es6-promise`, `rxjs`, `zone.js`, I can step through the original source code. Packages like `@angular` and `diff` however, do *not* work, their source maps seem to be broken beyond belief 😠

**Comment by erikbarke** [comment]
@wawyed, have you tested the last commit, can I close this?

**Comment by wawyed** [comment]
I'm trying to test it but Im getting this when trying to npm install the branch 

npm ERR! code 128
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
npm ERR! fatal: No url found for submodule path 'examples/karma-ts-test-by-dts-file' in .gitmodules
npm ERR!

**Comment by erikbarke** [comment]
Oh great, I broke the git repo... I've cleaned up now and the build passes on the ci servers and I'm able to `npm i` the branch locally, does it work for you too now?

**Comment by wawyed** [comment]
Yes, I got it working, unfortunately even though is mapping from the bundle to the original TS the line that it stops doesn't match the correct one.

**Comment by erikbarke** [comment]
Which package isn't working when you debug, a specific one or all? I banged my head on my desk for days before realizing that some packages simply have incorrect source maps, I verified by loading a few packages directly in Chrome:

```html
<!DOCTYPE html>
<html>
<body>
    <script src="node_modules/@angular/core/bundles/core.umd.js"></script>
    <script src="node_modules/diff/dist/diff.js"></script>
    <script src="node_modules/es6-promise/dist/es6-promise.js"></script>
    <script>
        console.log("try setting a break point");
    </script>
</body>
</html>
```

Put this html file in the root of, for instance, the angular2 example project and open the html file in Chrome. The angular file will crash and you might have to hit reload before the source maps load but it's still possible to set break points.

Now add `import "es6-promise";` somewhere in the exampe project and run the test project and try setting break points.

This is the result I get with Chrome on OSX:

- `angular v4.3.4`, break points are off in both the simple test and in karma-typescript, weird `packages` paths
- `diff v3.3.0`, seems completely broken in both the simple test and in karma-typescript (src/convert/xml.js??)
- `es6-promise v4.1.1`, works in both the simple test and in karma-typescript

The pattern I see is if it works when loading a source map directly in Chrome, it will work in karma-typescript as well.

It seems some vendors have a broken build chain where they transpile with source maps first and then they add umd wrappers without updating the source map, which throws the line numbers off.

**Comment by wawyed** [comment]
The package I used as a test is one of our private npm package and I can validate that the sourcemaps are correctly generated as they work fine when I run the app.

**Comment by erikbarke** [comment]
New approach: I've modified one of the [typescript example projects](https://github.com/monounity/karma-typescript/tree/sourcemaps/examples/typescript-latest) to add the package `karma-typescript-es6-transform` (written in Typescript, transpiled with source maps) to the bundle.

Debugging this project works as expected, I can set a breakpoint in [src/hello.component.ts](https://github.com/monounity/karma-typescript/blob/sourcemaps/examples/typescript-latest/src/hello.component.ts#L12) and step through the code with correct line mappings.

Does it work if you install from the sourcemap branch, `npm i github:monounity/karma-typescript#sourcemaps` and debug the `typescript-latest` project or are the line numbers off? Is this an os/environment issue?

In your project, are the line numbers off by one or by a lot, or does the discrepancy grow as the line numbers grow?

**Comment by erikbarke** [comment]
@trwolfe13 @Salasar @patrickarlt, I would love some testing outside my environment for this, could you guys help me out please?

**Comment by wawyed** [comment]
Hi, sorry about the delay in the reply. I have tried the branch and I'm getting mixed results. Some ts files are getting remapped but others just show an empty file while trying to load the ts file.

**Comment by erikbarke** [comment]
Ok, you should get the same results for your project with the `next` and the `sourcemaps` branches, they both contain the same source map logic.

Does the [typescript-latest example project](https://github.com/monounity/karma-typescript/tree/sourcemaps/examples/typescript-latest) on the `sourcemaps` branch work, are you able to set a breakpoint in [src/hello.component.ts](https://github.com/monounity/karma-typescript/blob/sourcemaps/examples/typescript-latest/src/hello.component.ts#L12) and step into the code for `karma-typescript-es6-transform`? Are the line mappings correct for the (one and only) Typescript file in the `karma-typescript-es6-transform` package?

**Comment by wawyed** [comment]
Yes, that seems to work correctly. One difference that I didn't mention, my compiled code uses inlineSources in the sourceMap so it doesn't point to a different file, contains the original code inside the sourcemap file.

**Comment by erikbarke** [comment]
Great, so it's not an os/environment issue then... Which leaves us with what? If you look at [source-map.ts](https://github.com/monounity/karma-typescript/blob/next/src/bundler/source-map.ts), there's nothing special going on in my code; file content is fed to `combine-source-map` which performs the actual magic.

I have yet to find a correct source map that doesn't work in karma-typescript, apart from your source maps, which I can't test since it's a private package.

I'm out of ideas here 😕

**Comment by wawyed** [comment]
I'm going to try to reproduce it in your example.

**Comment by wawyed** [comment]
Okay so I have created an example that you can reproduce :)

You can find it here:

https://github.com/wawyed/karma-typescript/tree/sourcemaps

Hope it helps!

**Comment by erikbarke** [comment]
Awesome!! Your source maps have sources that look like this:

```js
[
    'webpack:///webpack/bootstrap a5a1de700b3a78264108',
    'webpack:///./src/services/index.ts',
    'webpack:///external "@angular/core"',
    'webpack:///./index.ts',
    'webpack:///./src/index.ts',
    'webpack:///./src/services/MhrWindow/MhrWindow.service.ts',
    'webpack:///./src/mhrCommon.module.ts',
    'webpack:///external "@angular/common"'
]
```

The `webpack:///`prefix apparently makes `combine-source-map` create non-working source maps, so I created a fix that simply removes the prefix, you can try it out on the `next`branch, `npm i github:monounity/karma-typescript#next` :rocket:

**Comment by wawyed** [comment]
Hello, good news is that the files are not blank anymore :D. Bad news... the lines seem offset by a few lines.

**Comment by wawyed** [comment]
I found this tool to check sourcemaps visually. Maybe it can help you find out what's wrong:

http://sokra.github.io/source-map-visualization/

**Comment by erikbarke** [comment]
Darn.

I loaded *@ mhrwebux/common/index.js* and its source map from your tar ball into the visualization tool you linked and inspected row 127-129 of *index.js*:

```js
function _window() {
    return window;
}
```
Row 128 (`return window;`) points back to row 4 in *webpack:///src/services/MhrWindow/MhrWindow.service.ts* [4->**4**:2] [10->**4**:8] [11->**4**:9] [17->**4**:15] [18->**4**:16].

I then launched the typescript-latest project from your fork, with the fix for empty files, and located the `function _window() {` part in the bundle (around line 22000 in my case). If I set a breakpoint on the `return window;` row in Chrome, the mapped file *MhrWindow.service.ts* opens with a breakpoint on row 4 which contains `return window;`.

Row 162 of *index.js*, `var core_1 = __webpack_require__(1);` points back to row 2 in *webpack:///src/mhrCommon.module.ts* [0->**2**:0]. If I locate that row in the bundle and set a breakpoint, the mapped file *mhrCommon.module.ts* opens with a breakpoint on row 2 which contains `import { NgModule } from '@angular/core';`.

This seems pretty accurate and consistent to me, could you give me an example of a file and a row in your fork where the source mapping is off please?

I suspect there is more webpack magic hidden in your source maps 😕

**Comment by wawyed** [comment]
If I try to put a breakpoint on the getter function it adds it to the class definition, have a look at this:

![image](https://user-images.githubusercontent.com/4390806/30350043-10a9d4a6-980d-11e7-81e7-3aee2b297d9d.png)

**Comment by erikbarke** [comment]
Aah, windows line breaks, the gift from the [dot-matrix printers era](https://stackoverflow.com/questions/6521685/why-does-windows-use-cr-lf) that keeps on giving ☺️

If I hardcode `\n` as line breaks in the bundler instead of `os.EOL` (The Right Way&trade;) the source maps seem to work correctly also on windows. This is clearly a CRLF issue, I'll see if I can come up something less hacky.

**Comment by wawyed** [comment]
I was going to say it might be something related to line endings since you didn't seem to have issues.

Could you do something like?
```
var nl = (process.platform === 'win32' ? '\r\n' : '\n')
```

**Comment by erikbarke** [comment]
This is exactly what `os.EOL` does, it returns the correct newline for each platform, ie `\r\n` on windows. What I did was using a hardcoded `\n` in the bundler regardless of platform, which made the source maps work correctly, go figure 😕

**Comment by wawyed** [comment]
hmm, from what I can see the sourcemap gets converted into a base64 string that gets read by chrome, so maybe chrome wants linux endings always?

**Comment by erikbarke** [comment]
I'm using the fix the hardcoded unix line breaks, it doesn't seem to affect anything else but the source maps, the fix is on the next branch, `npm i github:monounity/karma-typescript#next`!

**Comment by wawyed** [comment]
So, that fixes the issue :)... unfortunately, it seems that there is some issue with the sourcemaps of the src or test files. I don't seem to be able to set a breakpoint in some statements, specially if I have new lines in between.

The crossed lines are the ones I'm not able to add a breakpoint.

![image](https://user-images.githubusercontent.com/4390806/30430278-a30b3114-9952-11e7-9b46-5327c0977a78.png)


But if i remove the line lines..

![image](https://user-images.githubusercontent.com/4390806/30430344-d753c40e-9952-11e7-9ff6-9c457304f250.png)

Works fine.

Don't know if it's a chrome thing or what.

**Comment by erikbarke** [comment]
This must be a Chrome issue, I get the same behavior on windows with and without the latest line break fix. Also, the new source maps logic only affects the main bundle, the project ts files still use the inline source maps generated by Typescript.

Anyway, I managed to set breakpoints in Chrome on windows by setting them in the compiled file and the breakpoints end on the correct lines, so it's a Chrome issue I guess:

<img width="659" alt="screen shot 2017-09-14 at 16 33 59" src="https://user-images.githubusercontent.com/5539280/30435921-3d7e1d52-996b-11e7-8f55-7f5a113e796e.png">

**Comment by erikbarke** [comment]
Ok, case closed then ☺️

**Comment by wawyed** [comment]
Releasing the new version soon? :)

**Comment by erikbarke** [comment]
3.0.6 is on npm now 🚀
