### ISSUE TITLE
coverage launcher directory name

### ISSUE THREAD

**Issue by typedefJorge** [monounity/karma-typescript#147]
Hey guys first of all, this is an amazing tool, second, im having an issue with the name of the directory generated for each launcher. Im trying to send the coverage json generated by this tool to codecov, the only problem im having is that i cant control the name of the directory generated for each launcher. For example if the tests get run for chrome it generates coverage/Chrome 59.0.3071 (Windows 8 0.0.0)/coverageFiles. So this is an issue for me because I want to have a scripts section in my package.json that looks something like this:
"scripts": {
        "ci-test": "./node_modules/.bin/karma start karma.conf.js --browsers PhantomJS --single-run",
        "cover": "./node_modules/.bin/codecov -f coverage-json/PhantomJS 2.1.1 (Linux 0.0.0)/cover.json"
    },
but npm doesnt like the path im trying to pass in as the -f argument to codecov

Im not sure if this is something this tool is doing or if its something inherent to karma-coverage. Just wondering if there was anything you guys could do to give us the option to pass in the kind of directory name that we want for each launcher. Thanks!!

**Comment by erikbarke** [comment]
Hey @typedefJorge, have you tried setting the `directory` and `subdirectory` properties of the setting ` karmaTypescriptConfig.reports`?

**Comment by typedefJorge** [comment]
yeah once i used the subdirectory property it seems to have merged all the reports from all the launchers. Thanks for the help!!
