### ISSUE TITLE
Update reference to browserify-zlib

### ISSUE THREAD

**Issue by ryanarobbins** [monounity/karma-typescript#149]
Please update the reference to browserify-zlib to version 0.2.0 if possible.  They had a duplicate key in their package.json in the version currently being referenced and it causes some of my tooling to throw an error and run slowly.

Thank you.

**Comment by erikbarke** [comment]
Hey @ryanarobbins, I've updated all the browser shims, including browserify-zlib. Does it work for you if you install from the development branch, `npm i github:monounity/karma-typescript#next`?

**Comment by ryanarobbins** [comment]
Thank you so much!  When I use the version from the dev branch it is pulling the newer version of the offending package.  I think that should take care of it!
