### ISSUE TITLE
Unable to use lodash-es (es6-transform) together with tests (angular 4)

### ISSUE THREAD

**Issue by nadavsinai** [monounity/karma-typescript#150]
Hi,
Thanks for your great work. 
I'm trying to setup karma to work with your framework for my angular 4 lib. 
I am using lodash-es so I added both relevant transforms.
however  when importing the following
````
import difference from 'lodash-es/difference';
````
I am getting  the following error

```` 
Uncaught TypeError: (0 , _defineProperty2.default) is not a function
````
my karma.config is as follows, tsconfig is unused (all inlined here)
``` 
config.set({
	frameworks: ["jasmine", "karma-typescript"],
		files: [
			{pattern: "./base.spec.ts"},
			{pattern: "./src/**/*.+(ts|html)"}
		],
		preprocessors: {
			"**/*.ts": ["karma-typescript"]
		},
		karmaTypescriptConfig: {
			bundlerOptions: {
				entrypoints: /\.spec\.ts$/,
				transforms: [
					require("karma-typescript-angular2-transform"),
					require("karma-typescript-es6-transform")()
				]
			},
			compilerOptions: {
                                exclude: ['dist', 'compiled', 'inlined'],
				module: "commonjs",
				baseUrl: './',
				"inlineSourceMap": true,
				"inlineSources": true,
				"emitDecoratorMetadata": true,
				"downlevelIteration": true,
				"importHelpers": true,
				"allowSyntheticDefaultImports": true,
				"sourceMap": false,
				"noEmitHelpers": true,
				"experimentalDecorators": true,
				target: 'es5',
				lib: ["ES2015", "DOM", "es2016", "es2017"],
			}
		},
		reporters: ["progress", "karma-typescript"],
		browsers: ['Chrome'],
});

I really appreciate your help!
Nadav

**Comment by erikbarke** [comment]
Hey @nadavsinai, I added your config and the lodash import to the example project for angular2 (running angular 4.0.3) on the development branch and I don't get this error.

Could you run your project with debug logging enabled in Karma, `logLevel: config.LOG_DEBUG` and attach the output as a text file here please?

You could also try running your project using the dev branch, `npm i github:monounity/karma-typescript#next`.

**Comment by nadavsinai** [comment]
Hi @erikbarke  and thanks for your quick reply
[here's the log](https://gist.github.com/nadavsinai/d8c686b3318097aae0831fabf04a940f)


I will now try dev branch and report

**Comment by nadavsinai** [comment]
interestingly the next branch has a longer stack trace over the same error
````
karma-typescript-bundle-14768S2xSbbxmkdqB.js:89184 Uncaught TypeError: (0 , _defineProperty2.default) is not a function
    at baseSetToString (karma-typescript-bundle-14768S2xSbbxmkdqB.js:89184)
    at karma-typescript-bundle-14768S2xSbbxmkdqB.js:43610
    at baseRest (karma-typescript-bundle-14768S2xSbbxmkdqB.js:89251)
    at Object.global.wrappers.C:/Data/ui-elements-webkit/node_modules/lodash-es/difference.js../isArrayLikeObject.js (karma-typescript-bundle-14768S2xSbbxmkdqB.js:89301)
    at require (commonjs.js:17)
    at commonjs.js:18
    at Object.global.wrappers.C:/Data/ui-elements-webkit/src/elements/button/button.component.ts.tslib (button.component.ts:7)
    at require (commonjs.js:17)
    at commonjs.js:18
    at Object.global.wrappers.C:/Data/ui-elements-webkit/src/elements/button/button.component.spec.ts.tslib (button.component.spec.ts:3)
````

**Comment by nadavsinai** [comment]
the @next branch sorts out the sourcemapping problem I had!! in the release (3.0.4) I only got sourcemaps for the specs whilst the tested components (imported from the spec) were only available in js (orignially in ts) in @next it works!! well done

**Comment by erikbarke** [comment]
Is there a reason you've wrapped the calls to the transforms in inline functions? The es6 transform gets called, but it gets called hundreds of times with the same file, `/lodash-es/difference.js`. What does the wrapper function look like? Does it work if you replace the wrapper function with `require("karma-typescript-es6-transform")()`?

**Comment by sjswoboda** [comment]
Similar issue:
`Uncaught TypeError: (0 , _nativeCreate2.default) is not a function`

We are using quite a few lodash-es functions. We're not wrapping the transform functions though...

Using karma-typescript#next

**Comment by nadavsinai** [comment]
I looked at the log and I now see what you mean by "wrapping" the transform functions, but I actually didn't do anything fancy, if you look at the config above you can see I just (cut & paste) called the transforms with require
````
...
transforms: [
					require("karma-typescript-angular2-transform"),
					require("karma-typescript-es6-transform")()
				]
....
````

**Comment by nadavsinai** [comment]
I see somthing interesting when debugging this. __defineProperty2.defualt is actually an object with the __esModule thing on it, which has a defualt which in turn is an object with .default property which is a module and so on recursively forever (or at least until I get bored...) I think es6-transform is transforming its own output in a loop

**Comment by sjswoboda** [comment]
My bad, my lib was not correct. Works fine if I set my compilerOptions with lib as follows:

`["dom","es5","es6","scripthost"]`

**Comment by nadavsinai** [comment]
mine was not far off but I tried changing to your lib setting (scripthost was missing) and it didn't change

**Comment by sjswoboda** [comment]
Yes, sorry; I had commented out the unit test to be stupid simple...but once I import a module, then I get the same error...so not fixed :(

**Comment by nadavsinai** [comment]
![screen shot 2017-07-18 at 23 41 53](https://user-images.githubusercontent.com/2870816/28338860-e108ad4c-6c12-11e7-82e2-3ccba11ec335.png)

**Comment by erikbarke** [comment]
Ok, does anyone of you have a repo I could take a look at? This is obviously a bug, but I haven't been able to reproduce it 😞

**Comment by nadavsinai** [comment]
OK, ive done an example repo, taking all proprietary code out and leaving the shell of our lib's setup
[https://github.com/Algotec/karma-typescript-bug-demo](https://github.com/Algotec/karma-typescript-bug-demo)
run yarn && npm run peers
then you can run npm run tdd to start karma and see the error
thanks for your help!

**Comment by erikbarke** [comment]
@nadavsinai, awsome! I'll be able to try your repo out sometime next week 😃

**Comment by erikbarke** [comment]
@nadavsinai, I was able to reproduce this bug when running your demo project!

**Comment by erikbarke** [comment]
Ok, this is what I've gathered this far, it seems this error is caused by race conditions between `zone.js` and `lodash-es`, ie the order of the import statements matter.

I made a few modifications to the [typescript-latest example project](https://github.com/monounity/karma-typescript/tree/master/examples/typescript-latest) to produce this error:

```bash
npm install lodash-es zone.js
```

Then I edited `src/hello.component.ts` to look like this:
```js
import "zone.js/dist/zone";

import difference from "lodash-es/difference";
import { HelloService } from "./hello-service.interface";

export class HelloComponent {

    constructor(private helloService: HelloService) {}

    public sayHello(): string {

        let a = [1, 2, 3];
        let b = [2, 3, 4];
        let c = difference(a, b);
        console.log(c);

        return this.helloService.sayHello();
    }
}
```

Running `npm test` now produces the same error as you guys get. If I move the `zone.js` import to after the `lodash-es` import it works, go figure 😒

**Comment by erikbarke** [comment]
An easy way to fix this is to simply add `import "lodash-es/difference";` to the top of base.spec.ts, before anything else!

**Comment by nadavsinai** [comment]
Thanks @erikbarke for your help, your workaround works perfectly, when can we expect a new release for the es6-transform?

**Comment by erikbarke** [comment]
Karma-typescript-es6-transform@1.0.2 is on npm now!
