### ISSUE TITLE
Single entry point to facilitate environment bootstrapping

### ISSUE THREAD

**Issue by michaelbull** [monounity/karma-typescript#151]
Hi, I'm trying to use `karma-typescript` for testing components in my Aurelia based project.  The ability to test components is reliant on the installation of [`jasmine-async`](https://github.com/facebook/jest/blob/master/packages/jest-jasmine2/src/jasmine_async.js) (provided by the [`jest-jasmine2`](https://github.com/facebook/jest/tree/master/packages/jest-jasmine2) package), as shown in their example project [here](https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-typescript-webpack/test/karma-bundle.js#L1-L6).

They use a single entry file, named `karma-bundle.js`, to ensure that the `jasmine-async` library is included and installed globally. I'm wondering how I would do this in `karma-typescript` as there is no "single point of entry" in which I can globally install the library - it seems that every single test is its own point of entry.

Does `karma-typescript` facilitate installing and configuring libraries that are globally available to the full test context? If so can you please explain how to do it as the README doesn't seem to cover it.

Thanks in advance.

**Comment by erikbarke** [comment]
Hey @michaelbull, the [angular2 example project](https://github.com/monounity/karma-typescript/tree/master/examples/angular2) uses the `base.spec.ts` file to make sure polyfills are loaded globally before the tests are executed, it's the first file in the Karma config file section. Would a similar setup work for you?

**Comment by michaelbull** [comment]
That's great, thanks very much!
