### ISSUE TITLE
Angular, Error: Can't resolve all parameters for MyService: (?)

### ISSUE THREAD

**Issue by AnimaMundi** [monounity/karma-typescript#155]
I can't seem to get reflection for dependency injection to work properly, I need to explicitly use the @Inject decorator to resolve this error.

`config/karma-common.conf`
``` javascript
const merge = require('webpack-merge');
const commonConfig = require('./config/karma-common.conf');

module.exports = function (config) {
  config.set(merge(commonConfig, {
    basePath: 'lib',
    karmaTypescriptConfig: {
      coverageOptions: {
        exclude: [
          /\.?(d|spec|test|module|index)\.ts$/i,
          /(test|utilities)\/*/
        ]
      },
      reports: {
        html: {
          directory: 'coverage',
          subdirectory: 'html',
          filename: 'report'
        }
      }
    },
    reporters: ['spec', 'karma-typescript'],
    browsers: ['PhantomJS'],
    logLevel: config.LOG_INFO
  }));
}
```

`karma.conf.js`
``` javascript
const os = require('os');

function getIpAddress() {
  let interfaces = os.networkInterfaces();

  let addresses = [];
  for (let i in interfaces) {
    for (let j in interfaces[i]) {
      let address = interfaces[i][j];
      if (address.family === 'IPv4' && !address.internal) {
        addresses.push(address.address);
      }
    }
  }

  if (addresses.length > 0) {
    return addresses[0];
  }

  return '127.0.0.1';
};

module.exports = {
  frameworks: ['jasmine', 'karma-typescript'],
  files: [
    'src/index.spec.ts',
    {
      pattern: 'src/**/*.+(ts|html)'
    },
    {
      pattern: 'test/**/*.ts'
    },
    {
      pattern: 'src/assets/**/*',
      watched: false,
      included: false,
      served: true,
      nocache: false
    }
  ],
  proxies: {
    "/": "http://localhost:8080/src/assets/"
  },
  exclude: [],
  preprocessors: {
    '**/*.ts': ['karma-typescript', 'coverage']
  },
  karmaTypescriptConfig: {
    bundlerOptions: {
      entrypoints: /\.spec\.ts$/,
      transforms: [
        require('karma-typescript-angular2-transform')
      ]
    },
    compilerOptions: {
      lib: ['ES2015', 'DOM']
    },
    tsconfig: 'tsconfig.test.json'
  },
  urlRoot: '/_karma_/',
  hostname: getIpAddress(),
  port: 9876,
  colors: true,
  autoWatch: false,
  singleRun: true,
  concurrency: Infinity
};
```

`src/index.spec.ts`
``` javascript
/// <reference path="../typings/index.d.ts" />

import 'core-js/es6';
import 'core-js/es7/reflect';

import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';

import { TestBed } from '@angular/core/testing';
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';

TestBed.initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());
```

This will not work for me:
``` javascript
import { Injectable } from '@angular/core';
import { MyOtherService } from '../my-other';

@Injectable()
export class MyService {
  constructor(private myOtherService: MyOtherService) { }
}
```

But this will:
``` javascript
import { Injectable, Inject } from '@angular/core';
import { MyOtherService } from '../my-other';

@Injectable()
export class MyService {
  constructor(@Inject(MyOtherService) private myOtherService: MyOtherService) { }
}
```

The first example of MyService works perfectly in the browser so it should in theory work with Karma TypeScript as well.

**Comment by erikbarke** [comment]
Hey @AnimaMundi, are the providers set up in a bootstrap class or similar that isn't included in the test run? Does it work if you add something like this to your test?

```js
beforeEach(async(() => {

    return TestBed
        .configureTestingModule({
            declarations: [MyService],
            providers: [{ provide: MyOtherService, useValue: new MyOtherService() }] // or a MyOtherService mock
        })
        .compileComponents()
        .then(() => {
            fixture = TestBed.createComponent(MyService);
        });
}));
```

**Comment by AnimaMundi** [comment]
Hey @erikbarke, thanks for getting back to me!

I am already providing the "parameters" in question to the testing module, so no, unfortunately it doesn't work if I try that. Since this does work when I explicitly add the @Inject decorator to the service that I'm trying to test, I don't think this has anything to do with the test module setup or providing the dependencies for that test module.

I don't know enough about this to be sure, but my first guess is it's something to do with the TypeScript transpilation and/or Reflect Metadata, because to me it looks like reflection is broken.

**Comment by erikbarke** [comment]
Ok, I modified the [Angular 2 example project](https://github.com/monounity/karma-typescript/tree/master/examples/angular2) to test injecting a service:

- `src/app/my-other.ts` (new service class):
```js
export class MyOtherService {
    public sayHello() {
        console.log("hello");
    }
}
```
- `src/app/hello.ts`:
```js
import { Component, Injectable } from "@angular/core";
import { MyOtherService } from "./my-other";

@Component({
    selector: "app-hello",
    styleUrls: ["../assets/style/main.css", "../assets/style/main.less", "../assets/style/main.scss"],
    templateUrl: "hello.html"
})
@Injectable()
export class HelloComponent {
    public title = "Hello :)";
    constructor(private myOtherService: MyOtherService) {
        myOtherService.sayHello();
    }
}
```

- `src/app/hello.spec.ts`
```js
import { DebugElement } from "@angular/core";
import { async, ComponentFixture, TestBed } from "@angular/core/testing";
import { By } from "@angular/platform-browser";

import { HelloComponent } from "./hello";
import { MyOtherService } from "./my-other";

describe("HelloComponent", () => {

    let fixture: ComponentFixture<HelloComponent>;

    beforeEach(async(() => {

        return TestBed
            .configureTestingModule({
                declarations: [HelloComponent],
                providers: [{ provide: MyOtherService, useValue: new MyOtherService() }]
            })
            .compileComponents()
            .then(() => {
                fixture = TestBed.createComponent(HelloComponent);
            });
    }));

    it("should display original title", () => {

        let debugElement = fixture.debugElement.query(By.css("h1"));
        fixture.detectChanges();

        expect(debugElement.nativeElement.textContent).toEqual("Hello :)");
    });

    it("should display a different test title", () => {

        let debugElement = fixture.debugElement.query(By.css("h1"));

        fixture.componentInstance.title = "Test Title";
        fixture.detectChanges();

        expect(debugElement.nativeElement.textContent).toEqual("Test Title");
    });
});
```

This works when I run `npm test`, the service gets injected, it logs 'hello' twice etc. Does this describe your scenario? Do you have a repo that reproduces the error that I could take a look at?

**Comment by AnimaMundi** [comment]
Yeah surely enough that works for me too when I start from your example project. I don't have access to the project where I'm running into this issue until next week so I will try trace my setup configuration once I have the project again and see if I can pin down the issue! Thanks for your help so far.

**Comment by AnimaMundi** [comment]
Sorry about the delay, it's obvious this is a problem with the configuration on my side anyway. I'll post again with the solution when I get a chance to fix it but so far I haven't been able to resolve it yet.

**Comment by AnimaMundi** [comment]
Dammit, I was missing `"emitDecoratorMetadata"` from my tsconfig.test.json...

So I guess I was right that reflection was broken 😆 just never thought to check my tsconfig for the problem. Thanks for your patience with this and sorry for wasting your time investigating such a simple oversight!

**Comment by mukeshsmk** [comment]
constructor(@Inject(media) service: media)

**Comment by mukeshsmk** [comment]
compiler.js:485 Uncaught Error: Can't resolve all parameters for File: (?, ?).

I Got this error any help pls,
this is my code 

import { Component } from '@angular/core';
import { NavController, Platform } from 'ionic-angular';
import { Media, MediaObject } from '@ionic-native/media';

import { File } from '@ionic-native/file';

@Component({
  selector: 'page-audio',
  templateUrl: 'audio.html'
})

export class AudioPage {
public music:any;

    constructor(private media: Media, private file: File) { }

   startRecording(){ 
    this.file.createFile(this.file.tempDirectory, 'my_file.m4a', true).then(() => {
     this.music = this.media.create(this.file.tempDirectory.replace(/^file:\/\//, '') + 'my_file.m4a');
     this.music.startRecord();
      window.setTimeout(() =>  this.music.stopRecord(), 10000); window.setTimeout(() =>  this.music.stopRecord(), 10000);
    });
   }

     stopRecording() {
         
     this.music.stopRecord();
      
      }
    
      startPlayback() {
        this.music.play();
       
      }
    
      stopPlayback() {
        this.music.stop();
       
      }
};

**Comment by thw0rted** [comment]
If anybody comes across this, and `emitDecoratorMetadata` is not the issue, scrub through your Karma errors with a fine-toothed comb.  I found a warning that `node_modules/core-js/bundles/reflect.umd` did not match any files, because I forgot the ".js" at the end.  (I had copy/pasted from a TS `import` in my `polyfills.ts`, which wasn't used by the test runner because it imported the production version of Zone etc.)

It would be great if Angular warned you when reflection isn't polyfilled, maybe I should open an issue with them?
