### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by cacothi** [monounity/karma-typescript#157]
Hi Guys,

I'm trying to use karma-typescript and getting the following errorr:

`C:\Dev\Lab\my-test\node_modules\karma-typescript\dist\karma\framework.js:21
            _this.log.debug("Configuration:\n", JSON.stringify(config, _this.replacer, 3));
                                                     ^
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Framework.create (C:\Dev\Lab\my-test\node_modules\karma-typescript\dist\karma\framework.js:21:54)
    at Array.invoke (C:\Dev\Lab\my-test\node_modules\di\lib\injector.js:75:15)
    at Injector.get (C:\Dev\Lab\my-test\node_modules\di\lib\injector.js:48:43)
    at C:\Dev\Lab\my-test\node_modules\karma\lib\server.js:143:20
    at Array.forEach (native)
    at Server._start (C:\Dev\Lab\my-test\node_modules\karma\lib\server.js:142:21)
    at Injector.invoke (C:\Dev\Lab\my-test\node_modules\di\lib\injector.js:75:15)
    at Server.start (C:\Dev\Lab\my-test\node_modules\karma\lib\server.js:103:18)
    at Object.exports.run (C:\Dev\Lab\my-test\node_modules\karma\lib\cli.js:280:26)
    at Object.<anonymous> (C:\Dev\Lab\my-test\node_modules\karma\bin\karma:3:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! Test failed.  See above for more details.`

I have followed the following steps:
- ng new my-app
- ng eject
- npm i -D karma-typescript
- npm i -D karma-typescript-angular2-transform

and then changed the karma.config as following:

`// Karma configuration file, see link for more information
// https://karma-runner.github.io/0.13/config/configuration-file.html

module.exports = function (config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', '@angular/cli', 'karma-typescript'],

    files: [
      { pattern: "base.spec.ts" },
      { pattern: "src/app/**/*.+(ts|html)" }
    ],

    preprocessors: {
      "**/*.ts": ["karma-typescript"]
    },

    plugins: [
      require('karma-jasmine'),
      require('karma-typescript'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-coverage-istanbul-reporter'),
      require('@angular/cli/plugins/karma')
    ],

    client: {
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },
    coverageIstanbulReporter: {
      reports: ['html', 'lcovonly'],
      fixWebpackSourcePaths: true
    },
    angularCli: {
      environment: 'dev'
    },
    reporters: ['progress', 'karma-typescript'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: false,
    browsers: ['Chrome'],
    singleRun: true,
    karmaTypescriptConfig: {
      bundlerOptions: {
        entrypoints: /\.spec\.ts$/,
        transforms: [
          require("karma-typescript-angular2-transform")
        ]
      },
      coverageOptions: {
        instrumentation: true
      }
    },
  });
};
`

Then running npm test (which runs karma start ./karma.conf.js)

Am I missing something?

**Comment by erikbarke** [comment]
Hey @cacothi, the `@angular/cli` framework seems to have circular references and since it isn't needed when running unit tests with `karma-typescript` I simply removed it from the Karma config. I also made few other changes to get rid of Typescript compiler warnings etc and came up with this config:

```js
module.exports = function (config) {
  config.set({

    frameworks: ["jasmine", "karma-typescript"],

    files: [
      { pattern: "base.spec.ts" },
      { pattern: "src/app/**/*.+(ts|html)" }
    ],

    preprocessors: {
      "**/*.ts": ["karma-typescript"]
    },

    reporters: ["progress", "karma-typescript"],
    browsers: ["Chrome"],
    singleRun: true,

    karmaTypescriptConfig: {
      tsconfig: "./tsconfig.json",
      bundlerOptions: {
        entrypoints: /\.spec\.ts$/,
        transforms: [
          require("karma-typescript-angular2-transform")
        ]
      }
    }
  });
};
```
Running `npm test` now runs 3 tests successfully 😃
