### ISSUE TITLE
`coverage-final.json` does not work with current version of `istanbul`

### ISSUE THREAD

**Issue by nros** [monounity/karma-typescript#158]
The error
----------

Using the created JSON file `coverage-final.json` with current version of `istanbul` fails with exception:
```
./node_modules/.bin/nyc report --reporter lcovonly
/Users/YYY/Documents/my-project/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:32
        writer.println('FN:' + [meta.decl.start.line, meta.name].join(','));
                                         ^

TypeError: Cannot read property 'start' of undefined
    at /Users/YYY/Documents/my-project/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:32:42
    at Array.forEach (native)
    at LcovOnlyReport.onDetail (/Users/YYY/Documents/my-project/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:30:28)
    at Visitor.(anonymous function) [as onDetail] (/Users/YYY/Documents/my-project/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/Users/YYY/Documents/my-project/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:123:17)
    at /Users/YYY/Documents/my-project/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach (native)
    at visitChildren (/Users/YYY/Documents/my-project/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:115:32)
    at ReportNode.Node.visit (/Users/YYY/Documents/my-project/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:126:5)
    at Tree.visit (/Users/YYY/Documents/my-project/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:158:20)
```

cause
----------

The problem lies with utilizing an old, unmaintained version of `istanbul` with `karma-typescript` (see [unmaintained istanbul](https://github.com/gotwarlost/istanbul)). The current version of `istanbul` require an enhanced version of `coverage-final.json` file, so coverage JSON files created with `karma-typescript` can not be further processed and used.
see the following commits with `istanbul`:
* [use new coverage attrs - commit 7db0855](https://github.com/istanbuljs/istanbuljs/commit/7db085552bb3f028e937b662892db70039f101bf)
* [use new coverage attrs - commit 8ec91a1](https://github.com/istanbuljs/istanbuljs/commit/8ec91a1618f2097fee271080c7086ee56ac98fd1)

solution
--------

Please update to the maintained, current version of `istanbul` to make the created JSON coverage file work again.

details
-------

The old `istanbul` version does not include the specification `decl` for each function, which is denoting the position of declaration of the function within the source code.

This is a [`prettyjson`](https://www.npmjs.com/package/prettyjson) print-out of a JSON file created with current release of `karma-typescript` utilizing old `istanbul` v0.4.
```
  fnMap: 
    1: 
      name: (anonymous_2)
      line: 17
      loc: 
        start: 
          line:   17
          column: 0
        end: 
          line:   null
          column: -1
```

And this is the print out for the same test, created with current `istanbul`:
```
  fnMap: 
    0: 
      name: (anonymous_2)
      decl: 
        start: 
          line:   17
          column: 0
        end: 
          line:   null
          column: -1
      loc: 
        start: 
          line:   17
          column: 0
        end: 
          line:   17
          column: -1
```

Although `decl` and `loc` are the same in this example, they need not to be.

to reproduce
--------------

1. run a test with `karma-typescript` to create a `coverage-final.json` file. my settings are
```JavaScript
        karmaTypescriptConfig: {
            bundlerOptions: {
                entrypoints: /\.spec\.[jt]s$/
            },


            compilerOptions: _.extend({}, defaultTSOptions, {
                allowJs: true,
                checkJs: true,
                declaration: false,
                inlineSourceMap: true,
                inlineSources: false,
                module: "commonjs",
                rootDir: env.paths.root,
                sourceMap: false,
            }),
            reports: {
                "json": { 
                    directory : "coverage/karma-mocha/",
                    filename: "coverage-final.json",
                },
                "text": ""
            },
        },

```
2. copy the created file `coverage-final.json` to the default `nyc` working/temp directory `.nyc_output`
```bash
cp coverage/PhantomJS\ 2.1.1\ \(Mac\ OS\ X\ 0.0.0\)/coverage-final.json .nyc_output/
```
3. run `nyc` to consume the coverage file
```
./node_modules/.bin/nyc report --reporter cobertura
```

why - what to achieve
----------------
`nyc` merges all JSON files within its directory `.nyc_output` to create the report. This seems the easiest and most natural way of merging such files of various test runs and create an overall report (see https://gist.github.com/rundef/22545366591d73330a48b8948fa060a7). Other packages like [`istanbul-merge`](https://www.npmjs.com/package/istanbul-merge) use current versions of `istanbul` and thus have the same problem.

So far I did not found a way to create a coverage JSON file from LCOV information. There would be packages to merge LCOV files.

**Comment by erikbarke** [comment]
Hey @nros, `karma-typescript` currently relies on [karma-coverage](https://github.com/karma-runner/karma-coverage) for coverage instrumentation but that project doesn't seem to be actively maintained anymore; an issue regarding upgrading to the maintained version of Istanbul, https://github.com/karma-runner/karma-coverage/issues/245, was filed over a year ago 😕

I guess this means I should leave `karma-coverage` behind and look into implementing instrumentation with the newer versions of the Istanbul libs.

**Comment by nros** [comment]
@erikbarke  Thanks so much! I am impressed about your fast move!

**Comment by erikbarke** [comment]
I still haven't started on actually solving your problem, I only updated the coverage tool chain for the plugins to use `nyc` 😕

**Comment by erikbarke** [comment]
@mitchhentges, would you like to take a stab at upgrading `istanbul` to `nyc`?

**Comment by mitchhentges** [comment]
Can do, I'll take a peek right now

**Comment by christophercr** [comment]
Hi @mitchhentges, do you have any news about this?

**Comment by mitchhentges** [comment]
Err, "right now" was a bit of a stretch haha.
I was depending on `karma-typescript` on a work project, but I've since been moved to a different project that doesn't use this package.

I'll unassign myself from my issues. Thanks for the ping, totally forgot about this :laughing:

**Comment by erikbarke** [comment]
Closing in favor #300.
