### ISSUE TITLE
Can't find dependencies

### ISSUE THREAD

**Issue by samueldweber** [monounity/karma-typescript#160]
When trying to run tests on .ts files, I get an error saying a depency was not found, and when I change the configs to run on .js files it says it cant find require, the js file is generated by tsc
[output_js_spec.txt](https://github.com/monounity/karma-typescript/files/1228962/output_js_spec.txt)
[output_ts_spec.txt](https://github.com/monounity/karma-typescript/files/1228963/output_ts_spec.txt)
if you need anything that may be useful to find a reason/fix, just say it and I will try to get it

**Comment by erikbarke** [comment]
Hey @samueldweber, do you have a repo I could take a look at?

**Comment by samueldweber** [comment]
Sorry, I cant do that private project, what I could give you is a print with the folders layout, I know that the dependencies exist, because I can import them into other components

**Comment by erikbarke** [comment]
The missing file, `caesarweb/src/views/init/onboarding/onboarding.component`, isn't included in any preprocessor pattern:

```js
"preprocessors": {
    "/home/samuelweber/VisualStudioCodeProjects/caesarweb/config/**/*.ts": [
        "karma-typescript",
    ],
    "/home/samuelweber/VisualStudioCodeProjects/caesarweb/tests/karma/*.ts": [
        "karma-typescript",
        "sourcemap",
    ]
},
```
