### ISSUE TITLE
Error when noParse module is set

### ISSUE THREAD

**Issue by roddolf** [monounity/karma-typescript#166]
I'm getting the error `TypeError: Cannot read property 'length' of undefined` when I set a module in the `noParse` property.

This is thrown by the `acron` module and it can be resolved changing the line:
https://github.com/monounity/karma-typescript/blob/4cb83cc8c3306ebd2bb532e0b8245f2bc603d499/src/bundler/resolve/source-reader.ts#L75

From `body: undefined` to `body: []`.

**Comment by erikbarke** [comment]
Hey @roddolf, thanks for reporting! Do you have a stack trace I could take look at? I'm worried this might break, for instance, the [es6 transform](https://github.com/monounity/karma-typescript-es6-transform), so I just want be sure before changing this.

There's a `noParse` [in the integrations tests](https://github.com/monounity/karma-typescript/blob/master/tests/integration-latest/karma.conf.js#L41) that doesn't break and I would like to add another test that documents the error you get, so any info on how to reproduce this error is welcome!

**Comment by roddolf** [comment]
This is my config: 
```
karmaTypescriptConfig: {
    tsconfig: "./tsconfig.json",
    bundlerOptions: {
        entrypoints: /\.spec\.ts$/,
        noParse: [ "jsonld" ],
    },
    compilerOptions: {
        sourceMap: true,
    },
}
```

And this is stack trace of the error:
```
ERROR [karma]: TypeError: Cannot read property 'length' of undefined
    at Object.base.Program.base.BlockStatement (/My-Project/node_modules/acorn/dist/walk.js:185:32)
    at c (/My-Project/node_modules/acorn/dist/walk.js:60:36)
    at Object.recursive (/My-Project/node_modules/acorn/dist/walk.js:61:5)
    at DependencyWalker.collectJavascriptDependencies (/My-Project/node_modules/karma-typescript/dist/bundler/dependency-walker.js:72:19)
    at Resolver.resolveDependencies (/My-Project/node_modules/karma-typescript/dist/bundler/resolve/resolver.js:156:35)
    at /My-Project/node_modules/karma-typescript/dist/bundler/resolve/resolver.js:55:27
    at /My-Project/node_modules/karma-typescript/dist/bundler/resolve/source-reader.js:20:17
    at /My-Project/node_modules/karma-typescript/dist/bundler/transformer.js:54:17
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by erikbarke** [comment]
I've added an extra check in the dependency walker now, does it work if you install the latest from the dev branch, `npm i github:monounity/karma-typescript#next`?

**Comment by roddolf** [comment]
Yes, it works correctly with the latest version.
