### ISSUE TITLE
error TS2693: 'Promise' only refers to a type, but is being used as a value here.

### ISSUE THREAD

**Issue by nicknett** [monounity/karma-typescript#169]
When running karma-typescript I get the error message: `error TS2693: 'Promise' only refers to a type, but is being used as a value here.`

This can be reproduced by inserting the line: 
`new Promise((resolve: any, reject: any) => setTimeout(resolve, 1));`
into line 8 on `hello.component.ts` in `/examples/typescript-latest/`

Can anyone offer an guidance please?
Nick.

**Comment by nicknett** [comment]
Don't worry, fixed this by:
1. in `tsconfig.json` -> `"target": "ES2015"`
2. in `karma.conf.js` -> `karmaTypescriptConfig: { tsconfig: "./tsconfig.json" },`
Nick.

**Comment by erikbarke** [comment]
Hey @nicknett, try adding `es2015` to the lib array in the compiler options of tsconfig.json:

```js
{
    "compileOnSave": false,
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "outDir": "tmp",
        "target": "ES5",
        "sourceMap": true,
        "types" : [
            "jasmine"
        ],
        "lib": [
            "es5",
            "es2015",
            "dom"
        ]
    },
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by erikbarke** [comment]
Haha, you were like 15 seconds faster than me 😄

**Comment by nicknett** [comment]
Yes thanks, step 2 was important in my config, only fixed it thanks to your great docs and examples! Cheers,
Nick
