### ISSUE TITLE
feat: load the files in order of dependency when using Triple-slash reference

### ISSUE THREAD

**Issue by mbarakaja** [monounity/karma-typescript#17]
I have tried the branch 2.1, in order to avoid module loaders, like SystemJS. Its work pretty well, all files are compiled and loaded in the browser without any wrap code.

Now my issues is that karma loads the files apparently in alphabetical order. This causes that some files, that are dependent on other files are loaded first causing errors in run time.

Suppose we have **`index.ts`** and **`module.ts`** files, then `index.ts` refers to `module.ts` and uses some code from it.

**`module.ts`**

``` js
class Model {

}
```

**`index.ts`**

``` js
/// <reference path="./module.ts" />
let class = new Model();
```

Karma will load index.js (the compiled version of index.js) first, causing the line `let class = new Model();` to thrown an error. Because the class Module isn't defined yet.

So, it is possible to resolve and load the files in order of dependency. This is something that TypeScript do when `outFile` compiler option is used.

**Comment by monounity** [comment]
@mbarakaja: would specifying the files in order in karma.conf.js instead of using wildcards work for you?

```javascript
files: [
    "src/module.ts",
    "src/index.ts",
    "src/foo.ts",
    "src/bar.ts"
]
```

**Comment by Hobart2967** [comment]
+1, need this too! No, we've got a massive amount of files and doing the list by hand is not possible.

**Comment by erikbarke** [comment]
@Hobart2967, maybe `karmaTypescriptConfig.bundlerOptions.entrypoints` could solve this problem?
