### ISSUE TITLE
Is it possible to use dynamic imports?

### ISSUE THREAD

**Issue by ldrick** [monounity/karma-typescript#171]
Hi, I'd like to use dynamic imports with TypeScript instead of require.ensure from webpack.
So basicly I have a module exporting an async method within a main.ts

```typescript
import * as Something from "./Something";

export default {
    getSomething: async () => {
        return (await import(/* webpackChunkName: "Something" */ "./Something")) as typeof Something;
    },
}
```

And I tested, it's not the async or await keywords, which lead to the error, its the dynamic import.
Does someone know, how to solve this, I tried already adding these two:

https://github.com/airbnb/babel-plugin-dynamic-import-node
https://github.com/monounity/karma-typescript-es6-transform

like so
```javascript
karmaTypescriptConfig: {
    bundlerOptions: {
        entrypoints: /\.spec\.ts$/,
        transforms: [
            require("karma-typescript-es6-transform")({
                presets: ["es2016"],
                plugins: ["dynamic-import-node"],
            }),
        ],
    },
}
```

The error I get is:
`01 09 2017 15:12:07.413:INFO [bundler.karma-typescript]: Bundled imports for 224 file(s) in 343 ms.
Failed to parse file: .......main.ts
01 09 2017 15:12:07.683:ERROR [preprocessor.coverage]: Line 107: Unexpected reserved word at
  .......main.ts`

Thanks for every idea.

**Comment by erikbarke** [comment]
Hey @ldrick, the Typescript compiler downgrades the ES2017 keywords `async` and `await` to ES5  as expected, but it leaves the `import` keyword intact which makes other third party modules crash and burn... I got this to work by replacing `import` with `require`, would that solve your issue?

**Comment by ldrick** [comment]
Hi @erikbarke that's, what I expected. So my first intention was to use the babel transform, like in my previous post, but it seems not working, the error stays exactly the same. Can you please share your idea, how to replace `import` with `require`? Thank you

**Comment by erikbarke** [comment]
I did something like this:

```js
import * as Something from "./Something";

public async getSomething() {
    return (await require("./Something")) as typeof Something;
}
```

**Comment by ldrick** [comment]
@erikbarke that's nearly my starting point.

> I'd like to use dynamic imports with TypeScript instead of require.ensure from webpack.

Currently I am using require.ensure, but its not possible to provide stable Typecheckings with that way.
With dynamic imports becoming more and more common, due to TypeScript supports it native and they are stage 3 [Proposal Dynamic Import](https://github.com/tc39/proposal-dynamic-import) may this could be an Feature-Request for this project?

**Comment by erikbarke** [comment]
The `import` statement not getting transpiled is a [Typescript bug](https://github.com/Microsoft/TypeScript/issues/17371), does it work if you use the latest version of Typescript?
