### ISSUE TITLE
feat: please support the "extends" setting in tsconfig.json (configuration inheritance)

### ISSUE THREAD

**Issue by antonmata** [monounity/karma-typescript#173]
It would be nice if the `extends` property of `tsconfig.json` was supported.

I found out the hard way that it wasn't supported. I was getting an `Uppercase/lowercase mismatch` error. I found out that it was because my `tsconfig.json` was using the `extends` property to inherit from a common config file where the `baseUrl` was defined.

**Comment by erikbarke** [comment]
Hey @antonmata, I modified the [typescript-latest example project](url) like this:

Karma config:

```js
module.exports = function(config) {
    config.set({

        frameworks: ["jasmine", "karma-typescript"],

        files: [
            { pattern: "src/**/*.ts" }
        ],

        preprocessors: {
            "**/*.ts": ["karma-typescript"]
        },

        karmaTypescriptConfig: {
            tsconfig: "./tsconfig.json"
        },

        reporters: ["dots", "karma-typescript"],

        browsers: ["Chrome"]
    });
};
```

tsconfig.json:

```js
{
    "extends": "./base-tsconfig.json",
    "compileOnSave": false,
    "exclude": [
        "node_modules"
    ]
}
```

base-tsconfig.json (this is a new file I created for this test):
```js
{
    "compilerOptions": {
        "module": "commonjs",
        "noImplicitAny": true,
        "outDir": "tmp",
        "target": "ES5",
        "sourceMap": true,
        "types" : [
            "jasmine"
        ]
    }
}
 ```

Does this describe your scenario? It works when I run `npm test`, I can change settings in `base-tsconfig.json` to change the compiler behavior.

Are you on an OS with a case sensitive file system?

**Comment by antonmata** [comment]
The key item for me was the `baseUrl`. To best describe my scenario, you need to add the `baseUrl` in `base-tsconfig.json` and also define appropriate `resolve.modules` in webpack:

```js
resolve: {
    extensions: [".tsx", ".ts", ".js", ".json"],
    modules: [
        __dirname,
        "node_modules"
    ]
}
```

I kind of figured out that it could be a path issue because I was getting a `Error: Uppercase/lowercase mismatch` message from an error thrown in `dependency-walker.ts`.

**Comment by antonmata** [comment]
I forgot to mention that I was able to workaround the issue by explicitly defining the `baseUrl` in the "child" `tsconfig.json` that was referenced by karma-typescript, essentially bypassing the inheritance.

**Comment by erikbarke** [comment]
I was able reproduce the error and this is probably a Typescript bug, https://github.com/Microsoft/TypeScript/issues/17617.

The compiler seems to lowercase module names if the `baseUrl` property is set in a tsconfig that is inherited, just like what you're describing. 

This triggers the case sensitivity validators in both karma-typescript and the Typescript compiler, if you're using the `forceConsistentCasingInFileNames` compiler option.

**Comment by antonmata** [comment]
Ah ok, that explains a lot. I was so confused that the error message was showing both paths, but they look alike except for just the casing. I really did not know what or how to fix that, hence just went for the workaround. Thanks for looking into this.
