### ISSUE TITLE
Static text file containing javascript is evaluated in require()

### ISSUE THREAD

**Issue by mitchhentges** [monounity/karma-typescript#174]
Thanks for making this pre-processor for Karma, it's pretty :100:

I'm currently using `2.1.7`, and I have a test that mocks a network request for a javascript file. This works well: I require the file -  `require('mockPage.txt')` - then I use the resulting string to represent the static file served over HTTP.

However, in version `3.0.1` of `karma-typescript`, commit [`1c8f8ed1fd0f7e15ca3995147d880e3fc0507534`](https://github.com/monounity/karma-typescript/commit/1c8f8ed1fd0f7e15ca3995147d880e3fc0507534) adds functionality that will attempt to evaluate `require()'d` files as javascript. This means that my static files are now evaluated, and the resulting content is not what the test expects.

For example, `mockPage.txt` contains:
```
(function() {
  return {
    foo: 'baz',
    bork: true
  }
})();
```

So where I expect: `(function(){return{foo:'baz',bork:true}})();`, I'm instead getting: `{foo:'baz',bork:true}`

-----

I'm _just barely_ beginning to understand the scope of this project, and I could be missing something painfully obvious, but I don't understand the rationale for attempting to parse `.txt` files as javascript/json. There's already functionality in place to handle as Javascript (and friends) if the file ends in `.js`/`.jsx`/etc.

Perhaps it would be the simplest and most clear to library users if `karma-typescript` just determined file contents based on extension?

If the feature _is_ definitely valuable, then it would be cool if we could look into an option to disable it so I can make my tests work nicely with a newer `karma-typescript` 😄

**Comment by erikbarke** [comment]
Hey @mitchhentges, the evaluation didn't seem necessary anymore and all tests pass without it so I have simply removed it! You can try it out by installing from the development branch, `npm i github:monounity/karma-typescript#next` ☺️

**Comment by mitchhentges** [comment]
Awesome! I'll test it in an hour or two :)

**Comment by mitchhentges** [comment]
Hey, by the way, should this be a breaking change, and the next version be 3.1.0? It will cause a user-visible change in functionality, so as 3.0.6 it might break some builds :)

**Comment by mitchhentges** [comment]
Gave it a shot earlier today, and removing the unnecessary evaluation definitely solved this issue, thanks! Looking forward to the release 🚤

**Comment by erikbarke** [comment]
Great!

Regarding the breaking change: it's not a documented feature, the commit message doesn't mention any issue and it's not even mentioned in the release notes... This "feature" is most likely something I thought was Really Awesome&trade; back when I was creating the Transforms API but it doesn't really make sense, as you pointed out.

I'm thinking that new behavior should be the default from now on, and if someone has a valid use case for evaluating the contents of a `.txt` file as javascript, there are two options: either a new bundler setting to override the behavior, ie `bundlerOptions.evaluateAsJavascript: [".js", ".txt", ...]` or maybe a custom transform.

**Comment by mitchhentges** [comment]
Sweet, thanks! Personally, for the sake of deferring work, I'd personally wait to implement any functionality to support evaluate-txt-as-JavaScript until someone actually has that use case.

Either way, thanks!
