### ISSUE TITLE
Support browser package alias

### ISSUE THREAD

**Issue by roddolf** [monounity/karma-typescript#175]
Im having problems with cross platform libraries, where they require specific Node.js modules.
But alias are declared in the `browser` property of the `package.json` of these libraries.

Should't the bundler use this alias?

**Comment by erikbarke** [comment]
Hey @roddolf, the karma-typescript bundler uses [browser-resolve](https://github.com/defunctzombie/node-browser-resolve) which supports the `browser` field in `package.json`, so this should work out of the box. Which specific packages aren't working for you, how can I reproduce this error?

**Comment by roddolf** [comment]
I'm using `jsonld` and `sockjs-client`.
For example, `jsonld` lists:
```json
{
  "browser": {
    "crypto": "./browser/ignore.js",
    "http": "./browser/ignore.js",
    "jsonld-request": "./browser/ignore.js",
    "pkginfo": "./browser/ignore.js",
    "request": "./browser/ignore.js",
    "url": "./browser/ignore.js",
    "util": "./browser/ignore.js",
    "xmldom": "./browser/ignore.js"
  },
}
```

But the compiling throws `Error: Cannot find module 'jsonld-request' from '.'`

**Comment by erikbarke** [comment]
I've committed a fix now, does it work for you if you install from the development branch, `npm i github:monounity/karma-typescript#next`?

**Comment by MasterCassim** [comment]
This fix produces an issue for my build now. When bundling, I always get the following fatal error:

Fatal error: Unable to resolve module [tslib] from [ <FOLDER>/_shared/interactionContainer.js ] where my actual project is located under <FOLDER>/project/ and tslib cannot be found with this changed behavior.

**Comment by erikbarke** [comment]
@MasterCassim, do you have a repo I could take a look at?

**Comment by MasterCassim** [comment]
Unfortunately, the source code is not public. I may be able to provide a reduced version.

**Comment by MasterCassim** [comment]
@erikbarke Created a small repo where the issue can be seen. Executing "npm install && grunt karma" only works when explicitly setting karma-typescript to v3.0.5

-> https://github.com/MasterCassim/karma-typescript-175

**Comment by erikbarke** [comment]
I've added an extra resolve without filename, does it work for you if you install from the development branch, `npm i github:monounity/karma-typescript#next`?

**Comment by MasterCassim** [comment]
Works correctly with github:monounity/karma-typescript#next

**Comment by erikbarke** [comment]
Great, I'm releasing this fix with a few other hotfixes this week 🚀
