### ISSUE TITLE
Unable to resolve npm linked module

### ISSUE THREAD

**Issue by WilliamBowen** [monounity/karma-typescript#178]
I'm not sure if this is a karma or a karma-typescript problem. I'm trying to write tests for a project that I have been assigned to.  The project has code that imports modules from a repo that is npm linked to the project. When the project was built it didn't have a test environment, so I was asked to add one. I've managed to get tests running as long as they don't import anything from the npm linked module, but as soon as I add a file to the karma config that has an import from the the other repo, I get the following error.
```
[Error: Unable to resolve module [@ontsys/cloud-lib-angular/routing] from [/home/vagrant/.gvm/pkgsets/go1.8.3/global/src/go.ontsys.com/cloud-ps-ui/src/app/home/home.component.js]
```
I'm pretty sure I'm missing something from my karma.conf.js file. I would really appreciate some insight on this if you could provide it. 
tsconfig.json
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "lib": ["es2015", "dom"],
    "baseUrl": "./node_modules",
    "paths": {
      "@ontsys/cloud-lib-angular/*": [
        "@ontsys/cloud-lib-angular/dist/*"
      ]
    }
  },
  "compileOnSave": false
}
```
karma.conf.js
```
module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine', 'karma-typescript'],

    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-typescript')
    ],

    files: [
        { pattern: "base.spec.ts" },
        { pattern: "src/app/**/*.ts" }
    ],

    preprocessors: {
        "**/*.ts": ["karma-typescript"]
    },

    karmaTypescriptConfig: {
        bundlerOptions: {
            entrypoints: /\.spec\.ts$/,
            transforms: [
                require("karma-typescript-angular2-transform")
            ]
        },
        tsconfig: 'tsconfig.json'
    },

    reporters: ['progress', 'kjhtml', 'karma-typescript'],

    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
    singleRun: false
  });
};
```

**Comment by erikbarke** [comment]
Do you a repo I could take a look at?

**Comment by WilliamBowen** [comment]
Repo is located at https://github.com/WilliamBowen/example. It is a stripped down version of the project I am working on, since it is not open source, but it creates the same issue. Thanks for taking a look.

**Comment by erikbarke** [comment]
Ok, I've looked at your example and it seems something's up with the `npm link`, I can't even get a simple `echo "require('@wb/project1')" | node` to resolve the linked package in the root of project2 (for example `echo "require('@angular/core')" | node` doesn't crash).

The `@wb/project1` folder structure has been created in node_modules, but the package.json property `main` points to index.js which doesn't exist, so I guess that's why all attempts to resolve stuff fails?

**Comment by erikbarke** [comment]
Try using an alias in the bundler options + the latest version of karma-typescript (3.0.6):

```js
    karmaTypescriptConfig: {
        compilerOptions: {
          noEmit: false,
          noEmitHelpers: false
        },
        bundlerOptions: {
            entrypoints: /\.spec\.ts$/,
            resolve: {
                alias: {
                    "@wb/project1/components": "node_modules/@wb/project1/dist/components/index.js"
                }
            },
            transforms: [
                require("karma-typescript-angular2-transform"),
                require("karma-typescript-es6-transform")()
            ]
        },
        tsconfig: './tsconfig.json'
    },
```

Using this config worked for me ☺️

**Comment by WilliamBowen** [comment]
Thank you, that seems to have taken care of the problem.  I had tried the using an alias before, but it turns out I was doing it wrong. I am now getting a different error. "Uncaught Error: Cannot resolve all parameters for 'BrowserPlatformLocation'(undefined @Inject)". This is probably unrelated though.

**Comment by erikbarke** [comment]
Great ☺️ The new error looks like an angular config error, so I'm closing this issue.
