### ISSUE TITLE
Integrating `proxywire`

### ISSUE THREAD

**Issue by gempain** [monounity/karma-typescript#179]
Hello,

I am trying to use `proxywire` or `rewire` alongside this lib, with no success so far. 

With `proxywire`, I get

```
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  TypeError: undefined is not a constructor (evaluating 'require.resolve(__filename)')
  at .../AppData/Local/Temp/karma-typescript-bundle-107443nmM9Ar4FH82.js:7140
```
when I import it.

With `rewire`, I get

```
Cannot find module 'coffee-script' from '.'
```

which is caused by `karma-typescript` trying to resolve `rewire` dependencies for bundling.

I am pretty sure the problem comes from the fact that those libraries are not build to be bundled. The `rewire` documentation even [mentions it as a limitation](https://github.com/jhnns/rewire#limitations).

All I am trying to do is test internal / non exported function, and the [only solution seems to be using the `rewire` approach](https://stackoverflow.com/questions/14874208/how-to-access-and-test-an-internal-non-exports-function-in-a-node-js-module). For example, take the following code:

```
export function a() {
  b();
}

function b() {

}
```

there is no way to mock `b` other than using `rewire`.

I tried using the options `noParse`, `exclude` or `ignore` of configuration property `bundlerOption`, obviously with no luck since those properties seem unrelated anyway. I think there should be a bundler option to specify modules that should not be bundled but should still be packaged as a side `node_modules` bundle.

Note that I also tried using the `karma-typescript-mock` package, with no luck as well. I could not get the internal reference to 

Thanks a lot if anyone can help.

**Comment by erikbarke** [comment]
Do you a repo I could take a look at?

**Comment by gempain** [comment]
Not right now, but I will try to setup one ASAP.
