### ISSUE TITLE
question: integrate with Browserify

### ISSUE THREAD

**Issue by camolin3** [monounity/karma-typescript#18]
Hello,
I am trying to make my tests work with a Browserify project using the branch 2.1, but I am not able to import `angular-mocks`.
This is the url of the project: 
https://github.com/camolin3/kunder-siberia-frontend

I hope you can help me. Have a nice weekend!

**Comment by monounity** [comment]
Hey @camolin3, your project runs just fine with a few changes:
* No angular-mocks imports (if it's imported, `karma-typescript` will load it automatically which means it will get loaded twice in the browser)
* Simpler file pattern in karma.conf.js
* angular-mocks in types in tsconfig.json

```diff
git diff

diff --git a/app/modules/home/home.controller.spec.ts b/app/modules/home/home.controller.spec.ts
index 9a62f91..a023cff 100644
--- a/app/modules/home/home.controller.spec.ts
+++ b/app/modules/home/home.controller.spec.ts
@@ -1,8 +1,4 @@
-import 'angular';
-import 'angular-mocks';
-
 import * as angular from 'angular';
-import * as mocks from 'angular-mocks';
 import { HomeController } from './home.controller';
 
 describe('HomeController', () => {
diff --git a/test/karma.conf.js b/test/karma.conf.js
index 5b8d39b..3f502f1 100644
--- a/test/karma.conf.js
+++ b/test/karma.conf.js
@@ -15,9 +15,7 @@ module.exports = function(config) {
       { pattern: 'node_modules/angular/angular.js' },
       { pattern: 'node_modules/angular-mocks/angular-mocks.js' },
       { pattern: 'node_modules/angular-ui-router/release/angular-ui-router.js' },
-      { pattern: 'app/**/*.ts', exclude: 'app/**/*.spec.ts' },
-      { pattern: 'app/**/*.spec.ts' },
-      { pattern: 'app/**/*.html' },
+      { pattern: 'app/**/*.ts' }
     ],
 
     // list of files to exclude
diff --git a/tsconfig.json b/tsconfig.json
index 98153c4..27356f0 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -10,7 +10,8 @@
     "typeRoots": [ "node_modules/@types/" ],
     "types": [
       "jasmine",
-      "angular"
+      "angular",
+      "angular-mocks"
     ]
   },
   "exclude": [
(END)
```

Cheers!

**Comment by camolin3** [comment]
Awesome, the tests are running! :smile:

For some reason after making those changes, Sublime (with TypeScript plugin) stills show me that `angular.mock` doesn't exists,. The compiler finds `inject` so I think is actually loading `@types/angular-mocks`.
![angular mock](https://cloud.githubusercontent.com/assets/1903086/19928328/c43332ca-a0dc-11e6-9b6b-ba30337a1b75.png)

This also happens in the log of `gulp test`.
![gulp_test](https://cloud.githubusercontent.com/assets/1903086/19929044/2d732116-a0e0-11e6-8605-68b87c49f26b.png)

Any idea of how to fix this?

**Comment by camolin3** [comment]
I think the problem is related to `angular-mocks` is trying to load its own version of angular, instead of the installed with the project. It is loading those two files:

 - `node_modules/@types/angular/index.d.ts`
 - ` node_modules/@types/angular-mocks/node_modules/@types/angular/index.d.ts`

**Comment by erikbarke** [comment]
What happens if you remove the line
import * as angular from 'angular'?
