### ISSUE TITLE
apply transform API on node_modules too

### ISSUE THREAD

**Issue by nros** [monounity/karma-typescript#186]
We are using karma + TypeScript + mocha + chai with `karma-typescript` for unit testing. At the moment [PhantomJS](http://phantomjs.org/) seems the best option for headless testing on CI machines.

However, PhantomJS does not support ES2015 (ES6) and seems to never will. Hence it fails on JavaScript code making use of keywords `let` or `const`. NPM modules utilizing ES 6 features seem to increase, as nodeJS supports and encourages ES6. Therefore PhantomJS fails if any of such modules is used (eg.: [`chai-as-promised`](https://www.npmjs.com/package/chai-as-promised))

Usually the transform API can be used to apply [`karma-typescript-es6-transform`](https://www.npmjs.com/package/karma-typescript-es6-transform). Unfortunately the transform API is not applied to resolved modules (eg: all those NPMs from `node_modules`). Hence there is no possibility to apply ES6 translation to those.

Would it be possible to add this feature?

**Comment by erikbarke** [comment]
This should work for both project files and files bundled from node_modules, what does your config look like?

I modified the [typescript-latest example project](https://github.com/monounity/karma-typescript/tree/master/examples/typescript-latest) like this:

```bash
npm i chai-as-promised karma-typescript-es6-transform
```
karma.conf.js:
```js
module.exports = function(config) {
    config.set({

        frameworks: ["jasmine", "karma-typescript"],

        files: [
            { pattern: "src/**/*.ts" }
        ],

        preprocessors: {
            "**/*.ts": ["karma-typescript"]
        },

        reporters: ["dots", "karma-typescript"],

        karmaTypescriptConfig: {
            bundlerOptions: {
                transforms: [
                    require("karma-typescript-es6-transform")()
                ]
            }
        },

        browsers: ["Chrome"]
    });
};
```

hello.component.js:
```js
import { HelloService } from "./hello-service.interface";

export class HelloComponent {

    constructor(private helloService: HelloService) {}

    public sayHello(): string {

        console.log(require("chai-as-promised"));

        return this.helloService.sayHello();
    }
}
```

This works if I execute `npm run dev:ci:phantomjs` (PhantomJS barfs if I remove the es6 transform).
