### ISSUE TITLE
Any suggestions on how to load jQuery before AngularJS for tests?

### ISSUE THREAD

**Issue by nathanbedford** [monounity/karma-typescript#187]
I have a Webpack/AngularJS (1.6)/TypeScript project.  I have Webpack configured to load jQuery before Angular, so I can use full jQuery instead of jQuery Lite in my directives.

Trouble is, when I  run my karma tests with karma-typescript now, it looks like jQuery isn't loading before Angular, so I can't do things like "element.click()' in my directives.  

I know removing jQuery as a dependency is an option, I feel like there has to be another way.  I've tried importing jQuery manually into my tests (before my Angular import) without luck.  I must be missing something.

Any ideas?

**Comment by erikbarke** [comment]
Off the top of my head, have you tried adding jQuery before all other files in the `files` section of the Karma config?
