### ISSUE TITLE
Provide relative path to instrumenter exclude regex 

### ISSUE THREAD

**Issue by gempain** [monounity/karma-typescript#188]
Hello,

`Coverage.prototype.isExcluded = function (regex, path)` receives the full path of files. This may be inapropriate in certain situations. For example, suppose I want to ignore the `test/` folder from my project. Currently, the only option is to set 
```
karmaTypescriptConfig: {
	coverageOptions: {
		exclude: [
			/test(\/|\\)/,
		]
	}
}
```
in my `karma.conf.js`.

This works fine unless a parent folder of the project's root directory is named `test`. If that happens, the regex will match all files and the coverage report will be empty. I just had the issue today where one of the parent project directory name contained the word "test".

In `coverage.js:31`, instead of passing `file.originalPath` to `isExcluded`, a path relative to the project's root directory would probably be more suitable.

What do you think ?

All the best;

**Comment by erikbarke** [comment]
This sounds like a good idea! Would you like to implement this in a PR?

**Comment by erikbarke** [comment]
Tracked in #193.
