### ISSUE TITLE
Compile source maps for `karma-typescript`

### ISSUE THREAD

**Issue by mitchhentges** [monounity/karma-typescript#189]
Would there be any harm in enabling sourcemaps for this package? It would make it easier for contributors to start on and debug the project, and dependent packages could step through `karma-typescript` if they needed to.

I can whip up the one-line PR, just wanted to start a discussion :)

**Comment by erikbarke** [comment]
Great idea! PR please ☺️

**Comment by erikbarke** [comment]
Fixed in #191.
