### ISSUE TITLE
Order files by reference tags set in *.ts

### ISSUE THREAD

**Issue by Hobart2967** [monounity/karma-typescript#199]
In order to have "outFile" supported somehow without using commonjs (namespacing instead of using modules), it is required to sort the *.ts files before running karma with karma-typescript.

Example

**fileA.ts**
```
/// <reference path="y/fileB.ts" />
namespace x { 
   import B = x.y.B;
   export class B {
       
   }
}
```

**fileB.ts**
```
namespace x.y {
   export class B {
       
   }
}
```

**=> Results in an error when running the test:**
Cannot read property 'B' of undefined.

Reason: Reference tags are ignored, so karma-typescript includes the *.js outputs in a wrong order. (fileA before fileB). To make fileB included before fileA, we now set up the grunt task to look up the references before it actually runs the tasks.

      function orderTsFiles(pattern) {
        const files = grunt.file.expand({
            cwd: pattern.projectDirectory
        }, pattern.src);

        const referenceDict = {};

        const orderedFiles = [];
        files.forEach(file => getPosition(orderedFiles, file, referenceDict, pattern.projectDirectory));
        grunt.log.debug(orderedFiles.join('\r\n'));
        return orderedFiles
    }

    function getPosition(orderedFiles, newFile, referenceDict, projectDirectory) {
        const path = require('path');

        const source = grunt.file.read(path.join(projectDirectory, newFile));

        var regex = /\S*\/\/\/\s*\<reference \s*path="(.*)"\s*\/>/g;

        let match;

        while ((match = regex.exec(source)) !== null) {

            // This is necessary to avoid infinite loops with zero-width matches
            if (match.index === regex.lastIndex) {
                regex.lastIndex++;
            }

            // The result can be accessed through the `m`-variable.
            match.forEach((match, groupIndex) => {
                if (groupIndex !== 1) {
                    return;
                }
                const referenceFile = path.join(path.dirname(newFile), match);
                if (referenceFile.lastIndexOf('.d.ts') === referenceFile.length - '.d.ts'.length) {
                    return;
                }
                if (orderedFiles.indexOf(convertSlashes(referenceFile)) === -1) {
                    getPosition(orderedFiles, path.join(path.dirname(newFile), match), referenceDict, projectDirectory);
                }
            });
        }

        if (orderedFiles.indexOf(convertSlashes(newFile)) === -1) {
            orderedFiles.push(convertSlashes(newFile));
        }
    }

    function convertSlashes(str) {
        return str.replace(/\\/g, '/');
    }

We first read our original tsconfig.json and order included TS files by reference tags:

            orderTsFiles({
                projectDirectory: path.join(process.cwd(), projectConfig.workspace, 'node_modules', x),
                src: tsConfig.include
            });

Result: 
```
  [
     "fileB.ts",
     "fileA.ts"
  ]
```

It would be nice if this would be somehow implemented in karma-typescript (maybe with a switch in options? Or when "outFile" is set to a truthy value?

**Comment by mitchhentges** [comment]
Interesting, I think I understand.
If `karma-typescript` isn't honouring ordering for triple-slash directives, isn't that a bug? IIRC, loading according to the order the directives are written in the file is normal behaviour, not something that should be enabled/disabled with a flag, right?

Also, just so I'm on the same page: if this was working properly, would you still be using `outFile`? My understanding of `karma-typescript` is that it compiles in-memory, and doesn't (normally) put its output files anywhere. Why is `outFile` being used in your situation? Just trying to get a better grasp of the situation :)

**Comment by erikbarke** [comment]
@mitchhentges, I agree that the loading order should be correct by default, no flags should be needed.

The cumbersome workaround for this could be specifying the files in the desired order in the Karma files section as suggested in #17, but that really isn't a feasible solution if the project has a large amount of files and you just want to use wildcards for matching for the files.

The bundler already [sorts the files](https://github.com/monounity/karma-typescript/blob/master/src/bundler/bundler.ts#L196) in the same order they were added in the Karma files section to avoid these kinds of race conditions where file A gets loaded before its dependency B (#77), maybe we could make that sorting function a bit smarter.

**Comment by mitchhentges** [comment]
@erikbarke, I'm fairly committed to this project, can you add me (and probably @gempain) to the repository?
If that's all OK, then it would be :100: if you could set me as the assignee for this ticketerino

**Comment by erikbarke** [comment]
@mitchhentges, I actually began digging a little deeper into this issue last night and I'm not sure there's anything we can do here 😞

The bundler counts the number of `import`/`require` statements in the project and if there are more than 0 dependencies each .ts file will be wrapped in a CommonJS wrapper. If there are 0 dependencies the code won't be bundled, which is useful if you're using namespaces with global variables.

For example, this Typescript class:
```js
/// <reference path="./fileB.ts" />
namespace x {
    import B = x.y.B;
    export class A {
    }
}
```

gets compiled to:

```js
var x;
(function (x) {
    var A = /** @class */ (function () {
        function A() {
        }
        return A;
    }());
    x.A = A;
})(x || (x = {}));
```
The "namespace" `x` is now a global variable which would be inaccessible inside a CommonJS wrapper. This means that when karma-typescript detects these kinds of projects it doesn't bundle any code *at all*, it only compiles the Typescript code and hands it over to Karma which serves each file to the browser, there's nothing to sort 😕

@Hobart2967, do you have any repo we could take a look at? Are you using karma-typescript in another way than what I'm describing here?

**Comment by Hobart2967** [comment]
Unfortunately only within a private company repository at this time. We are not using bundling, we use the "outfile" switch when compiling the JS for production environment. And we would like to behave the same for tests, which is not possible for karma-typescript, unfortunately. That means at this time we ordering the files by /// <reference matches.

The function I posted solves the problem, but still we would like to see this out of the box. BTW, we use AMD as module system.

**Comment by erikbarke** [comment]
I'm afraid I still don't understand what's happening here... You sort the files by triple slash references in your `grunt` workflow but what happens after that? Are you running Karma programmatically using `grunt-karma`, feeding Karma the list of sorted files directly from `grunt`?
