### ISSUE TITLE
Istanbul cannot find file

### ISSUE THREAD

**Issue by Duskfall** [monounity/karma-typescript#2]
Hello i get an error when i clone your repo:
Unable to find entry for [C:\Users\user\Downloads\karma-typescript\example-project\src\hello-service.interface.ts]]

**Comment by g00fy-** [comment]
this is solved by #1

**Comment by monounity** [comment]
@Duskfall The PR by g00fy- is merged now, could you check if it works for you now?

**Comment by Duskfall** [comment]
Yes i am already using the fork and is running fine thanks!
