### ISSUE TITLE
Missing styles, which are located in same directory to source code

### ISSUE THREAD

**Issue by l0nley** [monounity/karma-typescript#20]
I am not glob guru, but it looks like you are missing all styles, located in the same directory to source code.
https://github.com/monounity/karma-typescript/blob/2.1/lib/karma-wide-load/node-modules-loader.js#L70

As fast fix, 
You need to add:
````
glob.sync(directory+'/*.+(css|less|sass|scss)')
           .forEach(function(some) {
                styleSheetFiles.push(some);
            })
````
after styleSheetFiles initialization.

**Comment by monounity** [comment]
Hey @l0nley, nice work spotting this bug! My really naive first approach only worked for stylesheets in a sub folder, relative paths into parent directories like `import "../../foo/bar/css.css";` would break the test runner, even with your PR. The new approach is using the compiler AST output and check if an import is a "real" module or just a dummy import... As a bonus, the module loading is a bit faster now, without all the file system i/o!

**Comment by l0nley** [comment]
Works with latest  2.1. Thanks!
