### ISSUE TITLE
Improvements to "Contributing" docs

### ISSUE THREAD

**Issue by mitchhentges** [monounity/karma-typescript#200]
> One that runs `npm run build:watch`, which watches for changes and builds the karma-typescript source code.

Mention _where_ `npm run build:watch` should be executed (the root of the repository)

-----

> this project uses `tslint` which can be run on command line

Should be "which can be run on *the* command line"

> It also has an "autoFixOnSave" feature

Maybe throw `autoFixOnSave` in backticks?

-----

> with a unit test or an integration test that breaks without the bug fix.

Perhaps should be "or an integration test that _fails_ without the bug fix". Minor language nit, "breaks" implies that the test itself breaks down and performs incorrectly? IDK 🤷‍♂️ 

-----

Thanks for creating the "contributing" docs! They look great! These are mostly small recommendations, you nailed it the first time <3

**Comment by erikbarke** [comment]
Updated!
