### ISSUE TITLE
Suggestion: do development on `master` branch

### ISSUE THREAD

**Issue by mitchhentges** [monounity/karma-typescript#201]
Does it make more sense to have a `next` branch, or to do development on `master`?
I know that the development experience for new contributors would be simplified if we developed on `master`, because there'd be less branch-management overhead. However, I haven't worked on many projects where `next` is the primary dev branch, so I haven't realized the benefits (yet!)

**Comment by erikbarke** [comment]
It made sense a while back when Typescript were moving fast and every other release made karma-typescript crash and burn 🔥 Also, there was some really wild stuff going on development-wise in karma-typescript at the time which made me switch to doing all the development on feature branches and the hot fixes on the master branch. At first the feature branches had the same name as the upcoming release, but eventually I ended up using just one feature branch, `next`, out of sheer laziness... 

It really doesn't matter as long as there's always a branch that is always in a releasable state, if a bug fix needs to be shipped yesterday. If that deployable branch is the `master` branch or a `current-release` branch doesn't really matter, what matters is if the current development needs benefits from the current branching scheme.

I've been toying with the idea of using [the GitHub Flow](https://guides.github.com/introduction/flow/) where everyone, including me, works on feature branches, creates pull requests which are merged to the master branch when stable and tested. In other words: PR:s, the master branch is always deployable and no `next` branch ☺️

**Comment by mitchhentges** [comment]
My vote is GitHub flow. There's already a great collection of tests in `karma-typescript`, so there can be reasonable confidence that `master` is in a good state, and always ready to be released.

We found that it worked really well for [James Proxy](https://github.com/james-proxy/james/), too, if that anecdata helps ;)

**Comment by erikbarke** [comment]
Then it's settled, the GitHub Flow it is!

Off topic, would you like to take a look at what's needed to resolve issue 199?

**Comment by mitchhentges** [comment]
Perhaps I can take a peek on the weekend :)
My bigger priority is making the new version of `karma-typescript` work nicely with my repository (#177), but I'll work my way around

**Comment by erikbarke** [comment]
Great, 3.0.8 is on npm now 😃
