### ISSUE TITLE
Could not find source map for: <filename>

### ISSUE THREAD

**Issue by maxant** [monounity/karma-typescript#202]
I've added karma-typescript to a very simple app but even though I get a useful coverage report including mapping from JS to TS, karma is throwing errors during coverage transformation.

I'm logging the bug here, because it is this plugin which doing in-memory compilation, meaning that there are indeed no files for `remap-istanbul` to find.

Here is a demo project: https://github.com/maxant/typescript_examples/tree/bug/monounity/karma-typescript/issues/202

Steps to reproduce:

    git clone https://github.com/maxant/typescript_examples.git
    git checkout bug/monounity/karma-typescript/issues/202
    npm install
    npm run test

Tests pass and coverage is recorded including source mapping. For some reason, thre is an error message displayed, which I feel should not be.

**Comment by erikbarke** [comment]
It's the `remap-coverage` that somehow interferes, after removing that your project executed without any error messages!

**Comment by maxant** [comment]
Works perfectly, thanks!
