### ISSUE TITLE
Run without compiling typescript files?

### ISSUE THREAD

**Issue by goktugyil** [monounity/karma-typescript#214]
I'm using Webstorm IDE and all my .ts files are automatically compiled into .js on change. 

I do not need another step of compiling all the files to .js everytime I want to run a single test method. 

I just want to see the coverage on my .ts files.

If possible I would like to skip the compile process of karma-typescript. Is there a way to do this?

**Comment by erikbarke** [comment]
Unfortunately no, `karma-typescript` uses an in-memory cache internally which is shared by the preprocessor/compiler and the coverage reporter, the only way to populate this cache is to run the Typescript files through the preprocessor.

Off the top of my head, would combining `karma-coverage` and `nyc` work for you?

**Comment by goktugyil** [comment]
Thanks for the answer, I'll check that out.
