### ISSUE TITLE
Transforms: is it possible to generate code?

### ISSUE THREAD

**Issue by jods4** [monounity/karma-typescript#217]
I can't seem to get this to work, no matter what I try.
I have a transform that compiles views. It takes a HTML file as input, produces JS as output.

So I have one html template `view.html` (content not relevant).
In Typescript I have some import
```ts
import view from "./view.html";
```
To make it compile fine I declared that `.html` imports produce a specific interface:
```ts
declare module "*.html" {
  import { IView } from "./iview.ts";
  const view: IView;
  export default view;
}
```
All of this works. The html file is even loaded by `karma-typescript` and goes through my loader.

The issue is that the results seems to be treated like a trivial string export.
My transform produces code with `import` and `export` inside, i.e. arbitrarily complex JS/TS code.

Is that doable?

**Comment by erikbarke** [comment]
Could you post you karma config here? Or do you have a repo we could take a look at?

**Comment by jods4** [comment]
@erikbarke I did some digging myself into the karma bundler source code.

So my `view.html` goes through this code:
https://github.com/monounity/karma-typescript/blob/ac17c17c03ad6af813a93a717f2555597eba4f75/src/bundler/resolve/source-reader.ts#L25

If you look at `assertValidNonScriptSource` that is just below, it's clear that the only thing that is supported here is a trivial module that consists of a single `module.exports = "something"`, or is considered as such (`module.exports = ` is automatically added).

My problem is that my transform produces more complex code. Rather something like:
```ts
import X from "./other-module";

// do stuff
export function stuff() { return X }
```

**Comment by erikbarke** [comment]
@jods4, there's definitely room for improvement here...
@gempain, we could try just parsing the text content with `acorn` and if the parser doesn't barf it's considered a script and should be passed to the bundler as is, what do you think?

**Comment by jods4** [comment]
@erikbarke to avoid sniffing, maybe the transform could set a flag on `context` to indicate it returns js? That seems easy enough.

If this information is then used so that `bundleItem.isScript()` returns true, the rest should flow naturally from here: https://github.com/monounity/karma-typescript/blob/02964167f54041df066aec55816bdba5155bf875/src/bundler/resolve/resolver.ts#L201-L217

I currently trick the system into not touching my file by adding a dummy `module.exports = 0` at the top, but `isScript` is still false so dependencies aren't processed nonetheless.

**Comment by erikbarke** [comment]
The context object is shared between the transformers so I think we should put this new flag in the transform callback: 

https://github.com/monounity/karma-typescript/blob/02964167f54041df066aec55816bdba5155bf875/src/api/transforms.ts#L7-L9

The new flag should be optional (like the `transpile` flag), would you like to add this new feature in a PR?

[Contributing guide lines](https://github.com/monounity/karma-typescript/wiki/Contributing)

**Comment by jods4** [comment]
I opened a PR that made this work in my project.

It's really minimal and could be improved:
In particular it seems that there's no easy to send back typescript code, es6 code that would be transpiled (`import`/`export`) and you have to compile the AST in the transformer.
