### ISSUE TITLE
Display all files (includeAllSources)

### ISSUE THREAD

**Issue by marlongehringer** [monounity/karma-typescript#218]
Hi,
is there an option to show every file in the coverage report? Like the `includeAllSources` option in [karma-coverage](https://github.com/karma-runner/karma-coverage)? 

With `karma-typescript` I get following output:
![karma-typescript](https://user-images.githubusercontent.com/8615026/33380973-06da7ce4-d51d-11e7-910a-602aac5f87a8.png)

And with `coverage` and `coverageReporter.includeAllSources = true`:
![coverage](https://user-images.githubusercontent.com/8615026/33381052-31202b48-d51d-11e7-936c-37a3fcb8a6b2.png)

I want to include all the files, also the files without any .spec file, so that my treshold will fail if I'm missing some .spec files.

I found no option to enable that. Do you have any advice?

**Comment by erikbarke** [comment]
What does your Karma config look like? All files that are picked up by Karma and karma-typescript will get coverage, it doesn't matter if they have corresponding unit tests or not: #116.

I just tried this out by adding a new file to one the example projects and using wildcards all files gets coverage, even those without a test:

```js
frameworks: ["jasmine", "karma-typescript"],

files: [
    { pattern: "src/**/*.ts" }
],

preprocessors: {
    "**/*.ts": ["karma-typescript"]
},

reporters: ["dots", "karma-typescript"],
```
