### ISSUE TITLE
Karma-typescript fails on npm install command

### ISSUE THREAD

**Issue by Drag13** [monounity/karma-typescript#221]
Hi guys, 

We found an issue with npm install and latest package 3.0.8

You have a dependence on the coffee-script which is already renamed to the coffeescript. So when we try to install it all fails.

Bug can be reproduced with this setup:
    
    "jasmine-core": "2.8.0",
    "karma": "1.7.1",
    "karma-jasmine": "1.1.0",
    "karma-typescript": "3.0.8"

**Comment by vidartf** [comment]
The dependency in question is `pad` that should be upgraded to major version 2 (which has an updated dependency). For now, a workaround is to add a dev dependency on `"coffee-script": "1.12.7"`, see https://github.com/jashkenas/coffeescript/issues/4805.

**Comment by Drag13** [comment]
Thanks, so I assume this bug is not related to this repo and should be closed?

**Comment by vidartf** [comment]
The bug is not caused by this repo, but the `pad` dependency should probably still be updated to version 2 as the old version has a deprecated dependency. I see a PR was opened for that, so maybe leave the issue open until the PR is resolved.

**Comment by erikbarke** [comment]
Thanks guys 😃

**Comment by noru** [comment]
> As a quick workaround, you can reference an older version of the library in your package.json.
"coffee-script": "1.12.7" worked in my case.

Quote from the link above. Solved my problem
