### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buffer/' of undefined

### ISSUE THREAD

**Issue by Duskfall** [monounity/karma-typescript#23]
Hello! I am using the karma-typescript for another project which is written with namespaces and no modules at all.

When I run karma I get an error:

Uncaught TypeError: Cannot read property 'buffer/' of undefined
at C:/Users/AppData/Roaming/npm/node_modules/karma-typescript/lib/bundlers/builtin/commonjs.js:24

Does this happen because of no export classes, interfaces etc?

Here is my tsconfig:

````
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": false,
    "removeComments": true,
    "preserveConstEnums": true,
    "sourceMap": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "strictNullChecks": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "target": "es5",
    "module": "none"
  },
  "compileOnSave": true,
  "exclude": [
    "node_modules",
    "bower_components",
    "Scripts/typings/lodash/lodash-3.10.d.ts"
  ]
}
````

**Comment by monounity** [comment]
Hey @Duskfall, could you try the latest from master now?

**Comment by Duskfall** [comment]
Confirmed it works now! Thanks for prompt response
