### ISSUE TITLE
Compilation context has two separate typings, leading to failure

### ISSUE THREAD

**Issue by ktalebian** [monounity/karma-typescript#231]
`@types/react-router` incorrectly has `react` defined in its dependencies with the version of `*`. As a result, karma-typescript testing fails with error

```
node_modules/@types/react/index.d.ts(2736,19): error TS2320: Interface 'ElementClass' cannot simultaneously extend types 'Component' and 'Component'. Named property 'props' of types 'Component' and 'Component' are not identical.
``` 

and alike. I had this problem with webpack as well, but adding 

```
"paths": {
    "react": ["node_modules/@types/react"]
  }
```

to my `tsconfig.json` fixed the problem. It seems however, this property is not respected in the karma. How do I fix this problem?

**Comment by erikbarke** [comment]
Do you have a repo I could take look at?

**Comment by ktalebian** [comment]
@erikbarke require `@types/react` < 16, and `@types/react-router` `v3.0.4`. 

Because react-router is depending on React `*`, then it will try to use v16, but you are referencing v15 for the rest of your application.

**Comment by erikbarke** [comment]
I installed this with npm:

```bash
npm i @types/react-router@3.0.4 @types/react@15 react react-router

├─┬ @types/react-router@3.0.4 
│ └── @types/react@15.6.11 
├── react@16.2.0 
└── react-router@4.2.0
```

And then I modified `hello.component.ts` in the examples/typescript-latest project:

```js
import { HelloService } from "./hello-service.interface";

import { Component } from "react";
import { Router } from "react-router";

export class HelloComponent {

    constructor(private helloService: HelloService) {}

    public sayHello(): string {

        console.log(Component, Router);
        return this.helloService.sayHello();
    }
}
```

This runs without any errors if I run `npm test` so I'm having a hard time reproducing this issue...
