### ISSUE TITLE
Coverage being generated for sources that are not being tested

### ISSUE THREAD

**Issue by parky128** [monounity/karma-typescript#236]
I have just started using this plugin for an angularJS application and have so far setup a very simple test for a service I have:

```
import { GpsService } from "./gps.service";

describe("Service", () => {
  let gpsService: GpsService;

  beforeEach(() =>{
    angular.mock.module("app.services");
    angular.mock.module(function($provide) {
      $provide.factory('endpointsurls', function() {
        return {};
      });
    });
  });

  beforeEach(inject((_gpsService_) => {
    gpsService = _gpsService_;
  }));

  it('should do something', () => {
    gpsService.getGPSFix();
    expect(1).toEqual(1);
  })
});
```

This is just a dummy test as you can probably tell, but I wanted to prove I could call a method on my service and see it picked up in my coverage report.

I do indeed see the file covered by the output html report, but I also see my other TS sources showing with coverage even though I havent written any specs for these. Is this normal behaviour? I was hoping I would see zero coverage for anything that doesnt have a spec file associated, is this a config option?

![image](https://user-images.githubusercontent.com/10373419/34720129-8b98f266-f535-11e7-9ef0-dff54924aaf4.png)

Thanks

**Comment by erikbarke** [comment]
This is expected behavior, but you can exclude files from the coverage report by using the setting `karmaTypescriptConfig.coverageOptions.exclude`, as suggested in #116!

**Comment by parky128** [comment]
Thanks @erikbarke 

I will take a look at this further 👍

**Comment by erikbarke** [comment]
Closing this, feel free to reopen if you need!
