### ISSUE TITLE
Coverage browser folder question

### ISSUE THREAD

**Issue by nathagey** [monounity/karma-typescript#251]
Thanks for the great work, it's made typescript integration super easy.

How do I configure html coverage report to appear in the root of the coverage folder? It currently shows up in a folder named for the browser that ran the tests.

current
```
coverage/Chrome<.. etc ..>/html/index.html
```

desired
```
coverage/index.html
```

Thanks!

**Comment by erikbarke** [comment]
The setting you're looking for is `karmaTypescriptConfig.reports`, it gives you fine-grained control over paths and filenames:

```js
karmaTypescriptConfig: {
    reports:
    {
        "cobertura": {
            "directory": "coverage",
            "filename": "coverage.xml",
            "subdirectory": "cobertura"
        },
        "html": "coverage",
        "text-summary": ""
    }
}
```
