### ISSUE TITLE
Testing with ES2016 dependency

### ISSUE THREAD

**Issue by vidartf** [monounity/karma-typescript#255]
I'm trying to test some code, where one of the dependencies are using an ES2016 feature (the exponentiation operator `**`). Encountering the line `x = 10.0 ** logX;`, karma-typescript then fails with the following error:

```
START:
23 02 2018 15:06:19.017:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.7.2
23 02 2018 15:06:21.529:INFO [compiler.karma-typescript]: Compiled 3 files in 2490 ms.
23 02 2018 15:06:23.011:ERROR [source-reader.karma-typescript]: Error parsing code: Unexpected token (477:20)
```

Note: webpack seems to have no issues with this file.

**Comment by vidartf** [comment]
I tried debugging this by making a custom transform function, and it seems this parse error happens before that. I'm considering trying a `noParse` option, but I think I need the dependencies.

**Comment by vidartf** [comment]
It seems the following did the trick:
```js
bundlerOptions: {
  acornOptions: {
    ecmaVersion: "2016",
  },
}
```

Actionable: `acornOptions` should probably be included in the readme description of the available options. I had to read the source to figure this one out :)

**Comment by erikbarke** [comment]
Hey @vidartf, nice detective work ☺️ I've simply updated the code to default to ecma version 7/2016, it seems there are enough packages out there now using es-2016 and all tests seem to pass with this option. Regarding documenting this option, I'm a bit reluctant doing this since this is such an fundamental part of the bundler but if enough people want it, I'll do it.

**Comment by vidartf** [comment]
If simply updating the version works in a backwards-compatible way, then I agree that it isn't strictly needed to expose this to the user (i.e. document it as a feature). Feel free to close as fixed once you're satisfied!
