### ISSUE TITLE
(autoWatch: false) does not generate folder coverage and does not run tests

### ISSUE THREAD

**Issue by jocafi** [monounity/karma-typescript#259]
Dear @erikbarke ,

  using the karma.conf.js below and running npm it does not generate the folder coverage and seems to not run any tests, although it opens chrome in my MacOS. I tried it also in the "examples/typescript-latest" with same result.

When I remove the line **autoWatch: false** from karma.conf.js, then it works fine.

Reading the [documentation](http://karma-runner.github.io/2.0/config/configuration-file.html), I would expect that the tests should run once, the coverage shall be generated and karma shall exit.

```
module.exports = function(config) {
    config.set({
        autoWatch: false,
        frameworks: ["jasmine", "karma-typescript"],
        files: [
            { pattern: "src/**/*.ts" }, // *.tsx for React Jsx
            { pattern: "test/**/*.ts" }
        ],

        preprocessors: {
            "src/**/*.ts": ["karma-typescript", "coverage"], // *.tsx for React Jsx
            "test/**/*.ts": ["karma-typescript"]
        },
        reporters: ["progress", "coverage", "karma-typescript"],
        browsers: ["Chrome"]
    });
};
```
Thanks for your support !

**Comment by erikbarke** [comment]
Do you have an example repo I could take a look at?

**Comment by jocafi** [comment]
Hi Erikbarke,

How to reproduce the error:

1) Clone the repo https://github.com/monounity/karma-typescript

2) Go to the source "examples/typescript-latest"

3) Add the line below to your **karma.conf.json** file:

`autoWatch: false,`

4) run npm i

5) run npm test 

6) See that no coverage and tests exist.

**Comment by erikbarke** [comment]
Ok, this is a Karma quirk/feature:

* `autoWatch` defaults to `true`
* `singleRun` defaults to `false`

If both `autoWatch` and `singleRun` are set to `false` Karma will just launch the browser without running any tests and wait for a `karma run`. If you don't want auto watch you have to set `singleRun` to `true`, this will run your tests once and exit.

**Comment by jocafi** [comment]
Thx, Erik. 
I tried the configuration below and it also does not work:
- `autoWatch` = false
- `singleRun` = true
and
- `autoWatch` = true
- `singleRun` = true

The system did not exit. I have to click on ctrl+C to exit manually.
Sorry, but `singleRun` is not working.

**Comment by jocafi** [comment]
ok. I tested using `singleRun = true` and it run once as expected. 
However, it would be nice to have it the documentation. Otherwise, similar issues may be created. :-)
Thanks !
