### ISSUE TITLE
About coverage of default parameter

### ISSUE THREAD

**Issue by maple3142** [monounity/karma-typescript#260]
I called `createLSStorage({ namespace: 'test' })` in tests, but why I get the result below?
![coverage](https://i.imgur.com/T2OePRl.png)

**Comment by erikbarke** [comment]
I think this is a source map and re-mapping issue, what does the transpiled code look like?

**Comment by maple3142** [comment]
Transpiled code:
```javascript
var _b = _a.storage, storage = _b === void 0 ? window.localStorage : _b, _c = _a.stringify, stringify = _c === void 0 ? JSON.stringify : _c, _d = _a.parse, parse = _d === void 0 ? JSON.parse : _d, namespace = _a.namespace;
```

**Comment by erikbarke** [comment]
This is probably a [remap-istanbul](https://github.com/SitePen/remap-istanbul) issue, karma-typescript just relays the source mapping to remap-istanbul so I don't think there's much I can do here 😞
