### ISSUE TITLE
"d.ts"-Files are wrongly added to bundle

### ISSUE THREAD

**Issue by Franziskus1988** [monounity/karma-typescript#262]
I'm trying to get karma-typescript running, but I'm currently stuck with this problem:

![grafik](https://user-images.githubusercontent.com/5774027/37891188-9e871fea-30d3-11e8-9aa4-0b13b08abcdd.png)

**Comment by erikbarke** [comment]
Do you have an example repo I could take a look at?

**Comment by Franziskus1988** [comment]
Yes. I've created one: https://github.com/Franziskus1988/karma-typescript-problem

**Comment by jayyf9** [comment]
I have the same problem with the source reader error and also with the compiler despite excluding this.
![capture](https://user-images.githubusercontent.com/5147013/38620851-ddb38d9c-3d9f-11e8-8b0f-e9d7d4ab7c59.PNG)
![capture](https://user-images.githubusercontent.com/5147013/38620886-ec7841d8-3d9f-11e8-8ae3-64d6ba1d5699.PNG)

**Comment by Franziskus1988** [comment]
No. I tried every method to exclude d.ts files, but it didn't work. In my opinion it's a bug.

**Comment by Franziskus1988** [comment]
@erikbarke Any news, regarding this error? Otherwise I will have to use the karma-webpack plugin.

**Comment by surol** [comment]
@Franziskus1988 Had the same issue, until realized there is an import of `d.ts` file in one of the files. Make sure you don't have something like `import './some/path/some-file.d.ts`

**Comment by Franziskus1988** [comment]
@surol Please check my example repo: https://github.com/Franziskus1988/karma-typescript-problem

**Comment by surol** [comment]
@Franziskus1988 Your first problem is ["module": "commonjs"](https://github.com/Franziskus1988/karma-typescript-problem/blob/8a0927cc9c970993f387ccc70678daba6d7e17e9/tsconfig.json#L3)
With `"module": "es2015"` it compiles.

Your second problem is `easeljs`, which seems can not be resolved by TypeScript compiler.

Neither is this plugin's compatibility problem. Both are related to TypeScript compatibility.
