### ISSUE TITLE
Not working with webpack

### ISSUE THREAD

**Issue by yesman85** [monounity/karma-typescript#27]
I'm having trouble getting it to work with webpack, this is my config:

```
var webpackConfig = require('./webpack.config');

module.exports = function(config) {
    config.set({
        basePath: '',
        frameworks: ['mocha', 'chai', 'sinon', 'karma-typescript'],
        files: [
            { pattern: "test/**/*.ts" }
        ],
        exclude: [
        ],
        preprocessors: {
            'test/**/*.ts': ['webpack'],
            '**/*.ts': ['karma-typescript']
        },
        webpack: {
            module: webpackConfig.module,
            resolve: webpackConfig.resolve
        },
        reporters: ['progress', 'karma-typescript'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: true,
        browsers: ['Chrome'],
        singleRun: false,
        concurrency: Infinity,
        karmaTypescriptConfig: {
            reports: {
                "text-summary": "coverage"
            }
        }
    })
}
```

But when I run it I get this output:

> Version: webpack 1.13.3
> Time: 7ms
> webpack: bundle is now VALID.
> 13 11 2016 17:36:01.946:INFO [compiler.karma-typescript]: Compiled 7 files in 1066 ms.
> 13 11 2016 17:36:03.637:INFO [builtin-bundler.karma-typescript]: Bundled imports for 1 file in 123 ms.
> webpack: bundle is now INVALID.
> Hash: f4683f5fa2953dc3a97c
> Version: webpack 1.13.3
> Time: 8ms
> 
> ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' C:/Projects/test/test/main.test.js in C:\Projects\test
> webpack: bundle is now VALID.

I couldn't find any reference project that is using webpack and karma-typescript.

**Comment by monounity** [comment]
@yesman85, `karma-typescript` does it's own bundling, try removing webpack from karma.conf.js!

**Comment by yesman85** [comment]
Yeah I tried that, but even with the exact same config as the readme I get this error:

```[Error: No source found for C:/Projects/jsWebDb/node_modules/commandpost/index.d.ts!
Is there a mismatch between the Typescript compiler options and the Karma config?]
Error: No source found for C:/Projects/jsWebDb/node_modules/commandpost/index.d.ts!
Is there a mismatch between the Typescript compiler options and the Karma config?
    at C:\Projects\jsWebDb\node_modules\karma-typescript\lib\compiler.js:70:23
    at Array.forEach (native)
    at C:\Projects\jsWebDb\node_modules\karma-typescript\lib\compiler.js:64:19
    at invokeFunc (C:\Projects\jsWebDb\node_modules\lodash.debounce\index.js:160:19)
    at trailingEdge (C:\Projects\jsWebDb\node_modules\lodash.debounce\index.js:207:14)
    at timerExpired [as _onTimeout] (C:\Projects\jsWebDb\node_modules\lodash.debounce\index.js:195:14)
    at Timer.listOnTimeout (timers.js:92:15)```

**Comment by monounity** [comment]
It looks like the file pattern in karma.conf.js is picking up files from a node_modules directory, in this case `C:/Projects/jsWebDb/node_modules/commandpost/index.d.ts`. If you turn on debug logging in in karma.conf.js, do you see a lot of files that shouldn't be included in the test run?

**Comment by yesman85** [comment]
It does seem that way yes, it is including a ton of files from the node_modules directory. It's odd because I specified it in the exclude part of the tsconfig and the config. I worked around it by changing the files patterns to 

```        files: [
            { pattern: "./src/**/*.ts" },
            { pattern: "./test/**/*.ts" }
        ],```

**Comment by yesman85** [comment]
Ok I dug a little deeper, made a small test case, I think the problem is the imports from node_modules.

I changed the hello.component.spec.ts a bit to use chai:

```js
import { IHelloService } from "./hello-service.interface";
import { HelloComponent } from "./hello.component";
import { expect } from 'chai'

class MockHelloService implements IHelloService {

    public sayHello(): string {
        return "Hello world!";
    }
}

describe("HelloComponent", () => {

    it("should say 'Hello world!'", () => {

        let mockHelloService = new MockHelloService();
        let helloComponent = new HelloComponent(mockHelloService);

        expect(helloComponent.sayHello()).to.be('Hello world!');

    });
});
```

But this gives the exception: 

>   Error: Could not find module
> 
>   './test' from
> 
>   'C:/Projects/test/node_modules/chai/lib/chai/utils' using paths
> 
>   [./test]
>   [C:/Projects/test/node_modules/chai/lib/chai/test]
>   [C:/Projects/test/node_modules/chai/lib/chai/test.js]
> 
>   at node_modules/karma-typescript/lib/bundlers/builtin/commonjs.js:49

**Comment by yesman85** [comment]
After reading some more, found this issue: https://github.com/monounity/karma-typescript/issues/10

That seems to answer some questions :)
