### ISSUE TITLE
Breaking change was introduced during PATCH change

### ISSUE THREAD

**Issue by falsyvalues** [monounity/karma-typescript#274]
Hi!

Afer upgrade  from `3.0.8` to `3.0.9` and above my current karma setup stop working with this meaningless message (in this case):

> You need to include some adapter that implements \_\_karma__.start method!

If we run `karma` without `--single-run` we will get a bit more information.

> Unhandled rejection Error: COMPILATION ERROR
>     at maybeWrapAsError (/projects/test/node_modules/bluebird/js/release/util.js:61:12)
>     at /projects/test/node_modules/bluebird/js/release/nodeback.js:38:50
>     at nextPreprocessor (/projects/test/node_modules/karma/lib/preprocessor.js:26:14)
>     at Object.callback (/projects/test/node_modules/karma-typescript/dist/karma/preprocessor.js:19:36)
>     at /projects/test/node_modules/karma-typescript/dist/compiler/compiler.js:73:20
>     at Array.forEach (<anonymous>:null:null)
>     at Compiler.onProgramCompiled (/projects/test/node_modules/karma-typescript/dist/compiler/compiler.js:66:24)
>     at Compiler.compileProject (/projects/test/node_modules/karma-typescript/dist/compiler/compiler.js:52:14)
>     at Compiler.<anonymous> (/projects/test/node_modules/karma-typescript/dist/compiler/compiler.js:28:23)
>     at invokeFunc (/projects/test/node_modules/karma-typescript/node_modules/lodash/lodash.js:10333:23)
>     at trailingEdge (/projects/test/node_modules/karma-typescript/node_modules/lodash/lodash.js:10382:18)
>     at Timeout.timerExpired [as _onTimeout] (/projects/test/node_modules/karma-typescript/node_modules/lodash/lodash.js:10370:18)
>     at ontimeout (timers.js:498:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:290:5)

Diggin thru the change log I found #215 #216 which is a bit breaking change as you may see above.

To summarize this I kindly ask:
- Please provide a way to turn this off since by default TSC emits code (`noEmitOnError: false`)
- Don't introduce breaking changes in PATCH updates
- Fix message when karma runs with `--single-run` flag because "You need to include some adapter that implements \_\_karma__.start method!" is not sufficient

Thanks!

Used dependencies:

> "karma": "~2.0.4",
> "karma-babel-preprocessor": "~7.0.0",
> "karma-chrome-launcher": "^2.2.0",
> "karma-fixture": "0.2.6",
> "karma-jasmine": "~1.1.2",
> "karma-json-fixtures-preprocessor": "0.0.6",
> "karma-spec-reporter": "~0.0.28",
> "karma-typescript": "~3.0.12",

Related to #244 #249 #269

**Comment by erikbarke** [comment]
Thanks for doing all this digging! This absolutely needs to be fixed, PR?

**Comment by erikbarke** [comment]
I agree, go ahead!

[Contributing guidelines](https://github.com/monounity/karma-typescript/wiki/Contributing)

**Comment by falsyvalues** [comment]
Hi @erikbarke I was digging a bit this topic and found https://github.com/karma-runner/karma/issues/2064 issue, I see no way to handle preprocessor error in a nice way. I'm also not sure if this should be kept in code because it cause whole program to exit, maybe until we get a way to handle preprocessor errors in karma. What do You think?
```
if (this.project.getTsconfig().options.noEmitOnError) {
    ts.sys.exit(ts.ExitStatus.DiagnosticsPresent_OutputsSkipped);
}
```

**Comment by erikbarke** [comment]
So we remove just those lines instead of rolling back #216 entirely?

**Comment by falsyvalues** [comment]
From my point of view `noEmitOnError` is not usable in karma since it will break whole runner, not sure people deal with this. Do You have any information from users?
For running test depending on ts compilation errors I'm 👍 for dedicated option.

**Comment by erikbarke** [comment]
Ah, dedicated option as in `stopOnFailure`, default `false` instead of relying on `noEmitOnError`?
If that's the case I'm all for it 👍

**Comment by erikbarke** [comment]
@falsyvalues, have you made any progress on this issue?

**Comment by falsyvalues** [comment]
@erikbarke Sorry for delay, recently I had no chance to look on this. If possible it can be taken over to someone else. I can't give any ETA right now 😢

**Comment by erikbarke** [comment]
No worries, I'll leave this open!

**Comment by mattcasey** [comment]
I am not sure if this is the right place to bring it up. I would love to run `karma` without checking compiler errors at all. Why bother, since we will have to run `tsc` again before an app can actually be deployed. I usually have `tsc --watch` in VS Code as well, where type errors are much more helpful. I am looking for a similar flag as `ts-node` where you can set TRANSPILE_ONLY=true and willing to dig in and see if I can help out. 

Let me know if I should make a new issue. It seems like the above notes are about getting a more helpful error?

**Comment by DerGernTod** [comment]
as soon as you use jasmine-matchers you won't have any success in running karma with karma-typescript, their typings throw errors (at least with ts 3.7.4):
> 19 02 2020 11:11:05.210:ERROR [compiler.karma-typescript]: node_modules/jasmine-expect/dist/toBeFalse.d.ts(5,13): error TS2717: Subsequent property declarations must have the same type.  Property 'toBeFalse' must be of type '() => boolean', but here has type 'ToBeFalse'.

how about a flag to ignore diagnostics? e.g.
```
karmaTypescriptConfig: {
  skipDiagnostics: true
}
```
and then within `compiler.ts`:
```
        [...]
        this.cachedProgram = this.program;
        if (!this.config.karmaTypescriptConfig.skipDiagnostics) {
            this.runDiagnostics(this.program, this.compilerHost);
        }
        this.program.emit();
        [...]
```
