### ISSUE TITLE
Arrow Function not supported in coverage

### ISSUE THREAD

**Issue by rinick** [monounity/karma-typescript#289]
if tsconfig is targeting es2017,  arrow function will be kept as is in the output js files, in that case, karma would output this error 

```
Failed to parse file: C:\project\test.tsx
25 08 2018 17:59:20.710:ERROR [preprocessor.coverage]: Line 20: Unexpected token =>
```

**Comment by erikbarke** [comment]
This is expected behavior, the application and its tests are supposed to be transpiled to ES5, otherwise the tests won't run in!
