### ISSUE TITLE
"Duplicate identifier..." when I'm using gulp-sequence with different typings

### ISSUE THREAD

**Issue by kubut** [monounity/karma-typescript#29]
Hi again. You probably already hate me but I found another problem ;)
It is complicated situation and I'm not sure if you are able to do something with this - maybe I have to change structure of my project (what would be huuuuge challange because it is really large application). 
In my project I have 4 angular applications and every one has own gulp tasks (build, tests etc.). In addition I have common task which run sub-tasks from all four applications by gulp-sequence. Ok - it is hard to understand I know :) I prepared simple project which (I hope) shows what I'm talking about.
Just download zip, run `npm i` and `gulp init` (gulp init will install typings).
OK - now you have 3 commands:
- `gulp karma:foo` - fires tests for `foo` application
- `gulp karma:bar` - fires tests for `bar` application
- `gulp karma:full` - fires `gulp karma:foo` and `gulp karma:bar` in sequence.

First and second works fine but the last one fails with errors:
```
15 11 2016 23:23:29.161:ERROR [compiler.karma-typescript]: src/foo/typings/jasmine/jasmine.d.ts(80,9): error TS2375: Duplicate number index signature.
15 11 2016 23:23:29.161:ERROR [compiler.karma-typescript]: src/foo/typings/jasmine/jasmine.d.ts(134,9): error TS2374: Duplicate string index signature.
```
Note that typings for both modules are in different localizations (but jasmine.d.ts is in both). I think it is a key.
As I said I'm not sure if it is problem with your plugin itself but it looks like typescript compiler remember all compiled files - not only from one compile task but from all sequence. Maybe you can clear this after coverage is generated? Of course I'm totally noob in this topic so I may be totally wrong with my suspicions ;)

I know my descriptions may be a little crazy so here is example project:
[foobar_KT.zip](https://github.com/monounity/karma-typescript/files/593304/foobar_KT.zip)

My env
--
OS: Mint 18
NodeJS: v6.9.1
NPM: v3.10.8
Gulp: v3.9.1

**Comment by monounity** [comment]
Well, you *do* have a nack for finding quirky fringe case bugs... However, using `karma-nyan-reporter` gives you extra internet points :)
Also, great example package, it made finding this bug easy!

**Comment by kubut** [comment]
Wow, thats a quick answer :) But are you sure that `var cloneDeep = require("lodash.cloneDeep"),` this is correct? I think it should be `clonedeep` no `cloneDeep`

**Comment by monounity** [comment]
Oops, require() works on osx with both uppercase and lowercase...

**Comment by kubut** [comment]
Ok, now it works fine! Thanks! When you will bump NPM version? :)

**Comment by monounity** [comment]
Probably this weekend!
