### ISSUE TITLE
karma-typescript 3.0.13 has peer dependency warnings when used with typescript 3

### ISSUE THREAD

**Issue by fr0** [monounity/karma-typescript#298]
```
warning " > karma-typescript@3.0.13" has incorrect peer dependency "karma@1 || 2".
warning " > karma-typescript@3.0.13" has incorrect peer dependency "typescript@2".
```

Seems odd that this hasn't been updated to typescript 3 yet.

**Comment by erikbarke** [comment]
Fixed in #292, will be released in [4.0.0](https://github.com/monounity/karma-typescript/milestone/22).

**Comment by fr0** [comment]
Any chance of pushing this out sooner in 3.X patch for those of us using TypeScript 3 in production?

**Comment by erikbarke** [comment]
That's a tricky one... #296 and #295 have already been merged to `master` and I would really prefer to introduce those changes in a major version, ie 4.0.0, so probably no 🤔

**Comment by erikbarke** [comment]
@fr0, 4.0.0 is in beta on npm now!
