### ISSUE TITLE
Shouldn't this library become deprecated?

### ISSUE THREAD

**Issue by nadavye** [monounity/karma-typescript#299]
Hi,

Since this library is intended to be used for a two years old a deprecated version of Istanbul, I wonder if there's a point in maintaining this library as it just confuses end users?

Deprecated version of Istanbul: https://github.com/gotwarlost/istanbul
Latest version of Istanbul: https://github.com/istanbuljs

Thoughts?

Nadav

**Comment by erikbarke** [comment]
Deprecating? Certainly not, that seems a bit drastic, don't you think? Upgrading has been in the pipeline for a while now: #158, [roadmap](https://github.com/monounity/karma-typescript/wiki/Roadmap). If you would like upgrade to the maintained version of Istanbul, here are the [contributing guidelines](https://github.com/monounity/karma-typescript/wiki/Contributing).

**Comment by erikbarke** [comment]
Closing in favor #300.
