### ISSUE TITLE
Typescript 1.8.10

### ISSUE THREAD

**Issue by Duskfall** [monounity/karma-typescript#3]
Is it possible to make it work for Typescript version 1.8? or it requires at least version 2?

**Comment by g00fy-** [comment]
@Duskfall  the `package.json` file does not any explicit dependencies so you should be able to use any compiler version you want. It just have to be installed in your project root.

**Comment by Duskfall** [comment]
Thanks for quick answer @g00fy- 
I have tried with 1.8.10 and it doesn't work that's why i asked this.

it seems there is an error with the preprocessor when typescript version is lower than 2.0.0

![image](https://cloud.githubusercontent.com/assets/2528125/18249287/11d65144-7386-11e6-823c-ee5c80536b11.png)

**Comment by monounity** [comment]
@Duskfall, does it work if you use Typescript 2.0.0^? I just tried running the example project with 1.8.10 and it works.

**Comment by Duskfall** [comment]
Yes it does with 2.0.0. I also tested the example and it works! But in my project it doesn't, perhaps something to do with the typings or tsconfig

**Comment by monounity** [comment]
Ah, which typings are you using? I'll try to reproduce the error.

**Comment by monounity** [comment]
Ok, I can reproduce the error, it seems that the transpile method of the Typescript compiler before typescript@1.9.0-dev.20160610-1.0 can't handle for..in loops... I'll look into it to see if it's possible to create a workaround.

**Comment by Duskfall** [comment]
Hello again, just got to the pc at work today, I couldn't reply sooner sorry. Thanks for the fast response!

**Comment by erikbarke** [comment]
Ok, it seems that the default lib.d.ts doesn't get included automatically in earlier versions of Typescript, at least that's my working hypothesis now. I'll try to create a fix asap!
