### ISSUE TITLE
ERROR [compiler.karma-typescript] however Karma doesn't fail

### ISSUE THREAD

**Issue by mmiszy** [monounity/karma-typescript#30]
Whenever there's a compilation error, eg:

> ERROR [compiler.karma-typescript]: src/hello.component.ts(9,16): error TS2322: Type 'string' is not assignable to type 'void'.

Karma should fail too. Instead, it continues and tests may pass even if there are TypeScript compilation errors.

Is there any way to avoid this behaviour?

Example output:
```
16 11 2016 13:50:33.253:ERROR [compiler.karma-typescript]: src/hello.component.ts(9,16): error TS2322: Type 'string' is not assignable to type 'void'.

16 11 2016 13:50:33.259:INFO [compiler.karma-typescript]: Compiled 3 files in 1160 ms.
16 11 2016 13:50:33.761:INFO [builtin-bundler.karma-typescript]: Bundled imports for 1 file in 0 ms.
16 11 2016 13:50:33.762:INFO [watcher]: Changed file "/Users/miszy/htdocs/karma-typescript/example-project/src/hello.component.ts".
PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 1 of 1 SUCCESS (0.003 secs / 0.001 secs)
```

**Comment by monounity** [comment]
Hey @mmiszy, you can set `noEmitOnError` to true in either `tsconfig.json` or in the karma conf:

```javascript
karmaTypescriptConfig: {
    compilerOptions: {
         noEmitOnError: true,
         //...
    },
    //...
}
```

This will make karma exit in quite a spectacular way, I've added this feature to the documentation!

**Comment by mmiszy** [comment]
I tried adding this to karma conf and to my `tsconfig.json` but it doesn't work. Even with `noEmitOnError: true`, TypeScript still seems to compile the files.
I'm on Typescript 2.0.10, is this a known issue to you?

**Comment by mmiszy** [comment]
> This will make karma exit in quite a spectacular way

Indeed it makes Karma exit. However what I wanted to achieve is for Karma **not** to quit, but just to report the error and keep on watching files for changes. Is it possible?

**Comment by monounity** [comment]
It doesn't seem like this will be easy to implement, Karma seems to be kind of "binary", it either runs the tests or it quits, it's discussed here in a somewhat similar issue: https://github.com/karma-runner/karma/issues/550.
