### ISSUE TITLE
Upgrade to the maintained version of Istanbul

### ISSUE THREAD

**Issue by erikbarke** [monounity/karma-typescript#300]
This package uses the [deprecated version of Istanbul](https://github.com/gotwarlost/istanbul) and should be upgraded to use the [maintained version](https://github.com/istanbuljs/istanbuljs).

What needs to be replaced:

- Coverage instrumentation: replace calls to [karma-coverage](https://github.com/karma-runner/karma-coverage) with custom instrumentation code in [src/istanbul/coverage.ts](https://github.com/monounity/karma-typescript/blob/master/src/istanbul/coverage.ts). 

    - Examples of instrumentation using the new version of Istanbul:
    - The plugin `babel-plugin-istanbul`, [istanbuljs/babel-plugin-istanbul/blob/master/src/index.js](https://github.com/istanbuljs/babel-plugin-istanbul/blob/master/src/index.js).
    - The plugin `istanbul-instrumenter-loader`, [webpack-contrib/istanbul-instrumenter-loader/blob/master/src/index.js](https://github.com/webpack-contrib/istanbul-instrumenter-loader/blob/master/src/index.js)

- The coverage reporter: replace calls to [remap-istanbul](https://github.com/SitePen/remap-istanbul) with custom code in [src/karma/reporter.ts](https://github.com/monounity/karma-typescript/blob/master/src/karma/reporter.ts).

    - Example of reporting using the new version of Istanbul:
    - The plugin `karma-coverage-istanbul-reporter`, [mattlewis92/karma-coverage-istanbul-reporter/blob/master/src/reporter.js](https://github.com/mattlewis92/karma-coverage-istanbul-reporter/blob/master/src/reporter.js)

This (most likely) won't make it into the next major release, 4.0.0, so it should be released in 5.0.0 as there will be breaking changes in the `karma-typescript` config in `karma.conf.js`.

**Comment by ernieturner** [comment]
This might be noted elsewhere, but I figured it was worth bringing up that the old version of Istanbul that this library depends on now has sub-dependencies that [have](https://www.npmjs.com/advisories/755) [known](https://www.npmjs.com/advisories/813) high severity vulnerabilities.

**Comment by lukiffer** [comment]
Thanks for getting this addressed! Any chance we could get a pre-release version pushed to npm prior to the 5.0.0 release?

**Comment by erikbarke** [comment]
@lukiffer, 5.0.0-beta.0 is on npm now!
