### ISSUE TITLE
Configure bundler to include libraries loaded dynamically

### ISSUE THREAD

**Issue by unional** [monounity/karma-typescript#305]
I have a library that will load its plugins dynamically under node_modules.

Is there a way to configure the `bundlerOptions` to include specific libraries so that they are available to the main library?

**Comment by erikbarke** [comment]
Would a base test class like [this one](https://github.com/monounity/karma-typescript/blob/master/examples/angular2/base.spec.ts) solve your problem?

**Comment by unional** [comment]
It turns out this is not possible with webpack either (nor rollup). I need to find a way to do this and then see if I can come up with some solution for karma.

Thanks for looking into this. 🌷
