### ISSUE TITLE
Testing the Typescript application which is based on SystemJS module type

### ISSUE THREAD

**Issue by muthuramj** [monounity/karma-typescript#31]
How to test SystemJS module based Typescript application with this plug ins.

**Comment by monounity** [comment]
Hey @muthuramj, if your code is valid Typescript you should be able to run your tests with karma-typescript without SystemJS, your code will be automatically compiled/bundled using the CommonJS format before running in a browser. Having said that, is there something you need to do with SystemJS, like using a SystemJS plugin?

**Comment by muthuramj** [comment]
Hi @monounity ,

In my build process, I am using SystemJS module type for transpiling the typescript code into browser targeted JS code(ES5). So I wanted to know that will it be safe to test the code with CommonJS module type in browser?
And also I wanted to know about how it will work well with integration tests if the module type is CommonJS(Since CommonJS module is intended for NodeJS)?

**Comment by monounity** [comment]
The scenario you're describing is the very reason I created this plugin, separation of concerns! I want to be able to run my unit tests, with coverage, without jumping through hoops in the Karma conf while keeping unit testing and the build process separated. By default, your code will be transpiled to ES5/CommonJs and bundled by karma-typescript and executed in a browser by Karma, so I think it should work for your project.
