### ISSUE TITLE
require/import a json file no longer works

### ISSUE THREAD

**Issue by rinick** [monounity/karma-typescript#312]
my project has a dependency to antd package, which has a file to import package.json to check version
```
import { version } from '../../package.json';
```
https://github.com/ant-design/ant-design/blob/master/components/version/index.tsx

it works fine in 3.0.13, but after upgrading to 4.0.0-beta.2, it no longer works, showing this error
```
Uncaught Error: Can't find ../../package.json [C:/projects/dglux/node_modules/antd/package.json] (required by C:/projects/dglux/node_modules/antd/lib/version/index.js)
at node_modules/karma-typescript/dist/client/commonjs.js:13:17

Error: Can't find ../../package.json [C:/projects/dglux/node_modules/antd/package.json] (required by C:/projects/dglux/node_modules/antd/lib/version/index.js)
    at require (node_modules/karma-typescript/dist/client/commonjs.js:13:23)
    at node_modules/karma-typescript/dist/client/commonjs.js:18:24
    at Object.global.wrappers.C:/projects/dglux/node_modules/antd/lib/version/index.js.../../package.json (C:/Users/rinick/AppData/Local/Temp/karma-typescript-bundle-11704TSKnZnwSJed9.js:2097:16)
    at require (node_modules/karma-typescript/dist/client/commonjs.js:17:25)
    at node_modules/karma-typescript/dist/client/commonjs.js:18:24
    at Object.global.wrappers.C:/projects/dglux/node_modules/antd/lib/index.js../version (C:/Users/rinick/AppData/Local/Temp/karma-typescript-bundle-11704TSKnZnwSJed9.js:156588:39)
    at require (node_modules/karma-typescript/dist/client/commonjs.js:17:25)
    at node_modules/karma-typescript/dist/client/commonjs.js:18:24
    at Object.global.wrappers.C:/projects/dglux/src/editor/node-tree/NodeRenderer.tsx.react (src/editor/node-tree/NodeRenderer.tsx:3 <- src/editor/node-tree/NodeRenderer.js:28:28)
    at require (node_modules/karma-typescript/dist/client/commonjs.js:17:25)
```

**Comment by erikbarke** [comment]
This change is the prime suspect: https://github.com/monounity/karma-typescript/commit/527005c3252d1ee22e67a60c9e77a68885eac466, does it work if you revert the addition of "json" in the regexp in the compiled version of karma-typescript in your node_modules folder?

**Comment by rinick** [comment]
@erikbarke you are right, when I revert that line the error disappear

**Comment by erikbarke** [comment]
How are using `antd` in your code? I've updated the React integration tests in #314 to use React 16.7.0 and if I (for example) modify [tests/integration-latest/src/frameworks/react/react-tester.tsx](https://github.com/monounity/karma-typescript/blob/fix-json-import/tests/integration-latest/src/frameworks/react/react-tester.tsx) to import `antd` it works with `karma-typescript@4.0.0-beta.2`:

```js
import * as React from "react";
import * as antd from "antd";

export interface ReactComponentProps {
    compiler: string;
    framework: string;
}

export default class ReactTester extends React.Component<ReactComponentProps, {}> {

    public render() {
        console.log(antd.version);
        return <h1>Hello from {this.props.compiler} and {this.props.framework}!</h1>;
    }
}
```

**Comment by rinick** [comment]
> How are using `antd` in your code? 

https://github.com/ticlo/ticlo/blob/master/src/editor/node-tree/NodeRenderer.tsx
https://github.com/ticlo/ticlo/blob/master/karma.conf.js
https://github.com/ticlo/ticlo/blob/master/package.json

hmm, maybe it's because I use `"esModuleInterop": true,` in karmaTypescriptConfig.compilerOptions ?

**Comment by erikbarke** [comment]
Ok, I'm able to reproduce the error, I'll see what I can do!

**Comment by erikbarke** [comment]
I've reverted the change in 527005c3252d1ee22e67a60c9e77a68885eac466, all tests pass without it... The reverted version is in 4.0.0-beta.3 is on npm now!
