### ISSUE TITLE
Could you please support TS new options?

### ISSUE THREAD

**Issue by mushroom-cn** [monounity/karma-typescript#325]
TS has some new options in 3.x, such as build/clean/force. But I can't find any info about those new options in karma-typescript. Could you please support those new feature?

**Comment by erikbarke** [comment]
Config options are converted in https://github.com/monounity/karma-typescript/blob/master/packages/karma-typescript/src/shared/project.ts#L201, any takers on a PR for adding this/making sure it works?

[Contributing guidelines](https://github.com/monounity/karma-typescript/wiki/Contributing)

**Comment by erikbarke** [comment]
Closed in favor of #347.
