### ISSUE TITLE
Wrong paths to readable-stream?

### ISSUE THREAD

**Issue by ziola** [monounity/karma-typescript#335]
Lately I started to have troubles running tests using `karma-typescript@4.0.0`. 
They were working correctly till yesterday, when trying to run tests started to throw
`ERROR [karma-server]: Server start failed on port 9876: Error: Cannot find module 'readable-stream/duplex.js'`

My first steps were to check if the `readable-stream` dependency hasn't update and actually it did. The failures started around the release of version 3.4.0, which I don't use directly. Digging deeper I found that karma-typescript version 4.0.0 updated the readable-stream.

Here is where I started to have some problems understanding how it even worked in the past. The update in v 4.0.0 release bumped readable-stream from ^2.3.3 to ^3.1.1, but it looks like there were no updates to paths in [src/bundler/resolve/shims.ts](https://github.com/monounity/karma-typescript/blob/v.4.0.0/packages/karma-typescript/src/bundler/resolve/shims.ts).
Going through readable-stream repository it looks like with the release of version 3.x the files being referenced there are no longer present compared to the last of the version 2.x releases.

So my questions are:
1. should the path be update to reference the proper files similarly [to this PR in stream-browserify](https://github.com/browserify/stream-browserify/pull/23/files) that this project also uses as a dependency?
2. How it was working in the past couple of months after the readable-stream version was bumped.

**Comment by Derek-Wds** [comment]
I ran into the same problem and couldn't find a solution.

**Comment by erikbarke** [comment]
Does it work if you update the paths like in the stream-browserify PR?

**Comment by ziola** [comment]
OK, something strange happened here. 

I don't know what happened over the weekend, but it works now after reinstalling dependencies from scratch again and with a completely clean project.

When I was doing that last week it didn't help and it was always installing v.4.0.0, but now, without any changes to package.json, it installed v.4.1.0 that contains the updated paths. 

I think it may be an issue with npm not this library, but incidentally it happened just after release of readable-stream.
