### ISSUE TITLE
Does not work with latest version of babel

### ISSUE THREAD

**Issue by mkay581** [monounity/karma-typescript#338]
The `karma-typescript-es6-transform` package here doesn't seem to support Babel 7 (`@babel/core`). It looks like it is using `babel-core` (lower version) [here](https://github.com/monounity/karma-typescript/blob/b9347465a80b9bc93b40a0f91ff15bc363216d1e/packages/karma-typescript-es6-transform/src/transform.ts#L2).

Are there any plans to support the latest version of Babel 7?

**Comment by erikbarke** [comment]
Keeping up with Babel major versions a good idea, but I suspect an upgrade would have to be released in a major version of `karma-typescript` as it most likely would be a breaking change, thoughts @mkay581?

**Comment by mkay581** [comment]
Yeah I'd release it as a new major version unless the change is done in a way that is backwards compatible, which I'm not sure is easily done. But that would be great! Please let us know when this is done. It's currently blocking us from using the package since other deps we have use babel 7.

**Comment by erikbarke** [comment]
There's an upgrade to babel 7 in #343 now, does it work on your end too?
