### ISSUE TITLE
Ignore imports that don't have a source

### ISSUE THREAD

**Issue by yesman85** [monounity/karma-typescript#34]
I have a project that uses the 'estree' typings, there is no actual source for it, just typings.

But in my TS source I do:

`import { ExpressionStatement, FunctionExpression } from 'estree';`

But when I run the tests, I get:

> Error: Cannot find module 'estree' from 'C:/Projects/jsWebDb/src'
>     at Function.module.exports [as sync] (C:\Projects\jsWebDb\node_modules\resolve\lib\sync.js:33:11)
>     at Function.resolve.sync (C:\Projects\jsWebDb\node_modules\browser-resolve\index.js:321:21)
>     at resolveModules (C:\Projects\jsWebDb\node_modules\karma-typescript\lib\bundlers\builtin\bundler.js:177:49)
>     at C:\Projects\jsWebDb\node_modules\karma-typescript\lib\bundlers\builtin\bundler.js:80:21
>     at Array.forEach (native)
>     at C:\Projects\jsWebDb\node_modules\karma-typescript\lib\bundlers\builtin\bundler.js:76:36
>     at Array.forEach (native)
>     at C:\Projects\jsWebDb\node_modules\karma-typescript\lib\bundlers\builtin\bundler.js:72:21
>     at invokeFunc (C:\Projects\jsWebDb\node_modules\lodash.debounce\index.js:160:19)
>     at trailingEdge (C:\Projects\jsWebDb\node_modules\lodash.debounce\index.js:207:14)
>     at timerExpired [as _onTimeout] (C:\Projects\jsWebDb\node_modules\lodash.debounce\index.js:195:14)
>     at Timer.listOnTimeout (timers.js:92:15)

Is there a way to ignore certain imports?

**Comment by monounity** [comment]
Hey @yesman85, v2.1.3 has just been published on npm with support for ignoring modules in the bundler, you can specify an array of modules in `karmaTypescriptConfig.bundlerOptions.ignoredModuleNames`:

```javascript
karmaTypescriptConfig: {
    compilerOptions: {
        noImplicitAny: true,
        //...
    },
    bundlerOptions: {
        ignoredModuleNames: ["estree"],
    }
    //...
},
```

Having said that, do you really need to import the typings? Doesn't just loading the typings in your tsconfig work for you?

**Comment by yesman85** [comment]
Unfortunately it doesn't work with the tsconfig, atleast not how I tried:

```
    "files":[
        "./node_modules/@types/estree/index.d.ts"
    ]
```

and
```
    "compilerOptions": {
        "typeRoots": [
            "./node_modules/@types"
        ]
    },
```

It gives the same error.

But with your solution it works.
