### ISSUE TITLE
Can't install: : Missing package version

### ISSUE THREAD

**Issue by QuantumInformation** [monounity/karma-typescript#346]
When installing I get

npm ERR! Can't install github:monounity/karma-typescript#ff350cad5a30a97eb3f90e7ad773b82e22f461b5: Missing package version

**Comment by erikbarke** [comment]
I suspect this happens because karma-typescript is maintained as a lerna monorepo: the package.json at the root of the repo is for the monorepo and the real packages live in the ./package folder with real package.json files, I guess this trips npm up.
