### ISSUE TITLE
Getting Unexpected token from third party library due to async/await

### ISSUE THREAD

**Issue by fredyagomez** [monounity/karma-typescript#351]
See picture below.  I was assuming just importing "@babel/polyfill" would solve this issue but still getting the same error. Third party library is lit-element (@justinfagnani in case you have an input)

![image](https://user-images.githubusercontent.com/22927931/62967733-6f48f900-bdbe-11e9-8149-26b0e4e419aa.png)

My config looks like this
```
module.exports = function(config) {
  config.set({

    frameworks: ["jasmine", "karma-typescript"],

    files: [
     "@babel/polyfill",
      "./vendor/polyfills/custom-elements-es5-adapter.js",
      "./vendor/polyfills/custom-elements.min.js",
      {pattern: "src/components/**/*.ts"},
      {pattern: "src/utils/**/*.ts"}
    ],
    exclude: [
    ],

    preprocessors: {
      "**/*.ts": ["karma-typescript"]
    },

    reporters: ["dots", "karma-typescript"],

    browsers: ["ChromeHeadless"],

    singleRun: true,

    karmaTypescriptConfig: {
      bundlerOptions: {
        transforms: [
          require("karma-typescript-es6-transform")()
        ]
      },
      compilerOptions: {
        "lib": ["es6", "dom"]
      },
      reports: {
        "lcovonly": {
          "directory": "coverage",
          "filename": "lcov.info",
          "subdirectory": "typescript"
        }
      }
    }
  });
};
```

**Comment by justinfagnani** [comment]
The open-wc.org team may be able to help you. cc @daKmoR @LarsDenBakker @thepassle

**Comment by fredyagomez** [comment]
@justinfagnani thanks for the incredible fast respond. Saw the link for open-wc.org really helpful. I see the recommendation is to go with `@open-wc/karma-esm` for typescript/lit-elements web components.

**Comment by fredyagomez** [comment]
Closing this as I will be looking at open-wc.org for other approaches.

**Comment by nidtrifork** [comment]
@fredyagomez did you manage to find a solution without using `@open-wc/karma-esm`?
