### ISSUE TITLE
"non javascript content" when importing for side-effects

### ISSUE THREAD

**Issue by patrykbuzowicz** [monounity/karma-typescript#36]
I'm working on turning a legacy JS project to TS and I want to integrate unit tests for the TS code using this great plugin. Unfortunately, the migration of the legacy code sometimes requires importing other modules just for side effects here and there, like `import "./module"`

Apparently, however, this causes the builtin compiler and bundler to generate the "non javascript content" in the bundle and hence when that module is later imported by some other module not only for side effects, the requiring module gets passed an `undefined` (because the dependant module has got overridden with "non javascript content") and the code terminates.

I know this is kind of an edge case, however I want to ask whether it might be easy to get fixed.

Thanks!

**Comment by monounity** [comment]
Hi @patrykbuzowicz, the logic for collecting required modules has been improved in b188373825c67dcefbc83073b2c44a605af99c86 but it's not on npm yet, does it work if you install the latest from master, ie `npm install https://github.com/monounity/karma-typescript`?

**Comment by patrykbuzowicz** [comment]
Thanks for your quick response @monounity, I saw the commit and it touches the parts of code that I suspected so it looks promising. I'll review it in the evening and let you know

**Comment by patrykbuzowicz** [comment]
Works like a charm. Thank you for the quick response! Closing...
