### ISSUE TITLE
Babel 7 upgrade release

### ISSUE THREAD

**Issue by ksarath** [monounity/karma-typescript#361]
I am getting the following error when I use **karma-typescript-es6-transform** 

Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel

I do see the babel 7 upgrade is done for **karma-typescript-es6-transform** but not released yet. when can we expect a release?

**Comment by erikbarke** [comment]
The upgrade should be in https://www.npmjs.com/package/karma-typescript-es6-transform/v/5.0.0-beta.3, does it work for you if you try the beta?

**Comment by ksarath** [comment]
It works when tried with beta.

**Comment by erikbarke** [comment]
5.0.0 on npm now!
