### ISSUE TITLE
Advice on compatibilty with fetch-mock

### ISSUE THREAD

**Issue by wheresrhys** [monounity/karma-typescript#364]
I maintain the [fetch-mock](https://github.com/wheresrhys/fetch-mock) library. I recently released a major version introducing some new distribution files in order to slowly transition towards ESM. However, this has caused a lot of compatibility issues, the ones with karma-typescript being particularly bad: https://github.com/wheresrhys/fetch-mock/issues/504

I'm hoping one of the maintainers here can advise me on/collaborate on improving my distribution files in order to regain compatibility.

**Comment by erikbarke** [comment]
Hey @scottfwalter, @wheresrhys, I actually got https://github.com/scottfwalter/fetchmock-test running with #365 and these fixes in the example project:
```diff
diff --git a/karma.conf.js b/karma.conf.js
index b036a33..0f361e1 100644
--- a/karma.conf.js
+++ b/karma.conf.js
@@ -4,6 +4,7 @@ module.exports = function(config) {
         frameworks: ["jasmine", "karma-typescript"],
 
         files: [
+            { pattern: "./node_modules/babel-polyfill/dist/polyfill.js" },
             { pattern: "src/**/*.ts" }
         ],
 
@@ -14,6 +15,11 @@ module.exports = function(config) {
         reporters: ["dots", "karma-typescript"],
         karmaTypescriptConfig: {
             tsconfig: "./tsconfig.json",
+            bundlerOptions: {
+                transforms: [
+                    require("karma-typescript-es6-transform")()
+                ]
+            },
             reports: {
                 "cobertura": {
                     "directory": "coverage",
diff --git a/package.json b/package.json
index 9ea5b5d..8f7d074 100644
--- a/package.json
+++ b/package.json
@@ -32,6 +32,7 @@
     "typescript": "^3.7.5"
   },
   "dependencies": {
+    "babel-polyfill": "^6.26.0",
     "rxjs": "^6.5.4"
   }
 }
diff --git a/src/lib/featureToggles/featureToggle.spec.ts b/src/lib/featureToggles/featureToggle.spec.ts
index 64a71f0..c1a123b 100644
--- a/src/lib/featureToggles/featureToggle.spec.ts
+++ b/src/lib/featureToggles/featureToggle.spec.ts
@@ -1,3 +1,5 @@
+// import 'babel-polyfill'; // either put this in one of the tests or include it in the karma config
+
 import { FeatureToggles } from './featureToggle';
 // import * as fetchMock from 'fetch-mock';
 import fetchMock from 'fetch-mock';
```

Karma-typescript uses commonjs when executing the tests in a browser, so I suspect this is the only way to solve this, ie using the es6 transform which uses Babel 🤔

I'll release this in the next beta version for the 5.0.0 release, thoughts?

**Comment by erikbarke** [comment]
<img width="946" alt="Screenshot 2020-01-31 at 10 37 18" src="https://user-images.githubusercontent.com/5539280/73528721-b3d05b80-4415-11ea-9afd-473d68534b52.png">

**Comment by wheresrhys** [comment]
Thanks so much for your help @erikbarke 

> I'll release this in the next beta version for the 5.0.0 release, thoughts?

I can't see any changes to karma-typescript in your example. Do you mean you'll apply those transforms and rules by default so the end user doesn't have to add them?

**Comment by erikbarke** [comment]
Yes, the additional config will be necessary!
