### ISSUE TITLE
Could you add a note for the webpack users?

### ISSUE THREAD

**Issue by Alex1990** [monounity/karma-typescript#370]
By default, webpack cannot resolve the files with `.ts` extension. So, it's better to note the `resolve.extensions` of webpack for those webpack users.

**Comment by erikbarke** [comment]
Great idea! Do you have a configuration example to get me started?

**Comment by Alex1990** [comment]
Sorry! I found that it's unnecessary to use karma-typescript and karma-webpack simultaneously.
