### ISSUE TITLE
Is there a way to disable coverage?

### ISSUE THREAD

**Issue by srsudar** [monounity/karma-typescript#371]
I am debugging an issue where karma periodically opens a browser but the tests never load. I describe it in detail [here](https://github.com/karma-runner/karma-chrome-launcher/issues/216), Chrome just spinning forever.

Some similar issues scattered across various repos suggest that disabling coverage is helpful in solving/debugging this sort of thing. Is there a way to disable coverage in the `karma-typescript` config? I don't see an obvious one.

**Comment by erikbarke** [comment]
Does setting `karmaTypescriptConfig.coverageOptions.instrumentation` to `false` work for you?

**Comment by srsudar** [comment]
Yep that worked but it didn't fix my problem. Damn. Thanks!

**Comment by Finesse** [comment]
> Does setting `karmaTypescriptConfig.coverageOptions.instrumentation` to `false` work for you?

It doesn't disable the coverage reports in my case. This is what does:

```js
// karma.conf.js
module.exports = (config) => {
  config.set({
    // Your Karma configuration...

    karmaTypescriptConfig: {
      reports: {}, // Disables the code coverage report
    },
  })
}
```
