### ISSUE TITLE
Please support karma 5

### ISSUE THREAD

**Issue by Shereef** [monounity/karma-typescript#379]
npm WARN karma-typescript@5.0.2 requires a peer of karma@1 || 2 || 3 || 4 but none is installed. You must install peer dependencies yourself.

**Comment by pamls** [comment]
indeed, the support for the new version of karma would be appreciated. Thank you!

**Comment by Shereef** [comment]
Oh my gawd that was fast, thank you so much!

**Comment by erikbarke** [comment]
5.0.3 on npm now 🚀
