### ISSUE TITLE
Import of relative file above karma-conf fails

### ISSUE THREAD

**Issue by vidartf** [monounity/karma-typescript#38]
So I have the following project layout:
```yaml
root:
  - src: 
    - tsconfig.json
    - folder1/mycode.ts
  - test:
    - karma.conf.js
    - src:
      - tsconfig.json
      - folder1/mycode.spec.ts
```

Then I have the following karma config:
```js
module.exports = function (config) {
  config.set({
    basePath: '..',
    frameworks: ['mocha', 'karma-typescript'],
    files: [
      { pattern: "node_modules/expect.js/index.js" },
      { pattern: "test/src/**/*.ts" }
    ],
    port: 9876,
    colors: true,
    singleRun: true,
    logLevel: config.LOG_DEBUG,

    preprocessors: {
      '**/*.ts': ['karma-typescript']
    },

    reporters: ['mocha', 'karma-typescript'],

    karmaTypescriptConfig: {
      tsconfig: 'test/src/tsconfig.json'
    }
  });
};
```

Note particularly the `basePath: '..'` setting. Then in `root/test/src/folder1/mycode.spec.ts`, I have the following import:
```ts
import { foo } from '../../../src/folder1/mycode';
```

Trying to run this, I get the following errors (relevant bits extracted, can paste full log in pastebin if you want):
```
23 11 2016 18:37:59.138:DEBUG [preprocessor.karma-typescript]: Processing "root/test/src/folder1/mycode.spec.ts".
<snip>
23 11 2016 18:43:10.562:DEBUG [compiler.karma-typescript]: Reading: root/src/folder1/mycode.ts
<snip>
23 11 2016 18:43:18.946:DEBUG [web-server]: serving (cached): root/node_modules/karma-typescript/lib/bundlers/builtin/commonjs.js
Firefox 50.0.0 (Windows 10 0.0.0) ERROR
  Error: Could not find module

  '../../../src/folder1/mycode' from

  'root/test/src/folder1/mycode.spec.js' using paths

  [../../../src/folder1/mycode]
  [root/src/folder1/mycode]
  [root/src/folder1/mycode.js]
  [root/src/folder1/mycodeindex.js]
  [root/src/folder1/mycode/index.js]

  at node_modules/karma-typescript/lib/bundlers/builtin/commonjs.js:48
```

**Comment by vidartf** [comment]
PS: Not sure if title is relevant to the answer or not, so feel free to update as appropriate.

**Comment by vidartf** [comment]
Note that it seems to have no trouble loading other files in the `root/test/src` folder, it is when it goes to `root/src` it seems to fail.

**Comment by vidartf** [comment]
I tried moving the `karma.conf.js` to `root`, but that didn't seem to help either :-/

**Comment by vidartf** [comment]
I'll try to set up a more minimal example tomorrow, if the solution is not immediately apparent to you?

**Comment by monounity** [comment]
Try also including `root/src` in the Karma conf:

```javascript
files: [
    { pattern: "node_modules/expect.js/index.js" },
    { pattern: "test/src/**/*.ts" },
    { pattern: "src/**/*.ts" }
]
```

**Comment by vidartf** [comment]
Thanks! That helped push it further. I had to manually exclude untested files in `src` though:
```
ERROR [karma]: [Error: No source found for root/src/folder1/untestedcode.ts!
Is there a mismatch between the Typescript compiler options and the Karma config?]
```

The next uncovered issue is more esoteric (at least, I have no idea what is going on):
```
[web-server]: serving (cached): root/test/src/patch/patching.spec.js
[middleware:source-files]: Requesting /base/test/src/testutil.spec.js?ff762564617cf194d89f49ffeb19073c5687daaf /
[middleware:source-files]: Fetching root/test/src/testutil.spec.js
[middleware:source-files]: Requesting /base/test/src/typings.d.js?191b0daaa5e7170f6b1559068520aaab6efef222 /
[middleware:source-files]: Fetching root/test/src/typings.d.js
[middleware:source-files]: Requesting /base/node_modules/karma-typescript/lib/bundlers/builtin/commonjs.js?bfd283b21a9cfbeb359f47ccd14d6a458a85166c /
[middleware:source-files]: Fetching root/node_modules/karma-typescript/lib/bundlers/builtin/commonjs.js
[web-server]: serving (cached): root/test/src/testutil.spec.js
[web-server]: serving (cached): root/test/src/typings.d.js
[web-server]: serving (cached): root/node_modules/karma-typescript/lib/bundlers/builtin/commonjs.js
Firefox 49.0.0 (Windows 7 0.0.0) ERROR
  TypeError: CodeMirror.modeInfo is undefined
  at C:/Users/<username>/AppData/Local/Temp/karma-typescript-bundle-4904btEdzhPq1hlq.js:29547
```
CodeMirror is both a direct dependency, and also a dependency of one of my other dependencies (but dedupes to shared version). This other dependency also depends on the officially included add-on `mode/meta` (https://codemirror.net/mode/meta.js). The `modeInfo` field should be typed up in the manual typings (`typings.d.ts`), at least it works with normal compilation/webpack. I'm not sure if any of this is useful information :)

**Comment by monounity** [comment]
It looks like the CodeMirror module hasn't been bundled, have you imported it somewhere in your code? If you don't want to import it, does it work if you add it to the file list in the karma conf?

**Comment by vidartf** [comment]
Code mirror is imported like this: `import * as CodeMirror from 'codemirror';`. Looking at my production webpack code, `modeInfo` is only used in places where `var CodeMirror = __webpack_require__(<some number>);` is present.

**Comment by vidartf** [comment]
Note: The use of `modeInfo` is only in one of my dependencies.

**Comment by vidartf** [comment]
Also note as mentioned above, adding `codemirror.js` to the `files` doesn't change the behavior.

**Comment by monounity** [comment]
I think I've figured out the problem now, I'll try to create a fix asap!

**Comment by vidartf** [comment]
Neat! Sorry for not being very active here, as I'm in a bit of a crunch until the middle of next week. I should be able to test a proposed fix though.

**Comment by monounity** [comment]
Still haven't fixed this issue, I'm just refactoring some stuff to get there!

**Comment by monounity** [comment]
Does it work now if you try the latest from main?

**Comment by vidartf** [comment]
Sorry, same error. I made an effort to try to set up a minimal example, but got stuck on another issue on the way: 
Branch: https://github.com/vidartf/karma-ts-test/tree/codemirror
Appveyor: https://ci.appveyor.com/project/vidartf/karma-ts-test/build/job/d3ax8avfknd997tt
Travis: https://travis-ci.org/vidartf/karma-ts-test/jobs/181191181

It build fine, but compilation in test fails. Not sure why.

**Comment by monounity** [comment]
I'm almost able to compile your example both with `tsc` on command line and with karma-typescript with these changes:

```diff
diff --git a/src/tsconfig.json b/src/tsconfig.json
index 32c8310..a737670 100644
--- a/src/tsconfig.json
+++ b/src/tsconfig.json
@@ -10,5 +10,8 @@
     "noEmitOnError": true,
     "strictNullChecks": true,
     "skipLibCheck": true
     "skipLibCheck": true
-  }
-}
\ No newline at end of file
+  },
+  "include": [
+      "./typings.d.ts"
+  ]
+}
diff --git a/test/karma.conf.js b/test/karma.conf.js
index 57abf0a..a0026c1 100644
--- a/test/karma.conf.js
+++ b/test/karma.conf.js
@@ -8,9 +8,6 @@ module.exports = function(config) {
       { pattern: "test/src/**/*.ts" },
       { pattern: "src/**/*.ts" }
     ],
-    exclude: [
-      "src/typings.d.ts"
-    ],
     colors: true,
     singleRun: true,
     logLevel: config.LOG_DEBUG,
diff --git a/test/src/tsconfig.json b/test/src/tsconfig.json
index e5cfc09..15ac989 100644
--- a/test/src/tsconfig.json
+++ b/test/src/tsconfig.json
@@ -10,5 +10,9 @@
     "noEmitOnError": true,
     "strictNullChecks": true,
     "skipLibCheck": true
-  }
-}
\ No newline at end of file
+  },
+  "include": [
+      "../../src/typings.d.ts",
+      "**/*.ts"
+  ]
+}
```

Now I get the error `src/sub/code.ts(7,8): error TS2307: Cannot find module 'test-codemirror/lib/index.js'`.

**Comment by vidartf** [comment]
I have been able to fix the test repo with this, but my full project is still failing (different error now). I'll investigate some more, and see if I can reproduce the same errors in the test repo.

**Comment by vidartf** [comment]
Fixed, remaining issue is unrelated, will open a separate issue for it.

**Comment by vidartf** [comment]
Though it does seem strange to manually have to specify the file with `include` in tsconfig.json, as the typescript handbook [says](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html):

 > If the "files" and "include" are both left unspecified, the compiler defaults to including all TypeScript (.ts, .d.ts and .tsx) files in the containing directory and subdirectories except those excluded using the "exclude" property.

**Comment by vidartf** [comment]
Nevermind, those did not seem to actually be necessary, but rather the removal of the `exclude` in karma config was the critical point.
