### ISSUE TITLE
Running karma-typescript in Angular2 using TestBed throws "Platform with a different configuration has been created."

### ISSUE THREAD

**Issue by Bjeaurn** [monounity/karma-typescript#39]
Tried this with the @latest integration example as can be found here: 
https://github.com/monounity/karma-typescript/tree/master/integration-tests%40latest/src/angular2

Tried it in a semi clean "default" project (https://github.com/Bjeaurn/ng2-bootstrap/tree/karma-typescript-compat) with some adjustments in order to get karma-typescript working.

To reproduce:
- You can clone that into a directory. (https://github.com/Bjeaurn/ng2-bootstrap/tree/karma-typescript-compat)
- `npm install`
- `npm start` - verify it starts normally.
- `npm test`: Should crash on the TestBed error.

The error I'm receiving is: 
`Chrome 54.0.2840 (Mac OS X 10.12.1) ERROR
  Uncaught Error: A platform with a different configuration has been created. Please destroy it first.`

After some quick looking around, seems the TestBed configuration that Angular2 uses isn't compatible anymore with how karma-typescript handles the loading.

**Comment by monounity** [comment]
Well, you are bootstrapping two platforms, one in main.ts and another one in your test. I excluded main.ts from the test run and modified the test a bit:

```javascript
import { By } from "@angular/platform-browser";
import { DebugElement } from "@angular/core";
import { ComponentFixture, TestBed, async } from "@angular/core/testing";
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from "@angular/platform-browser-dynamic/testing";

import { AppComponent } from "./app.component";

describe("AppComponent", () => {

    TestBed.initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());

    let component: ComponentFixture<AppComponent>;

    beforeEach(async(() => {

        return TestBed
            .configureTestingModule({
                declarations: [AppComponent]
            })
            .overrideComponent(AppComponent, {
                set: {
                    template: "<div>foo</div>"
                }
            })
            .compileComponents()
            .then(() => {
                component = TestBed.createComponent(AppComponent);
            });
    }));

    it("should work", () => {
        expect(component).not.toBeUndefined();
    });
})
```
And it runs perfectly 👍

**Comment by monounity** [comment]
Oh, and if you want to load the template in the templateUrl instead of mocking it, you have to tell Karma to serve html files and with what url, using proxies:

```javascript
files: [
    { pattern: "node_modules/reflect-metadata/Reflect.js" },
    { pattern: "node_modules/zone.js/dist/zone.js" },
    { pattern: "node_modules/zone.js/dist/long-stack-trace-zone.js" },
    { pattern: "node_modules/zone.js/dist/proxy.js" },
    { pattern: "node_modules/zone.js/dist/sync-test.js" },
    { pattern: "node_modules/zone.js/dist/jasmine-patch.js" },
    { pattern: "node_modules/zone.js/dist/async-test.js" },
    { pattern: "node_modules/zone.js/dist/fake-async-test.js" },

    { pattern: "app/app.*.ts" },
    { pattern: "app/app.*.html" },
    { pattern: "app/errors/**/*.ts" },
    { pattern: "app/menu/**/*.ts" },
],
proxies: {
  "/app/": "/base/app/"
},
```
But then you have to deal with angular wanting to compile and load routing and custom tags in your test, ymmv.

**Comment by Bjeaurn** [comment]
How would you exclude the main.ts from the test run? By adding it as a file and adding `included: fase` or by adding it to the specific `excluded: []` list?

**Comment by Bjeaurn** [comment]
Maybe a bit of a separate discussion, but with the 'default' testing setup as provided by the Angular2 team, templates are automatically part of the compilation process (of course it'll need to find it, so you need either a `proxy`, a `map` and/or setup the pattern for it's files). But it doesn't require the you to setup the `TestBed` separately for every test, as this is part of the bootstrapping process. 

The upside of that is that you can get rid of the `async()` construction to start up your testing, and it cleans up your testing code quite a bit. 

Are you willing/planning to compare your solution with the way Angular2 setup their TestBed so maybe we could improve on some parts of testing automation in general?

**Comment by monounity** [comment]
There's no magic needed in the framework, just create a base class for the specs that pulls in the required modules and initiates the TestBed!

I've added an example project for Angular2 that uses a base class, check it out here: https://github.com/monounity/karma-typescript/tree/master/example-project@angular2

This makes the Karma config even simpler, which was my goal when I started this project, so thanks for this suggestion 👍
