### ISSUE TITLE
Custom Watermarks

### ISSUE THREAD

**Issue by ryanvall** [monounity/karma-typescript#404]
Hello! Is there currently a built in way to customize istanbul's [watermark](https://github.com/istanbuljs/nyc#high-and-low-watermarks) thresholds? I tried applying the configuration in a few places but didn't have any luck. In doing some digging through the source I believe it needs specified when constructing the [report context](https://github.com/monounity/karma-typescript/blob/master/packages/karma-typescript/src/karma/reporter.ts#L73) - which is passed into [istanbul-lib-report](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-lib-report/lib/context.js#L46).

If the above seems correct I can look into submitting a PR. Thanks for a great package!

**Comment by erikbarke** [comment]
Hey @ryanvall, a PR would be more than welcome!

**Comment by erikbarke** [comment]
@ryanvall, awesome!! 🚀
