### ISSUE TITLE
Since karma-typescript 5.3.0/Acorn 8.0.0 options.ecmaVersion is required

### ISSUE THREAD

**Issue by Stuk** [monounity/karma-typescript#409]
Thanks for the library! I noticed today when upgrading to karma-typescript 5.3.0 that I am getting the following warning in my build:

```
Since Acorn 8.0.0, options.ecmaVersion is required.
Defaulting to 2020, but this will stop working in the future.
```

It looks like it comes from this line, where the required option isn't specified:

https://github.com/monounity/karma-typescript/blob/9e7e8c18d724aedfaee7e8a79cde00198d430d15/packages/karma-typescript/src/bundler/validator.ts#L16

**Comment by alvachien** [comment]
Same here. Any updates?

**Comment by erikbarke** [comment]
5.4.0 is on npm now, fixing this issue 🚀
