### ISSUE TITLE
Publish Package Update for Karma 6.1

### ISSUE THREAD

**Issue by rxt30** [monounity/karma-typescript#433]
Currently the package can't be installed via `npm install --save-dev karma-typescript`, as the package doesn't have Karma 6.x as a valid dependency yet. The Dependency was already updated in commit 1f6cecf351fea4e2a11846decd4c14d9a25d6c66 ,  but the npm-package was not updated yet.

Is there a estimated release date for the package, or is there anything else that needs to be done before updating the package?

**Comment by erikbarke** [comment]
> or is there anything else that needs to be done before updating the package?

Nope, nothing to be done, 5.3.0 is on npm now 🚀 😄
