### ISSUE TITLE
Dependency Acorn 8.0.0 requires to be initialied with specific ecmaVersion

### ISSUE THREAD

**Issue by JanFellner** [monounity/karma-typescript#434]
We see a warning in the console when running karma.

```
Since Acorn 8.0.0, options.ecmaVersion is required.
Defaulting to 2020, but this will stop working in the future.
```

using 5.3.0

found this ticket:
https://github.com/monounity/karma-typescript/issues/409
which is merged to master and should be in 5.3.0?

**Comment by erikbarke** [comment]
Yeah, it was supposed to be in 5.3.0 but wasn't because I messed that release up... 5.4.0 is on npm now and I have verified that #427 is included ☺️
