### ISSUE TITLE
`require`d JSON breaks test

### ISSUE THREAD

**Issue by vidartf** [monounity/karma-typescript#45]
Having a line like 

```ts
const data = require('path/to/data.json');
```

will give an error during testing:

```
Chrome 55.0.2883 (Windows 10 0.0.0) ERROR
  Uncaught SyntaxError: Unexpected token m in JSON at position 2
  at http://localhost:9876/context.html:2
```

See test repo: https://github.com/vidartf/karma-ts-test/tree/json
Travis showing error: https://travis-ci.org/vidartf/karma-ts-test/jobs/182115047
Appveyor showing other error: https://ci.appveyor.com/project/vidartf/karma-ts-test/build/job/nbrb4s84k4ap2nta

**Comment by vidartf** [comment]
I saw `c4b9571f56d4715cce965d7566ef2a6151917fb5` now, and following the comments were able to load the JSON with the preprocessor. Unfortunately, it seems like the preprocessor adds a field `default` to the loaded JSON data, which should not be there.

**Comment by monounity** [comment]
I'm removing the stuff I added in c4b9571f56d4715cce965d7566ef2a6151917fb5, it was a bad idea... You'll be able to load the JSON without a special preprocessor, and the extra `default`should be gone too, the commonjs loader adds a bit of default export magic which JSON content doesn't need, it creates a cyclic dependency. I'm hoping I can commit the fix tomorrow morning!

**Comment by vidartf** [comment]
Ok. Final request though: It would be nice if it was possible to load JSON data from files whose filename does not have the `.json` file extension!

**Comment by vidartf** [comment]
Hmm. Nevermind the last one, as it seems that the normal `require` function might not be OK with that either.

**Comment by monounity** [comment]
Your test project works now with the latest from master, note that I've removed the JSON preprocessor, requiring JSON works automatically now!

**Comment by vidartf** [comment]
Thanks! Works well, also in my full project. Eagerly awaiting 2.1.5 👍
