### ISSUE TITLE
[karma-typescript-es6-transform] missing acorn dependency (transformer hangs in endless loop)

### ISSUE THREAD

**Issue by danielrentz** [monounity/karma-typescript#463]
While trying to setup tests with TypeScript, at one place I got an error about unexpected "import" statement telling me to try out karma-typescript-es6-transform. Doing so ends up in an unresponsive script. The node debugger reveals an endless loop in the Acorn Parser constructor. After further debugging I found that the transform script is using the wrong Acorn version (v7.4.1, installed due to other modules we are using in the project), instead of 8+ as intended after fixing #409 (passing the option `ecmaVersion:"latest"` results in this endless loop in Acorn v7, commit https://github.com/peterblazejewicz/karma-typescript/commit/ba3e9216e224d97fa8f56ad8feb1adaec2822a3e).

Root cause seems to be that the package.json of karma-typescript-es6-transform does not have acorn listed in its dependencies (but in devDependencies), so it requires just the one it finds in node_modules (which is v7 in our case).

Does not happen with the karma-typescript package which lists acorn in its package.json correctly.

**Comment by thw0rted** [comment]
@erikbarke as I commented on the other issue, I don't think the merged PR made it into a release yet.  I just spent the last hour digging through the mess that `npm`'s community has become (https://github.com/npm/npm/issues/2974, https://github.com/npm/npm-package-arg/pull/46, and on down the rabbit hole) to find that as far as I can tell, it is still not actually possible to install an NPM package from a `github:` source if it's in a monorepo (at least, without adding a bunch of postinstall script or using a third-party scraper website).
