### ISSUE TITLE
Angular 2 Component-Relative URL

### ISSUE THREAD

**Issue by fchiumeo** [monounity/karma-typescript#47]
Hello

Not working with Component-Relative URL in component decorators

```javascript
import { Component } from "@angular/core";

@Component({
    moduleId: module.id,
    selector: "app-footer",
    templateUrl: "footer.html"
})
export class Footer
{
}
```

```powershell
WARN [web-server]: 404: /footer.html
```

**Comment by erikbarke** [comment]
Hey @fchiumeo, this should work out of the box, have you included `.html`files in the Karma config?

If you look at the [Angular2 example](https://github.com/monounity/karma-typescript/tree/master/example-project@angular2), the Karma config includes html files:

```
{ pattern: "src/app/**/*.+(ts|html)" }
```
and uses a proxy to tell the Karma web server where to look for html files:

```
proxies: {
     "/app/": "/base/src/app/"
},
```

**Comment by fchiumeo** [comment]
yes, i'm settings this

```javascript
files: [
	"gulp/karma.shim.ts",
	"wwwroot/app/**/!(main|main-aot)*.+(ts|html)"
],
proxies: {
	"/wwwroot/app/": "/base/wwwroot/app/"
}
```

the problem is [module.id](https://github.com/monounity/karma-typescript/blob/master/lib/bundlers/builtin/commonjs.js#L11), not setting de filename in the property(example: http://localhost:9876/wwwroot/app/footer.js).

angular 2 example use absolute path, not relative

**Comment by erikbarke** [comment]
Ah, ok, I'll add support for relative urls and module.id!

**Comment by erikbarke** [comment]
Does it work for you if you install from the latest dev branch, `npm install https://github.com/monounity/karma-typescript.git#2.1.6`?

**Comment by fchiumeo** [comment]
Does not work in my project and neither in the example
I would have to set the url of karma and not the absolute path

example: c:/github/src/app/hello.ts => http://localhost:9876/app/hello.ts

absolute path cause error in zone.js
Error: More tasks executed then were scheduled(karma-typescript-bundle-8152p4lyxtRm2M7H.js:8813)

**Comment by erikbarke** [comment]
Ok, this is a windows path issue, I'll create a fix asap!

**Comment by erikbarke** [comment]
@fchiumeo, does it work with the latest from 2.1.6 now?

**Comment by fchiumeo** [comment]
:clap: :thumbsup:
now working perfectly !!!

thx
