### ISSUE TITLE
Use remap-istanbul from npm

### ISSUE THREAD

**Issue by talanta** [monounity/karma-typescript#5]
Hi
Would you pls change this dependency to target npm :
```json
// e.g
  "dependencies": {
  	.... 
    "remap-istanbul": "^0.6.4",
   }
```

Somehow, i cannot resolve github dependencies from npm install through corporate proxy.
Thanks !

**Comment by monounity** [comment]
@talanta, remap-istanbul 0.6.4 has an issue with inline source maps where the source folder structure is flattened.

The issuse is already solved (https://github.com/SitePen/remap-istanbul/issues/50) but 0.6.5 hasn't been published on npm yet, so I the github link in the dependencies as a temporary workaround.

I could try distributing the patched, non-released version from github with karma-typscript, which would solve the proxy problem for you.
