### ISSUE TITLE
request: v5.5.3 release

### ISSUE THREAD

**Issue by ryanio** [monounity/karma-typescript#507]
would it be possible to request a patch release (v5.5.3) with #502, we (ethereumjs-monorepo) would appreciate it as it would help our ci stay on latest typescript. related: #499

I was able to come up with this workaround https://github.com/ethereumjs/ethereumjs-monorepo/pull/1602#issuecomment-1008222864

Two challenges stemmed from the package-lock.json having typescript v3.9.9:
- Building with ts v4 failed with errors related to increased strictness of noImplicitAny
- It logged that it was compiling our code using v3.9.9, which failed on catch clause type declarations (which we've adopted in v4)

Other than that I was able to get it working though which is pretty cool when using a github ref of a package inside a monorepo, thanks to [gitpkg.now.sh](https://gitpkg.now.sh/)

I can help with a PR to update to typescript v4 if that sounds interesting to you as well. Otherwise a release with just #502 should fix our problem since typescript won't be installed as a devdep (I believe 🤔 ) is it even needed since it's already under peerDependencies?

**Comment by erikbarke** [comment]
Sure, I'll try to cut a release as soon as possible!

**Comment by ryanio** [comment]
thank you! 🙏

**Comment by erikbarke** [comment]
5.5.3 is on npm now 🎉
