### ISSUE TITLE
Acorn parser Ecmaversion doesn't follow Typescript target

### ISSUE THREAD

**Issue by acolytec3** [monounity/karma-typescript#520]
I wanted to raise this as it's not clearly documented anywhere and I'm not sure if it's a bug or some artifact of how `acorn` is used in the source-reader but wanted to explain the issue I came across and how we resolved it.

## Background
The [EthereumJS-Monorepo](https://github.com/ethereumjs/ethereumjs-monorepo) is configured as a monorepo using `npm workspaces` built in Typescript ~4.5 and we have a number of packages that depend upon one or more other packages within the monorepo. We are currently exploring upgrading our monorepo to an ES2020 build target.  In the process of upgrading one of the packages in our monorepo to use ES2020 syntax (bigints, nullish coalescing operators, etc), the karma tests broke in all of the other packages that depend on that package.

## The issue
Once one package was upgraded to use ES2020 syntax, `karma-typescript` began to produce these sort of errors when the browser tests were run n other packages that depended on the package recently upgraded to ES2020.
```
04 02 2022 19:29:03.458:INFO [compiler.karma-typescript]: Compiled 148 files in 9100 ms.
04 02 2022 19:29:04.302:ERROR [source-reader.karma-typescript]: Error parsing code: Unexpected token (119:37)
```
where the unexpected token was a `??` or else a bigint literal that appeared in the dependency package.

## The solution
After much googling and digging through source code, the ultimate solution is that we had to specify the ECMAScript target in the Acorn which karma-typescript uses to parse compiled Javascript in the `karmaTypescriptConfig` option within `karma.conf.js` as below in each package in the monorepo:
```
karmaTypescriptConfig: {
      tsconfig: './tsconfig.json',
      bundlerOptions: {
        entrypoints: /\.spec\.ts$/,
        acornOptions: {
          ecmaVersion: 11
        }
      },
    },
 ```

## Thoughts
I'm not 100% certain if this is a bug or not but one thing I did observe that makes me think it might be.  When we ran the browser tests through Karma in the package in the monorepo that was upgraded to ES2020, karma had no problem parsing the ES2020 syntax in the compiled javascript within that package.  It's only when it was parsing javascript from a dependency where we have to explicitly set the ECMAScript target for Acorn and it's not obvious to me why that is the case.  

I'm not easily able to produce a sample repo that reproduces this exact issue but I'm happy to provide a link to the commit in the current branch history in our monorepo where this issue can be reproduced.

All that to say, I'm not sure if this is a bug per se since it may just be a lack of documentation, in which case I'm happy to contribute a PR on some docs to spell this out a bit.  But, it does seem like it could be nice if the `source-reader` would default Acorn's ecmaVersion to whatever the target is specified in the `tsconfig` that the karmaTypescriptConfig option reads in if that particular option isn't specified (and the `acornOptions` key isn't identified in any of the docs at present.  I wouldn't have known it was there if I hadn't looked at Acorn first and then tracked back to the `karma-typescript` repo to see if any configs were passed to Acorn or not)

**Comment by erikbarke** [comment]
Hmm, this has been discussed before (#255 for example), maybe it's time to document this config option, so a PR would be nice!

**Comment by acolytec3** [comment]
> Hmm, this has been discussed before (#255 for example), maybe it's time to document this config option, so a PR would be nice!

Ah, I was obviously not using the right search terms.  Either way, will try to draft up a PR in the next day or two.  Thanks!
