### ISSUE TITLE
error when using enzyme

### ISSUE THREAD

**Issue by sir-marc** [monounity/karma-typescript#54]
Karma throws an error because enzyme requires 'react/addons'.

> ERROR [karma]: [Error: Cannot find module 'react/addons' from '[path to project]\node_modules\enzyme\build']

Before i had my karma runner using webpack and i defined the react/addons as externals like so:

```
webpackConfig.externals = { // Configuration required by enzyme
	jsdom: 'window',
	cheerio: 'window',
	'react/lib/ExecutionEnvironment': true,
	'react/lib/ReactContext': 'window',
	'react/addons': true,
};
```

but as I'm no longer using webpack in karma, how can I define those externals so enzyme runs?

Every hint is much appreciated

**Comment by erikbarke** [comment]
Hey @sir-marc, off the top of my head, there's a bundler setting you could start with, `karmaTypescriptConfig.bundlerOptions.ignoredModuleNames`:

```javascript
karmaTypescriptConfig: {
    bundlerOptions: {
        ignoredModuleNames: ["react/addons"]
    }
}
```

I'm in the midst of changing the behavior of the `ignoredModuleNames` property, it just skips the specified modules completely which might cause problems, instead I'm thinking it should skip parsing the module but include it in the bundle.

**Comment by sir-marc** [comment]
@erikbarke Thanks for the quick response.
Unfortunately adding this did not make any difference

**Comment by sir-marc** [comment]
Oh dear, thank you!
It really makes a difference! The problem was I got a very similiar error but pointing to `react/lib/ReactContext` instead of `react/addons`.

So I ended up with the following.
```
bundlerOptions: {
  ignoredModuleNames: [
    "react/addons",
    "react/lib/ReactContext",
    "react/lib/ExecutionEnvironment",
  ]
}
```

This error resolves but leads to another:

> PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
>   SyntaxError: Expected an identifier but found 'License' instead
>   at node_modules/react-addons-create-fragment/LICENSE:1

**Comment by sir-marc** [comment]
Found this one: I included non javascript files.
Now i get:

> TypeError: undefined is not an object (evaluating 'global['encoding-indexes'][name]')
  at %APPDATA%/Local/Temp/karma-typescript-bundle-90860DwQsE4IEh5jT.js:17968

**Comment by erikbarke** [comment]
Ah, the 'encoding-indexes' is a bundler bug, I'll try to create fix as soon as possible!

**Comment by sir-marc** [comment]
Is there something I can help you with?

**Comment by erikbarke** [comment]
Any help with debugging open issues is always welcome, just dig in 😃

**Comment by erikbarke** [comment]
In this case it was a one line fix! Does it work for you if you install from the latest dev branch, `npm install https://github.com/monounity/karma-typescript.git#2.1.6`?

**Comment by sir-marc** [comment]
I can't execute that command as I am behind a firewall. I think I need to wait until you publish this one.

**Comment by sir-marc** [comment]
@erikbarke I can confirm, this resolves the issue! Thank you so much.
I've downloaded the zip and installed it manually. I hope you can publish this change soon :)

**Comment by sir-marc** [comment]
I just tried this at home with you latest and the i get the no provider error.
If i then add karma-typescript to the plugins section it tells me more:

> 23 12 2016 18:20:36.935:ERROR [plugin]: Error during loading "karma-typescript" plugin:
  Cannot find module 'acorn'
23 12 2016 18:20:36.941:ERROR [preprocess]: Can not load "karma-typescript", it is not registered!
  Perhaps you are missing some plugin?
[path to project]\node_modules\karma\node_modules\di\lib\injector.js:9
      throw error('No provider for "' + name + '"!');

**Comment by erikbarke** [comment]
Doh, I have to add acorn as a dependency, you can solve this temporarily with `npm install acorn`!
