### ISSUE TITLE
TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by Wedvich** [monounity/karma-typescript#55]
I'm trying out karma-typescript for the first time, and I have a pretty vanilla setup in my karma.conf.js:

```js
module.exports = function (config) {
  config.set({
    autoWatch: true,
    colors: true,
    files: [
      { pattern: 'test/**/*.spec.ts' }
    ],
    frameworks: ['mocha', 'chai'],
    plugins : [
      'karma-mocha',
      'karma-chai',
      'karma-typescript'
    ],
    preprocessors: {
      '**/*.ts': ['karma-typescript']
    },
    reporters: ['progress', 'karma-typescript']
  });
};

```

However, this crashes right out of the gate with this error:

```
22 12 2016 07:18:47.301:ERROR [karma]: TypeError: Cannot read property 'options' of undefined
    at emit (C:\Repos\structured-log\node_modules\karma-typescript\lib\compiler.js:165:54)
    at C:\Repos\structured-log\node_modules\karma-typescript\lib\compiler.js:63:9
    at invokeFunc (C:\Repos\structured-log\node_modules\lodash.debounce\index.js:160:19)
    at trailingEdge (C:\Repos\structured-log\node_modules\lodash.debounce\index.js:207:14)
    at Timeout.timerExpired [as _onTimeout] (C:\Repos\structured-log\node_modules\lodash.debounce\index.js:195:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

I'm using the following versions:

- node 6.9.1
- typescript 2.1.4
- karma 1.3.0
- karma-typescript 2.1.5

Is this a bug, or have I misconfigured anything? From looking at the source, it seems as the crash happens when it tries to read the tsconfig. I do have a `tsconfig.json` present. I tried setting it explicitly through the `karmaTypescriptConfig` as well, but that didn't make any difference.

**Comment by erikbarke** [comment]
This looks like a windows paths issue, I'll try to reproduce the error!

**Comment by sir-marc** [comment]
What does your config look like? Could you post that aswell?
And how do you import it?

**Comment by erikbarke** [comment]
Well, that was one unhelpful error message if I ever saw one... Turns out `karma-typescript` is missing in the Karma config `frameworks` array:
```js
frameworks: ['mocha', 'chai', 'karma-typescript'],
``` 
I've added a framework check and a (hopefully) more helpful error message!

**Comment by Wedvich** [comment]
Thanks for the quick resolution! Adding karma-typescript to the `frameworks` array did the trick.
