### ISSUE TITLE
Cobertura coverage report is not coming with the extension

### ISSUE THREAD

**Issue by muthuramj** [monounity/karma-typescript#56]
Cobertura coverage report is not coming with the extension. Please provide the options to give subdir and filename for the reports.

**Comment by erikbarke** [comment]
Hey @muthuramj, I've added options for directory and filename, does it work for you if you install from the latest dev branch, `npm install https://github.com/monounity/karma-typescript.git#2.1.6`?
If you’re behind a firewall and can’t install from GitHub, you can download the branch as a zip and install manually.
