### ISSUE TITLE
Console coverage report

### ISSUE THREAD

**Issue by AlexVangelov** [monounity/karma-typescript#6]
How to configure a simple console report?
Thank you.

**Comment by AlexVangelov** [comment]
I found it,
by adding 

> karma-coverage

 and 
`coverageReporter: { type: "text-summary" }`

Easy to use package, nice work!

**Comment by erikbarke** [comment]
Hey, thanks!

I found and fixed a bug thanks to this issue, you should be able to add this to your config after the next release (v2.0.3):

    karmaTypescriptConfig: {
        reports:
        {
            "html": "coverage",
            "text-summary": ""
        }
    }

This will give you the html report and a console report with correct statistics for the remapped coverage:

    Statements   : 100% ( 15/15 )
    Branches     : 100% ( 0/0 )
    Functions    : 100% ( 5/5 )
    Lines        : 100% ( 11/11 )

The incorrect statistics created by `karma-coverage` (really not the fault of `karma-coverage` though, it's been fed transpiled and modularized javascript):

    Statements   : 100% ( 25/25 )
    Branches     : 66.67% ( 4/6 )
    Functions    : 100% ( 9/9 )
    Lines        : 100% ( 19/19 )

Cheers!

**Comment by AlexVangelov** [comment]
Perfect! And stats are adjusted.
