### ISSUE TITLE
Error when using a custom tsconfig.json

### ISSUE THREAD

**Issue by abdulhaq-e** [monounity/karma-typescript#60]
I get the following error when using a custom tsconfig.json:

```
05 01 2017 23:19:21.223:ERROR [karma]: Error: No source found for /data/workspace/ngrx-json-api/tests.bundle.ts!
Is there a mismatch between the Typescript compiler options and the Karma config?
    at /data/workspace/ngrx-json-api/node_modules/karma-typescript/lib/compiler.js:72:23
    at Array.forEach (native)
    at /data/workspace/ngrx-json-api/node_modules/karma-typescript/lib/compiler.js:66:19
    at invokeFunc (/data/workspace/ngrx-json-api/node_modules/lodash.debounce/index.js:160:19)
    at trailingEdge (/data/workspace/ngrx-json-api/node_modules/lodash.debounce/index.js:207:14)
    at Timeout.timerExpired [as _onTimeout] (/data/workspace/ngrx-json-api/node_modules/lodash.debounce/index.js:195:14)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

`tests.bundle.ts` is an exact copy of `base.spec.ts` which you provide in multiple examples. Here is my karma.config.js file: https://github.com/abdulhaq-e/ngrx-json-api/blob/coverage/karma.conf.js

**Comment by abdulhaq-e** [comment]
It's not really related to the custom config file. I removed it and added the following in `karmaTypescriptConfig`:

```
    compilerOptions: {
        "lib": [
          "dom", "es6"
        ]
      }
```
to get:

```
 No source found for /data/workspace/ngrx-json-api/node_modules/typescript/lib/dom.ts
05 01 2017 23:24:45.684:ERROR [karma]: TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/data/workspace/ngrx-json-api/node_modules/typescript/lib/typescript.js:8980:109)
    at parseSourceFileWorker (/data/workspace/ngrx-json-api/node_modules/typescript/lib/typescript.js:8940:26)
    at Object.parseSourceFile (/data/workspace/ngrx-json-api/node_modules/typescript/lib/typescript.js:8899:26)
    at Object.createSourceFile (/data/workspace/ngrx-json-api/node_modules/typescript/lib/typescript.js:8727:29)
    at getSourceFile (/data/workspace/ngrx-json-api/node_modules/karma-typescript/lib/compiler.js:205:25)
    at Object.compilerHost.getSourceFile (/data/workspace/ngrx-json-api/node_modules/karma-typescript/lib/compiler.js:169:20)
    at findSourceFile (/data/workspace/ngrx-json-api/node_modules/typescript/lib/typescript.js:45859:29)
    at /data/workspace/ngrx-json-api/node_modules/typescript/lib/typescript.js:45806:93
    at Object.forEach (/data/workspace/ngrx-json-api/node_modules/typescript/lib/typescript.js:1115:30)
    at processSourceFile (/data/workspace/ngrx-json-api/node_modules/typescript/lib/typescript.js:45806:34)
    at processRootFile (/data/workspace/ngrx-json-api/node_modules/typescript/lib/typescript.js:45694:13)
    at /data/workspace/ngrx-json-api/node_modules/typescript/lib/typescript.js:45175:25
    at Object.forEach (/data/workspace/ngrx-json-api/node_modules/typescript/lib/typescript.js:1115:30)
    at Object.createProgram (/data/workspace/ngrx-json-api/node_modules/typescript/lib/typescript.js:45174:24)
    at emit (/data/workspace/ngrx-json-api/node_modules/karma-typescript/lib/compiler.js:176:22)
    at /data/workspace/ngrx-json-api/node_modules/karma-typescript/lib/compiler.js:63:9
```

**Comment by erikbarke** [comment]
Hey @abdulhaq-e, does it work for you if you install from the latest dev branch, `npm install https://github.com/monounity/karma-typescript.git#2.1.6`?
If you’re behind a firewall and can’t install from GitHub, you can download the branch as a zip and install manually.

**Comment by sir-marc** [comment]
I have the exact same error but an other path:

> 01 02 2017 20:17:24.580:ERROR [compiler.karma-typescript]: No source found for path/to/project/node_modules/src/server/types.d.ts
01 02 2017 20:17:24.581:ERROR [karma]: [TypeError: Cannot read property 'length' of undefined]

I'am using version 2.1.7

**Comment by erikbarke** [comment]
Hey @sir-marc, long time no see! That path ending with `src/server/types.d.ts` inside node_modules looks suspicious, what does your tsconfig and Karma config look like?

**Comment by sir-marc** [comment]
Hey @erikbarke Yeah in the meantime everything went as expected, thank you so much for amazing this module!
my karma.conf.js
```
module.exports = function karmaConf(config) {
  config.set({
		basePath: '.',
    browsers: ['Chrome'],
    frameworks: ['mocha', 'chai', 'karma-typescript', 'sinon'],
    reporters: ['progress', 'karma-typescript'],
    files: [
      'src/**/*.tsx',
      'tests/**/*.spec.tsx',
    ],
    preprocessors: {
      'src/**/*.tsx': ['karma-typescript'],
      'tests/**/*.tsx': ['karma-typescript'],
    },

		karmaTypescriptConfig: {
			tsconfig: './tsconfig.json',
			exclude: ['stories/**/*.tsx'],		
			coverageOptions: {
				exclude: /\.(d|spec|test)\.tsx?/,
			},
			bundlerOptions: {
				//for enzyme
				exclude: [
					"react/addons",
					"react/lib/ReactContext",
					"react/lib/ExecutionEnvironment"
				]
			},
			//coverage
			reports: {
				"html": "coverage",
				"text-summary": "",
			},
		}
  });
};

```

and my tsconfig.json:
```
{
    "compileOnSave": true,
    "compilerOptions": {
        "outDir": "dist",
        "target": "es5",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "commonjs",
        "jsx": "react",
        "experimentalDecorators": true,
				"moduleResolution": "node",
				"lib": [
					"es6",
					"es2017",
					"dom",
					"scripthost"
				],
        "baseUrl": ".",
        "paths": {
          "js/*": ["src/js/*"],
          "interfaces/*": ["src/js/interfaces/*"],
          "elements/*": ["src/js/elements/*"],
          "commons/*": ["src/js/commons/*"],
          "style/*": ["src/assets/sass/*"]
        },
				"typeRoots": [
					"node_modules/@types/"
				]
    }
}

```

**Comment by erikbarke** [comment]
That config looks completely normal, could you run the tests with `logLevel: config.LOG_DEBUG` and post the logs here?

**Comment by sir-marc** [comment]
Yeah for me too. 
Is there a way to save the output to a file? 
As the log output is too long for the console?

**Comment by erikbarke** [comment]
Does piping the output to a text file, `karma start --single-run > log.txt` work for you?

**Comment by sir-marc** [comment]
[log.txt](https://github.com/monounity/karma-typescript/files/751840/log.txt)
Here you go, thank you

**Comment by erikbarke** [comment]
The path `C:/Users/marcb/Documents/coiffeur/coiffeurclient/node_modules/src/server/types.d.ts` seems to materialize out of thin air when the Typescript compiler attempts to read it. It looks like this is a dynamic require or similar where some path string concatenation has gone wrong, do you have any custom typings that get picked up by the compiler?

I've refactored the compiler to use the Typescript compiler API instead of rolling my own caching and file reading, does the problem go away if you install from the latest dev branch, `npm install https://github.com/monounity/karma-typescript.git#2.1.8`?

**Comment by sir-marc** [comment]
The error goes away but about 1 million new ones popup :S
[log.txt](https://github.com/monounity/karma-typescript/files/757609/log.txt)

**Comment by erikbarke** [comment]
You're excluding `"stories/**/*.tsx"` in the karma-typescript config, I think you need to add `node_modules` to that exclude. I'm not sure whether this is a configuration parsing bug or not, I'll investigate some more!

**Comment by sir-marc** [comment]
we are making progress, but now a strange redux error occurs. I am right excluding node_modules from karma-typescript? Or should I exclude it from karma itself, too? Or only there?
[log.txt](https://github.com/monounity/karma-typescript/files/758154/log.txt)

**Comment by sir-marc** [comment]
Sorry, i don't have either :S 
When i ran it, it also threw an error regarding redux/createStore.js could not be found, but I've no idea why. It works just fine and the files is there, too

**Comment by erikbarke** [comment]
Ok, so you don't have the `symbol-observable` and `assertion-error` modules, have you tried installing them manually? It's the code in `node_modules\redux\lib\createStore.js` that tries to require `symbol-observable`.
