### ISSUE TITLE
Possible to allow 'subdir' option for reports destination?

### ISSUE THREAD

**Issue by rfgamaral** [monounity/karma-typescript#63]
This package was a lifesaver, kudos :)

The current `karmaTypescriptConfig.reports` is not completely flexible and removes some functionality from the original option in `karma-coverage`, like `subdir`: https://github.com/karma-runner/karma-coverage#advanced-multiple-reporters

I'm trying to accomplish something like this: [karma-runner/karma-coverage#85](/karma-runner/karma-coverage/issues/85). The slight difference being that I don't need a "browser" folder, I just want my coverage to be stored exactly in the location I specify.

Is this possible?

**Comment by erikbarke** [comment]
Hey @rfgamaral, thanks for this suggestion!

I've added an option to specify a `subdirectory`:
```javascript
"cobertura": {
    "directory": "coverage",    // optional, defaults to 'coverage'
    "subdirectory": "cobertura" // optional, defaults to the name of the browser running the tests
    "filename": "coverage.xml", // optional, defaults to the report name
}
```

The above example should produce the path `./coverage/cobertura/coverage.xml`.

To try it out, install from the latest dev branch:`npm install https://github.com/monounity/karma-typescript.git#2.1.7`.
If you’re behind a firewall and can’t install from GitHub, you can download the branch as a zip and install manually.

**Comment by rfgamaral** [comment]
Amazing quick work, thank you so much for that. It's working nicely for me like this:

```javascript
html: {
    directory: path.join(__dirname, 'build', 'coverage'),
    subdirectory: '.',
    filename: '.'
}
```
All coverage output files are on the root of `/build/coverage`.

Feel free to close this :)
