### ISSUE TITLE
Karma Hangs Inside Docker Container

### ISSUE THREAD

**Issue by alecmerdler** [monounity/karma-typescript#64]
First of all, thank you for this package, it works much better than karma-webpack for testing TypeScript.

When running `karma` while building a Docker container, the process hangs after outputting `Resolved configFileJson`. Running locally, it looks like the next step is supposed to be `Resolved tsconfig`. I have confirmed that the `tsconfig.json` is in the project root inside the container.

Is there anything I am missing as to why it is hanging?

**Debug output from local machine:**
![screenshot_20170119_165816](https://cloud.githubusercontent.com/assets/11700385/22131514/d2ce12f4-de68-11e6-8cec-1595fa62171c.png)

**Debug output from inside Docker container:**
![screenshot_20170119_165843](https://cloud.githubusercontent.com/assets/11700385/22131530/eabf85c8-de68-11e6-8bed-e648a95cd29f.png)

**Comment by erikbarke** [comment]
Hey @alecmerdler, I'll try to reproduce the error!

**Comment by erikbarke** [comment]
I've added an [example project for Docker](https://github.com/monounity/karma-typescript/tree/2.1.7/example-project%40docker), but I can't reproduce this error, it just works... Does the example build and run on your machine?
