### ISSUE TITLE
Is it possible to have a single entry point and require test files manually?

### ISSUE THREAD

**Issue by rfgamaral** [monounity/karma-typescript#68]
Ok, I hope you don't mind but I have another question that given what you explained on #67, I don't think it's possible...

Say you have an app made of "components", "services" and "pages". Each component, service or page is a class and each have their test file. The idea here would be to manually require each of those test files in a specific order to have the tests run and print on the console in that order **so that they could be grouped into `describe` blocks**.

For instance:

**`IndexSpec.tsx`:**

```ts
describe("components", () => {
    // require all test files for components
});

describe("services", () => {
    // require all test files for services
});

describe("pages", () => {
    // require all test files for pages
});
```

Each test file would also have a `describe` block and the output (at least with `moch-reporter` would be something like this:

```
components
    button
        test description...
    panel
        test description...
services
    githubService
        test description...
    gitlabSerivce
        test description...
pages
    pageFoo
        test description...
    pageBar
        test description...
```

Is this even remotely possible with `karma-typescript`? Or is this already possible (or not) and doesn't have anything to do with `karma-typescript`?

**Comment by erikbarke** [comment]
`karma-typescript` has a specialized reporter that connects the transpiled Typescript code with `remap-istanbul`, it doesn't write anything to the console (other than a bit of debug logging). Off the top of my head I'd say that it should be possible and `karma-typescript` shouldn't get in your way, but I don't of a reporter capable of grouping tests like in your scenario.

**Comment by rfgamaral** [comment]
I'm not looking for a reporter capable of grouping tests like I described... I was just describing a way to force the testes to run in a certain order by chaining their execution through a single entry file. But I'm not sure how to do that because...

The gist of it would be to have a single entry point (a single file), either on `files` or `preprocessors` (if possible) and this file would require all other test files so that the tests execution would be made in the order of the require calls.

I know this is slightly out of scope but do you have any idea how could this be achieved? From a `karma-typescript` point of view, could I have a single entry point in the `files`/`preprocessors` property?

**Comment by erikbarke** [comment]
Ah, ok! I'm afraid this would take some work since `karma-typescript` relies on Karma for serving the files in the browser running the tests. One way to do it would be modifying the bundler to bundle everything in a single file, but again, that would require a bit of work...

**Comment by rfgamaral** [comment]
Understood. Take it as a low priority feature request then if you think it's something worth to implement or just close this :)

**Comment by erikbarke** [comment]
Closing it for now, but it's on my list of nice-to-have features!
