### ISSUE TITLE
Can't resolve imports using Advance Path configuration

### ISSUE THREAD

**Issue by michaeljota** [monounity/karma-typescript#72]
Sorry if this is duplicated, I tried to find this, but was unable.

I'm having troubles trying to resolve imports from the advance configuration, it is unable to do so.

Link to [Advance Path Resolution](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#module-resolution-enhancements-baseurl-path-mapping-rootdirs-and-tracing)

**Comment by erikbarke** [comment]
Hey @michaeljota, I don't think this is a duplicate! Do you have an example that works with `tsc` and fails with `karma-typescript`?

**Comment by michaeljota** [comment]
I just test this with [angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter), change an import to be from baseUrl, and it did not run. 

Also, lots of errors cause it does not find Promise (?). 

`APR error`
```cmd
26 01 2017 16:31:34.069:ERROR [compiler.karma-typescript]: src/app/home/home.component.ts(6,26): error TS2307: Cannot find module 'app/app.service'.`
```

**Comment by erikbarke** [comment]
What does your `karma.conf.js` and `tsconfig.json` look like? Does your project compile on the command line with `tsc`?

The errors about not finding "Promise" are likely fixed by installing typings for Node.js, for instance `@types/node`.

**Comment by michaeljota** [comment]
The `karma.conf.js` file is the same one you use from the Angular 2 example. Also the `spec.base.ts`. The `@types/node` are installed and listed in the package `devDependencies`. 

The project was not made to be compileable with tsc, but with Webpack. You can find the Webpack configuration in the project `config` folder. The Karma environment has its own `webpack.config` file.

**Comment by erikbarke** [comment]
Ok, I'll take a look!

**Comment by erikbarke** [comment]
The angular2-webpack-starter-pack project runs on my end with `karma-typescript`, kind of, I need to add support for relative urls in `templateUrl`. This plugin supports absolute template urls and relative template urls with module.id, but that doesn't work with webpack, see #69.

**Comment by erikbarke** [comment]
It works now, here are the steps:

```bash
git clone https://github.com/AngularClass/angular2-webpack-starter.git
cd angular2-webpack-starter
npm install
npm install --save-dev https://github.com/monounity/karma-typescript.git#2.1.8 karma-typescript-angular2-transform karma-typescript-es6-transform
```

Create the file `base.spec.ts` in the root of the `angular2-webpack-starter` project:

```js
import "core-js"
import "zone.js/dist/zone";
import "zone.js/dist/long-stack-trace-zone";
import "zone.js/dist/proxy";
import "zone.js/dist/sync-test";
import "zone.js/dist/jasmine-patch";
import "zone.js/dist/async-test";
import "zone.js/dist/fake-async-test";

import { TestBed } from "@angular/core/testing";
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from "@angular/platform-browser-dynamic/testing";

TestBed.initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());
```

Edit `./config/karma.conf.js` to look like this:

```js
module.exports = function(config) {
    config.set({

        frameworks: ["jasmine", "karma-typescript"],

        files: [
            { pattern: "base.spec.ts" },
            { pattern: "src/app/**/*.+(ts|html|css)" }
        ],

        exclude: [
            "src/app/app.e2e.ts",
            "src/app/home/home.e2e.ts",
        ],

        preprocessors: {
            "**/*.ts": ["karma-typescript"]
        },

        karmaTypescriptConfig: {
            bundlerOptions: {
                entrypoints: /\.spec\.ts$/,
                transforms: [
                    require("karma-typescript-angular2-transform"),
                    require("karma-typescript-es6-transform")()
                ]
            },
            compilerOptions: {
                noEmit: false,
                noEmitHelpers: false
            },
            tsconfig: "./tsconfig.json"
        },

        reporters: ["progress", "karma-typescript"],

        browsers: ["Chrome"]
    });
};
```

Edit `src/app/about/about.component.ts`and comment out the `setTimeout` bit in `asyncDataWithWebpack`:

```js
private asyncDataWithWebpack() {
    // you can also async load mock data with 'es6-promise-loader'
    // you would do this if you don't want the mock-data bundled
    // remember that 'es6-promise-loader' is a promise
    /*setTimeout(() => {

      System.import('../../assets/mock-data/mock-data.json')
        .then((json) => {
          console.log('async mockData', json);
          this.localState = json;
        });

    });*/
  }
```

Edit src/app/home/x-large/x-large.directive.spec.ts and change 
`import { By } from '@angular/platform-browser/src/dom/debug/by';` to
`import { By } from '@angular/platform-browser';`

Now run `npm test` and 10 tests should execute sucessfully 😃

Note: This example uses the new transforms API of the 2.1.8 dev branch of `karma-typescript` + beta versions of the new plugins `karma-typescript-angular2-transform` and `karma-typescript-es6-transform`, bleeding edge...
