### ISSUE TITLE
Able to run tests; no coverage report output

### ISSUE THREAD

**Issue by jfongp** [monounity/karma-typescript#73]
Hi. I am able to run my tests with karma by itself and with no errors using karma-typescript. Below is the output:

karma start karma.conf.js

26 01 2017 22:12:12.351:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.0.0
26 01 2017 22:12:20.901:INFO [karma]: Karma v1.4.0 server started at http://0.0.0.0:9876/
26 01 2017 22:12:20.909:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
26 01 2017 22:12:20.967:INFO [launcher]: Starting browser PhantomJS
26 01 2017 22:12:23.945:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket Gyol_ucV3QllLs7GAAAA with id 5289562
**PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 3 of 3 SUCCESS (0.143 secs / 0.315 secs)**

I was expecting a coverage folder after running but it doesn't exist.

karma.conf.js

`module.exports = function (config) {

  var appBase = 'Tests/transpiled/App/';       // transpiled app JS and map files
  var appSrcBase = 'App/';       // app source TS files

  var testingBase = 'Tests/transpiled/Tests/specs/'; // transpiled test JS and map files
  var testingSrcBase = 'Tests/specs/'; // test source TS files

  config.set({
    basePath: '..',
    frameworks: ['jasmine', "karma-typescript"],

    plugins: [
      require('karma-jasmine'),
      require('karma-chrome-launcher'),
      require('karma-phantomjs-launcher'),
      require('karma-jasmine-html-reporter'),
      require('karma-typescript'),
      require('karma-coverage')
    ],

    client: {
      builtPaths: [appBase, testingBase], // add more spec base paths as needed
      clearContext: false // leave Jasmine Spec Runner output visible in browser
    },

    customLaunchers: {
      // From the CLI. Not used here but interesting
      // chrome setup for travis CI using chromium
      Chrome_travis_ci: {
        base: 'Chrome',
        flags: ['--no-sandbox']
      }
    },

    files: [
      // System.js for module loading
      'node_modules/systemjs/dist/system.src.js',
      'node_modules/systemjs/dist/system-polyfills.js',

      // Polyfills
      'node_modules/core-js/client/shim.js',

      // zone.js
      'node_modules/zone.js/dist/zone.js',
      'node_modules/zone.js/dist/long-stack-trace-zone.js',
      'node_modules/zone.js/dist/proxy.js',
      'node_modules/zone.js/dist/sync-test.js',
      'node_modules/zone.js/dist/jasmine-patch.js',
      'node_modules/zone.js/dist/async-test.js',
      'node_modules/zone.js/dist/fake-async-test.js',

      // RxJs
      { pattern: 'node_modules/rxjs/**/*.js', included: false, watched: false },
      { pattern: 'node_modules/rxjs/**/*.js.map', included: false, watched: false },

      // Paths loaded via module imports:
      // Angular itself
      { pattern: 'node_modules/@angular/**/*.js', included: false, watched: false },
      { pattern: 'node_modules/@angular/**/*.js.map', included: false, watched: false },

      { pattern: 'Tests/systemjs.config.js', included: false, watched: false },
      { pattern: 'Tests/systemjs.config.extras.js', included: false, watched: false },
      'Tests/karma-test-shim.js', // optionally extend SystemJS mapping e.g., with barrels

      // transpiled application & spec code paths loaded via module imports
      { pattern: appBase + '**/*.js', included: false, watched: true },
      { pattern: testingBase + '**/*.js', included: false, watched: true },

      // Paths for debugging with source maps in dev tools
      { pattern: appSrcBase + '**/*.ts', included: false, watched: false },
      { pattern: appBase + '**/*.js.map', included: false, watched: false },
      { pattern: testingSrcBase + '**/*.ts', included: false, watched: false },
      { pattern: testingBase + '**/*.js.map', included: false, watched: false }
    ],

    exclude: [],
    proxies: {
        "/App/": "/base/App/"
    },
    preprocessors: {
        "Test/**/*.ts": ["karma-typescript"]
    },
    reporters: ['progress', 'kjhtml', "karma-typescript"],

    karmaTypescriptConfig: {
        reports:
        {
            "cobertura": {
                "directory": "./coverage",
                "filename": "coverage.xml",
                "subdirectory": "cobertura"
            },
            "html": "coverage",
            "text-summary": ""
        },
        "compilerOptions": {
            "baseUrl": ".",
            "target": "es5",
            "module": "system",
            "moduleResolution": "node",
            "sourceMap": true,
            "emitDecoratorMetadata": true,
            "experimentalDecorators": true,
            "removeComments": false,
            "noImplicitAny": false,
            "noEmitOnError": true
        }
    },
    coverageReporter: {
        instrumenterOptions: {
            istanbul: { noCompact: true }
        }
    },
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['PhantomJS'],
    singleRun: true
  })
}
`

Any help is appreciated. Thanks!

**Comment by erikbarke** [comment]
Hey @jfongp, does it work if you include all `.ts` files in the preprocessor?

```js
preprocessors: {
    "**/*.ts": ["karma-typescript"]
},
```

It looks like only the tests are included, not the files that are tested.

**Comment by jfongp** [comment]
Hi @erikbarke, I did that and got errors like "error TS2307: Cannot find module 'Core/Services/user'." I think the tsconfig used by karma-typescript is different than the one used in my App folder. Here's my project structure:

root
   |_____ App (contains tsconfig, baseUrl = ".")
   |_____Tests (contains tsconfig, baseUrl = "..")
               |___ specs
               |___ transpiled
                             |______  App
                             |______ Tests
                                           |_____ specs

tsconfig in App folder:

`
{
  "compilerOptions": {
    "baseUrl": ".",
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "noEmitOnError": true,
	"outDir": "../wwwroot/app"
  },
  "compileOnSave": true
}
`

tsconfig in the Tests folder:
`
{
  "compilerOptions": {
    "baseUrl": "../",
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "noEmitOnError": true,
    "outDir": "./transpiled",
    "types": [ "core-js" ]
  },
  "compileOnSave": true
}
`

Am I allowed to only have one tsconfig when I use karma-typescript? Thanks!

**Comment by erikbarke** [comment]
You can point to any `tsconfig.json` you want from `karmaTypescriptConfig.tsconfig` and then add to/override options using `karmaTypescriptConfig.compilerOptions!

**Comment by jfongp** [comment]
@erikbarke , the problem I am having is that I need two different baseUrls. If I point to the tsconfig in the App folder, I can't really override the baseUrl because I really need the one in the Tests folder as well. Am I misunderstanding this? Thanks!

**Comment by erikbarke** [comment]
Do you need two different baseUrls at the same time when compiling your project?

**Comment by jfongp** [comment]
@erikbarke, I did but I have restructured the code base. Now it's working! Thanks!
