### ISSUE TITLE
Need help. Can't set up karma-typescript with Typescript React project

### ISSUE THREAD

**Issue by paibamboo** [monounity/karma-typescript#75]
Hello. 
I've been trying to set up karma-typescript with the [React Boilerplate from Vortigern](https://github.com/paibamboo/vortigern). To start from the basic, I just used the sample configuration below.

![with_karma-typescript_code](https://cloud.githubusercontent.com/assets/13611391/22418706/bfc9ec30-e70c-11e6-8b47-63de5dc89689.png)

But the error is like it doesn't understand typescript syntax.

![with_karma-typescript_cmd](https://cloud.githubusercontent.com/assets/13611391/22418788/0b737d5e-e70d-11e6-8a84-d406ed71056d.png)

I tried removing karma-typescript-related from the config like so.

![without_karma-typescript](https://cloud.githubusercontent.com/assets/13611391/22418910/a13431f8-e70d-11e6-993a-fb0b5996540a.png)

And the error is still the same. As if karma-typescript has no effect at all?

![without_karma-typescript_cmd](https://cloud.githubusercontent.com/assets/13611391/22418928/b8380bb8-e70d-11e6-9efd-2ea60cd772c1.png)

Please help. What am I missing?

**Comment by erikbarke** [comment]
Hey @paibamboo, you need to include `.tsx` files instead of `.ts` in the Karma file and preprocessor sections!

**Comment by paibamboo** [comment]
@erikbarke I tried that too, still the same error.

**Comment by erikbarke** [comment]
Ok, here's how I got it up and running:

Install the latest dev branch:
`npm install https://github.com/monounity/karma-typescript.git#2.1.8`

Issues:
- `../build/manifest.json` in `src/server.tsx` doesn't seem to exist, I replaced that require with `const manifest = "{}";`
- I had to install `@types/es6-promise`, the Typescript compiler complains about `Cannot find name 'Promise'`otherwise
- `react-router@3.0.2` needs `history@3.0.0` but `history@4.5.1` gets pulled in, they're not compatible so I had to manually install `history@3.0.0`

The Karma config:

```js
module.exports = function(config) {
    config.set({

        frameworks: ["mocha", "karma-typescript"],

        basePath: "../../",

        files: [
            { pattern: "node_modules/es6-shim/es6-shim.js" }, // needed for PhantomJS
            { pattern: "src/**/*.+(ts|tsx)" }
        ],

        preprocessors: {
            "**/*.+(ts|tsx)": ["karma-typescript"]
        },

        karmaTypescriptConfig: {
            bundlerOptions: {
                entrypoints: /\.test\.tsx$/,
                exclude: [
                    // dynamic requires or stuff that breaks PhantomJS
                    "node-pre-gyp",
                    "react/addons",
                    "react/lib/ExecutionEnvironment",
                    "react/lib/ReactContext",
                    "send",
                    // webpack stuff, can be removed if webpack imports are removed from dev setup
                    "../config/webpack/dev",
                    "webpack",
                    "webpack-manifest-plugin"
                ]
            },
            compilerOptions: {
                target: "ES5"
            },
            tsconfig: "tsconfig.json"
        },

        reporters: ["progress", "karma-typescript"],

        browsers: ["PhantomJS"]
    });
};

```

This runs 12 tests and creates coverage successfully 😃

**Comment by paibamboo** [comment]
Wow nice. Thanks a lot :D

**Comment by paibamboo** [comment]
@erikbarke Sorry to disturb again. When I install @types/es6-promise, karma-typescript runs fine. But I cannot run the project using "npm run start" anymore. It complains that 'Promise' is duplicated. From the error apparently Typescript has a library named Promise already. 

![dup_promise](https://cloud.githubusercontent.com/assets/13611391/22732540/17433280-ee21-11e6-8991-cec9da1207eb.png)

Seems like compilerOptions.target is the cause? Because when I set target to es6 (same as tsconfig), the error about duplicated Promise is gone, instead another error about typescript syntax appeared. 

![syntax_error](https://cloud.githubusercontent.com/assets/13611391/22733077/10989f4a-ee23-11e6-9d87-b008c830068f.png)

**Comment by erikbarke** [comment]
Ok, I've edited my previous answer: you have to `npm uninstall @types/es6-promise` and add `lib: ["es2015", "dom"]` to the karmaTypescriptConfig.compilerOptions instead, with that configuration I was able to run both `npm run start` and `npm test` successfully!

**Comment by paibamboo** [comment]
It works. Thanks Eric. Is the es2015 lib that karma-typescript uses the one in node_modules/typescript/lib or it has its own lib somewhere else? And is `lib` a hidden config? I don't see it in https://github.com/monounity/karma-typescript.

**Comment by erikbarke** [comment]
The `lib`option is a [Typescript compiler option](https://www.typescriptlang.org/docs/handbook/compiler-options.html), `karma-typescript`just passes the values of `karmaTypescriptConfig.compilerOptions` to the Typescript API!

**Comment by paibamboo** [comment]
My bad :P

**Comment by erikbarke** [comment]
No worries 😃
