### ISSUE TITLE
How to keep .js / .map.js files for debug in browser?

### ISSUE THREAD

**Issue by DaneGrinder** [monounity/karma-typescript#76]
Hi.

Just a quick question here. I'm sure it's a stupid one, but hope you guys can bear with me :-)

How do you guys debug in the browser, when the .js and .map.js files gets deleted, before you can serve them up to a browser?

Is there a setting that will serve them up through the already running (test) server?

**Comment by erikbarke** [comment]
Hey @DaneGrinder, are you running Karma with `autoWatch: true`? If so, you should be able to click the big debug button in the top right corner of the browser and, for instance in Chrome, open the developer tools and debug the transpiled javascript code!

**Comment by DaneGrinder** [comment]
Hi @erikbarke . First of, thank you so much for answering :-)

I'm completely new to TDD, so my normal work flow is, that my app is served up (index.html), by a simpel webserver, and open in 1 or more browsers. TSC -watch, live-reload in the browser and just using the Chrome debugger. I'm 100% depending on the dev tools in the browser for debugging. How do one debug in the TDD paradigme, if you never see the actual output of your code? (serving up the html and debugging the ts (js).)

I'm running it with autowatch yes, and I can see the code in the dev tools. But not seeing the actual output rendered in the DOM, kind of confuses me :-) My code could pass all tests and so on, but not actual give the correct output in the DOM. Like not drawing the correct shapes etc on a canvas element. Or maybe that's just me being old school here, and not feeling ready to trust output "I haven't actually seen" :-D

**Comment by erikbarke** [comment]
Ah, this is the nature of unit testing, you programmatically test the logic behind (for instance) a button on a form, you don't actually press the button in the GUI to see what happens. If you want to automate testing the GUI, have you tried tools for integration testing and end to end testing (e2e) like [Selenium](http://www.seleniumhq.org), [Protractor](http://www.protractortest.org/#/) etc?

**Comment by DaneGrinder** [comment]
:-) yeah, I probably just have to get used to it. All new things are hard.

I might not have chosen the best project to start out with. I'm rendering animations on a canvas, generated from attributes set on the canvas, parameters fetched from a server, and built in default fall back values. That's a stream of hundreds of animation frames, and in theory, I could probably test each of them, but I still wouldn't actually know, if the animations look and "feel" exactly the way I want them too :-)

That Selenium looks awesome. Defiantly going to look into that 👍 

Thanks a lot for taking time off to help a TDD noob getting started.

Have a great day

**Comment by erikbarke** [comment]
No problem, happy TDD'ing :smile:
