### ISSUE TITLE
Polyfills are sometimes not loaded

### ISSUE THREAD

**Issue by Necroskillz** [monounity/karma-typescript#77]
I noticed that sometimes browser would throw an error when executing tests (using `base.spec.ts` as from your `angular2` example project):

```
 ReferenceError: Can't find variable: Map
```
```
 ReferenceError: Can't find variable: Zone
```

One run the error is there, next run (without changing the source) it runs OK. Makes me think there is some kind of race condition where the angular code starts executing but the polyfills are not loaded yet. 

My OS is win 10, and I also (sometimes) have this issue with just running tests on the example project.

Putting the files directly into karma `files` seems to solve this issue, but of course is not as nice as just importing it.

```
        files: [
            'node_modules/core-js/client/core.js',
            'node_modules/zone.js/dist/zone.js',
            'node_modules/zone.js/dist/long-stack-trace-zone.js',
            'node_modules/zone.js/dist/proxy.js',
            'node_modules/zone.js/dist/sync-test.js',
            'node_modules/zone.js/dist/jasmine-patch.js',
            'node_modules/zone.js/dist/async-test.js',
            'node_modules/zone.js/dist/fake-async-test.js',
            { pattern: 'base.spec.ts' },
            { pattern: 'src/app/**/*.+(ts|html)' }
        ],
```

I see that you have several builds failing because of this on CI server, so I guess you already know about this -.- Do you have any solution?

**Comment by erikbarke** [comment]
Yeah, I managed to track down this bug a few days ago, the entrypoints get added in a random order last in the bundle file causing race conditions, I'm working on a fix, thanks for reporting!

**Comment by erikbarke** [comment]
@Necroskillz, I've checked in a fix which passed the build on Travis (the Appveyor build is really flaky, the Karma browser launcher crashes almost every time...)!

Does it work for you if you install from the latest dev branch, `npm install https://github.com/monounity/karma-typescript.git#2.1.8`?
If you’re behind a firewall and can’t install from GitHub, you can download the branch as a zip and install manually.

**Comment by Necroskillz** [comment]
looks good, I ran the tests a few times and they passed every time.

**Comment by erikbarke** [comment]
Ok, closing!

**Comment by damirkusar** [comment]
Can you publish 2.1.8 to NPM?

**Comment by erikbarke** [comment]
Hey @damirkusar, I'm afraid the 2.1.8 branch isn't in a releasable state just yet, but I'm hoping to publish on npm within a few weeks 😃

**Comment by damirkusar** [comment]
Hi @erikbarke, Thanks for your response, keep going :D
I also having another problem, after updating TS, when installing the core-js typings, TS has trouble to start up.. when not having the typings installed, then karma-typescript complains about not having it and having no definition for export symbol.. I know it is very vague currently, will prepare next week something so that you could reproduce it, but not sure if it is within you :)
