### ISSUE TITLE
Incorrect coverage %

### ISSUE THREAD

**Issue by jfongp** [monounity/karma-typescript#78]
Hi, I only have two unit tests which test a few lines of the code base. For some reason, I am getting a lot of coverage for code that is not tested directly or indirectly. For example, I have a Angular 2 routing module that is never tested and is showing 100% coverage. Is there something up with my karma conf? Thanks!

![image](https://cloud.githubusercontent.com/assets/17488920/22518034/c3d48eba-e870-11e6-8433-6398b9acb17a.png)

`module.exports = function(config) {
    config.set({

        frameworks: ["jasmine", "karma-typescript"],

        files: [
			// System.js for module loading
			'node_modules/systemjs/dist/system.src.js',
			'node_modules/systemjs/dist/system-polyfills.js',

			// Polyfills
			'node_modules/core-js/client/shim.js',

			// zone.js
			'node_modules/zone.js/dist/zone.js',
			'node_modules/zone.js/dist/long-stack-trace-zone.js',
			'node_modules/zone.js/dist/proxy.js',
			'node_modules/zone.js/dist/sync-test.js',
			'node_modules/zone.js/dist/jasmine-patch.js',
			'node_modules/zone.js/dist/async-test.js',
			'node_modules/zone.js/dist/fake-async-test.js',
			
			'node_modules/reflect-metadata/Reflect.js',
	  
            { pattern: "App/coverage-base.spec.ts" },
			// need to exclude the boot file or it would throw an error
            { pattern: "App/**/!(boot).+(ts|html)" }
        ],

        proxies: {
            "/App/": "/base/App/"
        },

        preprocessors: {
            "App/**/*.ts": ["karma-typescript"]
        },
		
		//logLevel: config.LOG_DEBUG,
		
        reporters: ["progress", "karma-typescript"],

		karmaTypescriptConfig: {
			reports: {
				"cobertura": {
					"directory": "Coverage",
					"filename": "cobertura/coverage.xml"
				},
				"html": "Coverage",
				"text-summary": ""
			},
			tsconfig: "./App/tsconfig.json",
			exclude: ["node_modules/**/*", "wwwroot/**/*"]
		},
		browsers: ["Chrome"],
		singleRun: true
    });
};
`

My tsconfig file:

`{
  "compilerOptions": {
    "baseUrl": ".",
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "noEmitOnError": true,
	"suppressImplicitAnyIndexErrors": true,
	"types": [
		"jasmine",
		"core-js",
		"node",
		"lodash"
	]
  },
  "compileOnSave": true    
}`

**Comment by erikbarke** [comment]
Hey @jfongp, could you run the tests with `logLevel: config.LOG_DEBUG` and post the logs here?

**Comment by jfongp** [comment]
@erikbarke , here's the log file. Really hope to use this tool in our project. Very useful!
[log.txt](https://github.com/monounity/karma-typescript/files/746400/log.txt)

**Comment by jfongp** [comment]
@erikbarke , looking through the coverage, I noticed that statements such as imports, export class, constructor, annotations such as '@injectable()' are counted as "covered statements" by default, even there is no spec against it. Is this by design? I thought those lines would be excluded.

Maybe I am not understanding coverage correctly.

**Comment by jfongp** [comment]
@erikbarke thanks for your quick response! I guess maybe when I use TestBed to start testing, the initialization of components that have no specs also get constructed. which would run the lines you mentioned above? If I run isolated unit tests instead of Angular components test, those lines would probably not be hit. 

Thanks for the explanation and creating this great tool! Keep up the good work! :D

**Comment by netzzwerg** [comment]
Hello, I have nearly the same problem and I can reproduce it inside the `karma-typescript/example/mocha` example. I removed  2 lines from the `hello.component.spec.ts` like this: 

    import { HelloService } from "./hello-service.interface";
    import { HelloComponent } from "./hello.component";

    class MockHelloService implements HelloService {

        public sayHello(): string {
            return "Hello world!";
        }
    }

    describe("HelloComponent", () => {

        it("should say 'Hello world!'", () => {

            //let mockHelloService = new MockHelloService();
            //let helloComponent = new HelloComponent(mockHelloService);

            expect(true).to.be(true);
        });
    });

so coverage should be nearly zero. And I added this:

    karmaTypescriptConfig: {
        reports: {
            "html": "coverage",
            "text": ""
        }
    },
to the `karma.conf.js` to get the command line report. This is the result, which looks wrong for me:

![console](https://cloud.githubusercontent.com/assets/186091/26644518/468c7daa-4635-11e7-9a45-7e582f16a8de.png)

Thank you!

**Comment by erikbarke** [comment]
@netzzwerg, I made the same changes and got the same results as you, but I think the results are correct in this case: Typescript interfaces are erased when compiling, creating a more or less empty vanilla javascript file.

All files added to the Karma file list are by default considered entry points (this is configurable) and will be executed by the bundler in a `commonjs` wrapper on each test run. Since each file is executed, each interface will also be executed and visited by the coverage tool which sees that every line has been executed, which means it has 100% coverage.

If you look at the html report for `hello.component.ts`, you'll see that neither the `constructor` nor the function `sayHello()` have any hits at all, so I believe this is correct 😃

If you don't want this behavior, the bundler options has a regex for filtering entrypoints, `karmaTypescriptConfig.bundlerOptions.entrypoints`.

**Comment by netzzwerg** [comment]
Problem solved. Thank you @erikbarke! After adding the `karmaTypescriptConfig.bundlerOptions.entrypoints`  to the `karma.conf.js` config like this:
```javascript
karmaTypescriptConfig: {
  bundlerOptions: {
    entrypoints: /\.spec\.ts$/
  }
}
```
 to use the `spec.ts` test file as entry point the coverage changed from this
```
-----------------------------|----------|----------|----------|----------|---------------
File                         |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines
-----------------------------|----------|----------|----------|----------|---------------
 src/                        |    71.43 |      100 |    33.33 |       80 |             
  hello-service.interface.ts |      100 |      100 |      100 |      100 |            
  hello.component.ts         |    71.43 |      100 |    33.33 |       80 |              9
-----------------------------|----------|----------|----------|----------|---------------
All files                    |    71.43 |      100 |    33.33 |       80 |             
-----------------------------|----------|----------|----------|----------|---------------
```
to this:
```
-----------------------------|----------|----------|----------|----------|---------------
File                         |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines
-----------------------------|----------|----------|----------|----------|---------------
 src/                        |    14.29 |      100 |        0 |       20 |               
  hello-service.interface.ts |      100 |      100 |      100 |      100 |               
  hello.component.ts         |    14.29 |      100 |        0 |       20 |       3,7,9,11
-----------------------------|----------|----------|----------|----------|---------------
All files                    |    14.29 |      100 |        0 |       20 |               
-----------------------------|----------|----------|----------|----------|---------------
```
