### ISSUE TITLE
Can not load karma-typescript, it is not registered

### ISSUE THREAD

**Issue by Duskfall** [monounity/karma-typescript#8]
For versions 2.0.4 and 2.0.5 i get this error when starting karma
![image](https://cloud.githubusercontent.com/assets/2528125/18543485/c63358e4-7b38-11e6-98fc-57a6cbbac0dd.png)

This doesn't happen for versions <= 2.0.3

Also if I change the files and have autowatch :true , the files aren't loaded anew but stay the same, so i need to close the karma and rerun it

Thanks!

**Comment by monounity** [comment]
@Duskfall, do you have the package `source-map` in the node_modules folder? It looks like it doesn't get pulled in by npm. Also could you post your karma config here? Thanks :)

**Comment by Duskfall** [comment]
@monounity Yes I have both source-map and source-map-support in node_modules!

karma.conf:

````
module.exports = function (config) {
    config.set({
        basePath: './',
        files: [
            './Scripts/Libs/angular/angular.min.js',
            './Scripts/Libs/angular-mocks/angular-mocks.js',
            './Scripts/**/**.ts',
            './Scripts/UnitTests/Tests/Controllers/**.ts',
            './Scripts/UnitTests/Tests/Services/**.ts'
        ],
        exclude: [],
        frameworks: [
            "jasmine", "karma-typescript"
        ],
        reporters: ['progress'],
        karmaTypescriptConfig: {
            reports:
            {
                "html": "coverage",
                "teamcity": "coverage",
            },
            remapOptions:
            {
                // Regex or string for excluding files, the example below is default
                exclude: /(typings|Interfaces|Libs)/,
                // Function for warning messages, these warnings are silent by default
                warn: function (message) { }
            }
        },
        preprocessors: {
            "**/*.ts": ["karma-typescript"]
        },
        browsers: ['Chrome'],
        autoWatch: true,
        singleRun: false,
    });
};

I also give you the file structure with the node_modules loaded:

[tree.txt](https://github.com/monounity/karma-typescript/files/476273/tree.txt)

**Comment by monounity** [comment]
Great, I'll try to reproduce the bug!

**Comment by monounity** [comment]
I can reproduce the problem and it looks like an older version of `source-map` gets pulled in by another package. Does the problem go away if you install it manually, ie `npm install source-map`?

If so, I'll fix the problem by adding the dependencies for the bundled version of `remap-istanbul` package.json.

**Comment by Duskfall** [comment]
Yes indeed it works! Both bugs seem to be resolved with the newest source-maps. Much appreciated @monounity thanks
