### ISSUE TITLE
Error: No source found 

### ISSUE THREAD

**Issue by pat154** [monounity/karma-typescript#82]
Hi, first of all, thanks for the great Karma plugin.

I've been using this successfully for a while until out of the blue I've begun to get this error when trying to run tests. I haven't been able to resolve it, even after reading about the other people that have reported the same issue on here so I thought I would reach out for help here.

Here is my karma.conf.js: [http://pastebin.com/xPXWh2Y0](http://pastebin.com/xPXWh2Y0)
Here is the output I get when trying to run tests: [http://pastebin.com/7qjq2p8U](http://pastebin.com/7qjq2p8U)

I'm using the latest karma-typescript version: 2.1.7 and typescript version 2.0.3.

My setup was working perfectly at one stage in it's own branch. I just recently came back to the branch with no changes at and it was suddenly breaking.

Any help you can give me would be really appreciated!

**Comment by erikbarke** [comment]
Hey @pat154, this is the same problem as in #71, case sensitive filenames! It looks like the file "Src/ts/services/Config**s**ervice.ts" has a lowercase "s" on disk vs "Src/ts/services/Config**S**ervice.ts" in your code.

**Comment by pat154** [comment]
Thanks! You were right! I had seen that issue before and checked my paths but a couple had slipped through the cracks!
