### ISSUE TITLE
How to use es6 library

### ISSUE THREAD

**Issue by Necroskillz** [monounity/karma-typescript#87]
Hi,

I wanted to use `lodash-es` in my angular 2 project, but (understandably as it is es6 only package), it fails with `Error: Invalid syntax in bundle: 'import' and 'export' may only appear at the top level`. This package works well with typescript, rollup and webpack, so it would be nice to be able to use it.

Is there any way to use such libraries with karma-typescript?

**Comment by fchiumeo** [comment]
How are you configured karma and tsconfig ?

**Comment by Necroskillz** [comment]
no special settings for this.

Here is how you can reproduce (in example-project@angular2 for example):

- `npm i -D lodash-es @types/lodash-es`
- (src/app/hello.ts) `import forEach from 'lodash-es/forEach';`
- `npm test`

**Comment by erikbarke** [comment]
Hey @Necroskillz, to make this work you would need to run `lodash-es` through, for instance, [Babel](https://github.com/babel/babel) which will be possible with some new features I'm currently working on, see #69, #72, #66.

**Comment by kevindqc** [comment]
I have the same problem with `@ngrx/effects`.

The part that triggers the problem:
I'm having a similar problem:
`
09 02 2017 17:25:55.529:ERROR [karma]: Error: Invalid syntax in bundle: 'import' and 'export' may only appear at the top level (104970:196) in C:\Users\KDoyon\AppData\Local\Temp\karma-typescript-bundle-22760MK8oQfzjJJPT.js
`

Looking at line 104970 in the bundle, it is:

```
global.wrappers['node_modules/@ngrx/effects/testing/index.js']=[function(require,module,exports,__dirname,__filename){ export * from './runner';
export * from './testing.module';

},'node_modules/@ngrx/effects/testing/index.js',{}];
```

**Comment by erikbarke** [comment]
@kevindqc, check my answer in #69!

**Comment by Safiyya** [comment]
Glad to see someone with the same issue @Necroskillz ! I was pulling my hair out with `d3-ng2-service` (from `https://github.com/tomwanzek/d3-ng2-service`).

These steps 
- `npm install d3-ng2-service`
- `import { D3Service } from 'd3-ng2-service';` in `src/app/hello.ts`
- `npm test` 

give me `Error: Invalid syntax in bundle: 'import' and 'export' may only appear at the top level`

**Comment by erikbarke** [comment]
@Safiyya, thanks for your input, I'll add that as a test case when I develop this new feature!

**Comment by erikbarke** [comment]
Hey guys, `karma-typescript` now have a plugin API for transforming source code in the bundling step and one of the first plugins is [karma-typescript-es6-transform](https://github.com/monounity/karma-typescript-es6-transform). The configuration is dead simple:

```bash
$ npm install --save-dev karma-typescript-es6-transform
```

```js
karmaTypescriptConfig: {
    bundlerOptions: {
        transforms: [
            require("karma-typescript-es6-transform")()
        ]
    }
}
```

I've added an [integration test](https://github.com/monounity/karma-typescript/tree/2.1.8/tests/integration-latest/src/bundling/transforms) using the npm packages reported in this thread that passes on Travis and Appveyor 😃

**Comment by Safiyya** [comment]
Sounds great, will try it this week and come back to you. Thanks !

**Comment by Safiyya** [comment]
Works like a charm, problem solved with `npm install --save-dev https://github.com/monounity/karma-typescript.git#2.1.8`. Cheers :)

**Comment by erikbarke** [comment]
@Safiyya, awesome!!

**Comment by erikbarke** [comment]
3.0.0-beta.1 is on npm now with support for ES6!

`npm install karma-typescript@beta`
`npm install karma-typescript-es6-transform@latest`

(2.1.8 ended up having so much new functionality + breaking changes it was renamed to 3.0.0)

**Comment by StevenLiekens** [comment]
@erikbarke  Excuse me if this is a dumb question but why would you use Babel with TypeScript? The TypeScript compiler already has the ability to lower ES6 imports/exports to something else.

https://www.typescriptlang.org/docs/handbook/modules.html#code-generation-for-modules

Anyway this is something that should just work with a default install of karma-typescript, without additional plugins or config. It's 2018 and ES modules ain't going nowhere.
