### ISSUE TITLE
Problem with namespaces

### ISSUE THREAD

**Issue by Tomino2112** [monounity/karma-typescript#88]
Just trying this package for the first time and unfortunately it does not run and crashes with "x is not defined"

example:

app.ts
```
namespace foo {
    export let bar = () => {
        console.log("hello world");
    }
}
```

app.spec.ts
```
describe("test", () => {
    it("should run", () => {
        expect(foo.hasOwnProperty("bar")).toBe(true)
    });
});
```

**This might not be a working example, just writing it from top of my head.** 

Point is that if I run something like this, it throws `foo is not defined`

Only thing I can think of is that it is not loading files in correct order.

karma.conf.js
```
...
files: [
    "public/**/*.ts"
    "test/**/*.ts"
]
...
```
This should first load all public files (with namespaces defined etc) and then load tests.

This works perfectly fine if I use just karma and target compiled JS files

**Comment by erikbarke** [comment]
Hey @Tomino2112, this could be related to #77, bundled files were not added in the same order as specified in the karma config.

Does it work for you if you install from the latest dev branch, `npm install https://github.com/monounity/karma-typescript.git#2.1.8`?
If you’re behind a firewall and can’t install from GitHub, you can download the branch as a zip and install manually.

**Comment by Tomino2112** [comment]
@erikbarke Unfortunately same issue. I can try to put together working example

**Comment by Tomino2112** [comment]
@erikbarke ok after more testing I think it actually got a little further, still not working though.

One thing for starters, I cannot use:
```
beforeEach(module("app"));
```

Have to use:
```
beforeEach(angular.mock.module("app"));
```
Not critical but works in JS version

Now to the real issue. It still complains that `foo` is not defined. I did similar small app to the one above and it seems to work, so I must have some special case... I will try to backtrack and see what could be the issue.

**Comment by Tomino2112** [comment]
When I click on the "Debug" in testing chrome window, and inspect what and how scripts are included it all makes sense and should work. Baffled really...

**Comment by Tomino2112** [comment]
Sorry couldn't find what is going on, still doesn't work though. I havent got anymore time to spend on testing this, If you really want to try to solve this, I suppose I could give you access to the code.

**Comment by erikbarke** [comment]
Ok, I'll try to reproduce on my end, shouldn't be to difficult!

**Comment by erikbarke** [comment]
@Tomino2112, `karma-typescript` supports your scenario, kind of... Every .ts file gets wrapped in a `commonjs` function that creates a unique scope for `require`, `module`, `__dirname` etc which is why your tests can't find global variables like the namespace `foo`.

It's however possible to use namespaces, but then you can't use any `require`or `import` statements, see #14, `karma-typescript` only adds the wrapper if one or more `require` or `import` statements are found.

As far as I know use namespaces with webpack either 😞
