### ISSUE TITLE
Error : Cannot find module 'source-map/lib/source-map-consumer' ???

### ISSUE THREAD

**Issue by StefH** [monounity/karma-typescript#9]
> 16 09 2016 21:32:55.789:DEBUG [plugin]: Loading karma-* from c:\angular2-odata\node_modules
> 16 09 2016 21:32:55.799:DEBUG [plugin]: Loading plugin c:\angular2-odata\node_modules/karma-chrome-launcher.
> 16 09 2016 21:32:55.812:DEBUG [plugin]: Loading plugin c:\angular2-odata\node_modules/karma-commonjs.
> 16 09 2016 21:32:55.814:DEBUG [plugin]: Loading plugin c:\angular2-odata\node_modules/karma-coverage.
> 16 09 2016 21:32:56.186:DEBUG [plugin]: Loading plugin c:\angular2-odata\node_modules/karma-electron-launcher.
> 16 09 2016 21:32:56.199:DEBUG [plugin]: Loading plugin c:\angular2-odata\node_modules/karma-jasmine.
> 16 09 2016 21:32:56.202:DEBUG [plugin]: Loading plugin c:\angular2-odata\node_modules/karma-mocha.
> 16 09 2016 21:32:56.211:DEBUG [plugin]: Loading plugin c:\angular2-odata\node_modules/karma-mocha-reporter.
> 16 09 2016 21:32:56.227:DEBUG [plugin]: Loading plugin c:\angular2-odata\node_modules/karma-sauce-launcher.
> 16 09 2016 21:32:56.630:DEBUG [plugin]: Loading plugin c:\angular2-odata\node_modules/karma-sourcemap-loader.
> 16 09 2016 21:32:56.639:DEBUG [plugin]: Loading plugin c:\angular2-odata\node_modules/karma-typescript.
> 16 09 2016 21:32:56.830:ERROR [plugin]: Error during loading "c:\angular2-odata\node_modules/karma-typescript" plugin:
>   Cannot find module 'source-map/lib/source-map-consumer'
> 16 09 2016 21:32:56.834:DEBUG [karma]: Registered a load error of type plug_in with name c:\angular2-odata\node_modules/karma-typescript

**Comment by AlexVangelov** [comment]
Looks like the dependency is missing after remap-istanbul was included.
Manual install of `source-map` works for me.

**Comment by monounity** [comment]
Yes, it's a missing dependency, also discussed in #8!
