### ISSUE TITLE
karma-typescript can't load or ignore scss files within nested folders

### ISSUE THREAD

**Issue by YoussefTaghlabi** [monounity/karma-typescript#91]
I have the following Angular 2 component:

```
import { Component } from '@angular/core';

@Component({
  selector: 'web-example',
  styleUrls: ['./example.component.scss'],
  template: `
    <div>Foo</div>
  `
})
```

And I have the following karma config file:

```
module.exports = function(config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['jasmine', 'karma-typescript'],

    // list of files / patterns to load in the browser
    files: [
        'src/base.spec.ts',
        { pattern: 'src/**/!(main).+(ts)' },
        { pattern: 'src/**/*.scss', included: false, watched: false }
    ],

    proxies: {
      "/src/": "/base/src/"
    },
    ...
    ...
  })
}
```

As you can see, I'm including a pattern to exclude `scss` files. I don't want karma to process `scss` as this should be part of `e2e`:

When running karma, I get the following error:
```
15 02 2017 17:03:43.828:WARN [web-server]: 404: /example.component.css
```

And when running Karma in debug mode, I see that karma typescript is trying to load the `scss` file via Ajax:

![image](https://cloud.githubusercontent.com/assets/1639024/22997656/4c495826-f3a1-11e6-8cc2-3910a0c6f511.png)

The only time I get to bypass the 404, and have karma not load the `scss` file via ajax, is when I add `/base/` as a prefix to my `scss` file as in:

```
import { Component } from '@angular/core';

@Component({
  selector: 'web-example',
  styleUrls: ['/base/example.component.scss'],
  template: `
    <div>Foo</div>
  `
})
```

This is definitely not a resolution, as this will break when used in webpack.

Any help will be greatly appreciate it!

Thanks!

**Comment by YoussefTaghlabi** [comment]
Looking at the `example-project@angular2` example, I have added a `scss` file and also added the following pattern to ignore it (Same configuration as above):
`{ pattern: 'src/**/*.scss', included: false, watched: false }`

This works as intended: Karma-typescript ignores `scss` files. However, If I add a nested folder to the `app` folder:
```bash
---|src
     ---|app
           ---|example
                ---|example.component.spec.ts
                ---|example.component.scss
                ---|example.component.ts
```

I get the same exact issue as above. My folder structure is the same structure as described here.
So this might be a config path issue for nested files.

**Comment by erikbarke** [comment]
Hey @YoussefTaghlabi! The `xhr` calls you're seeing are made by Angular so I'm not quite following your logic here... If I exclude the file specified in `styleUrls` Angular barfs because it fails to load the file because it isn't served by the Karma web server, which breaks the test run.

Having said that, I'm working on support for `.scss`, `.sass` etc in Angular components, so I'm gonna leave this issue open!
