### ISSUE TITLE
Can't find dependency

### ISSUE THREAD

**Issue by Dashiing** [monounity/karma-typescript#93]
Using https://github.com/monounity/karma-typescript.git#2.1.8 resolved @jdanyow issue #92  for me, thanks.

But now I'm having another issue:

24 02 2017 09:36:29.599:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.2.1
24 02 2017 09:36:33.303:INFO [compiler.karma-typescript]: Compiled 7 files in 3161 ms.
24 02 2017 09:36:34.141:INFO [bundler.karma-typescript]: Bundled imports for 3 file(s) in 336 ms.
24 02 2017 09:36:34.302:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
24 02 2017 09:36:34.304:INFO [launcher]: Launching browser Chrome with unlimited concurrency
24 02 2017 09:36:34.363:INFO [launcher]: Starting browser Chrome
24 02 2017 09:36:36.366:INFO [Chrome 56.0.2924 (Windows 10 0.0.0)]: Connected on socket JmHAIgGqgLbih8bkAAAA with id 8159575
Chrome 56.0.2924 (Windows 10 0.0.0) ERROR
  Uncaught Error: Can't find ../../WebResources/services/formService [C:/Projects/Research/FRW/DEV/WebResources/services/formService.ts] (required by C:/Projects/Research/FRW/DEV/WebResources.Component/app/controller.spec.ts)
  at node_modules/karma-typescript/src/client/commonjs.js:13

The file exists because I bundle my app with webpack using ts-loader and it can resolve the dependencies just fine. 

Thanks in advance.

**Comment by soleshot** [comment]
I'm having the same issue; still investigating (error on the first import)

**Comment by erikbarke** [comment]
@Dashiing, @soleshot, could you guys run karma with `logLevel: config.LOG_DEBUG` and post the logs and your karma configs here?

**Comment by tehvgg** [comment]
[log.txt](https://github.com/monounity/karma-typescript/files/828950/log.txt)

@erikbarke Was this resolved? I'm running off of KarmaTS 3.0 w/ TS 2.2.1. I've attached my debug info, having the same issue. Below is my karma configuration.

```js
module.exports = function (config) {
	config.set({
		basePath: './',
		frameworks: [ 'jasmine', 'karma-typescript' ],
		browsers: [ 'Chrome' ],
		reporters: [ 'progress', 'karma-typescript' ],
		autoWatch: true,
		singleRun: false,
		files: [
			{ pattern: 'node_modules/jasmine-promises/dist/jasmine-promises.js', watched: false },
			{ pattern: 'tests/*.spec.ts', included: false },
			{ pattern: 'data/**/*.json', included: false }
		],
		preprocessors: {
			'tests/*.spec.ts': [ 'karma-typescript' ]
		},
		karmaTypescriptConfig: {
			bundlerOptions: {
				addNodeGlobals: false
			},
			compilerOptions: {
				sourceMap: true,
				target: 'ES5',
				allowJs: true
			},
			reports: {
				html: 'tests/coverage',
				text: ''
			}
		},
		proxies: {
			'/data': 'http://localhost:9876/base/data'
		},
		logLevel: config.LOG_DEBUG
	});
};
```

**Comment by erikbarke** [comment]
Hey @tehvgg, it looks like `project-folder/tests/test.spec.ts` is requiring itself?

**Comment by tehvgg** [comment]
Yep. Going through the package source I saw that inside `src/client/commonjs.js`... `global.wrappers` was empty, and `filename`, `required`, and `requiring` were all the same string.

**Comment by erikbarke** [comment]
According to the debug log the Typescript files compiles just fine, but you're including just one spec file in the Karma config, which should cause runtime errors because required files were never loaded into the Karma web server, no surprise there. What baffles me is the fact that it looks like one file is requesting itself, could you post `project-folder/tests/test.spec.ts` here?

**Comment by tehvgg** [comment]
Unfortunately it's a closed source project. The imports are for source files, which are brought in by the bundle, which is why I don't include the source files in the Karma config.

```
project
|-- scripts
|   |-- srcFileA.ts
|   \-- srcFileB.ts
|-- tests
|   \-- test.spec.ts
|-- gulpfile.js
\-- karma.conf.js
```

**Comment by erikbarke** [comment]
Ah, the "bundle" in `karma-typescript` is very Karma centric, it consists of one big file with dependencies loaded from node_modules + each project file loaded by Karma, wrapped in a commonjs wrapper. If you want to include a file from your project in the test run, you have to tell Karma to include it in the `files` section.

My guess is you could just include `project-folder/**/*.+(js|ts)` and then tell `karma-typescript` to execute the spec files:

```js
karmaTypescriptConfig: {
    bundlerOptions: {
        entrypoints: /\.spec\.ts$/
    }
}
```

**Comment by adamcogx** [comment]
I am having the same issue.  The first run through the tests runs fine (when running with singleRun:false), but when I change a file, the following happens:

13 03 2017 13:06:11.181:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.2.1
13 03 2017 13:06:14.044:INFO [compiler.karma-typescript]: Compiled 88 files in 2379 ms.
13 03 2017 13:06:14.695:INFO [bundler.karma-typescript]: Bundled imports for 75 file(s) in 148 ms.
13 03 2017 13:06:14.896:WARN [karma]: No captured browser, open http://localhost:9876/
13 03 2017 13:06:14.909:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
13 03 2017 13:06:14.910:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
13 03 2017 13:06:14.918:INFO [launcher]: Starting browser PhantomJS
13 03 2017 13:06:17.957:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket 5R2k4Uv-PtYfM4T-AAAA with id 24264397
PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 2 of 2 SUCCESS (0.015 secs / 0.003 secs)
13 03 2017 13:06:25.362:INFO [compiler.karma-typescript]: Compiled 88 files in 1097 ms.
13 03 2017 13:06:25.895:INFO [watcher]: Changed file "C:/dev/FactoFlowReStart/FactoFlowReStart/app/tests/dummy.spec.ts".
13 03 2017 13:06:25.924:INFO [watcher]: Changed file "C:/Users/ADAM~1.DOV/AppData/Local/Temp/karma-typescript-bundle-12312kPiaK9nsvfzU.js".
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  Error: Can't find C:/dev/FactoFlowReStart/FactoFlowReStart/app/tests/dummy.spec.ts [C:/dev/FactoFlowReStart/FactoFlowReStart/app/tests/dummy.spec.ts] (required by C:/dev/FactoFlowReStart/FactoFlowReStart/app/tests/dummy.spec.ts)
  at node_modules/karma-typescript/src/client/commonjs.js:13

**Comment by adamcogx** [comment]
Here is my config file:

```
module.exports = function (config) {
    config.set({
        preprocessors: {
            'app/**/*.ts': ['karma-typescript'],
            'app/templates/**/*.html': ['ng-html2js']
        },
        basePath: '',
        frameworks: ['jasmine', 'karma-typescript', 'sinon'],
        files: [
            'Scripts/preamble.js',
            'Scripts/lib/angular/angular.js',
            'Scripts/lib/angular-animate/angular-animate.min.js',
            'Scripts/lib/angular-aria/angular-aria.min.js',
            'Scripts/lib/angular-material/angular-material.min.js',
            'Scripts/lib/angular-ui-router/release/angular-ui-router.js',
            'Scripts/lib/angular-resource/angular-resource.js',
            'Scripts/lib/lodash/dist/lodash.js',
            'node_modules/angular-mocks/angular-mocks.js',
            'app/templates/**/*.html',
            { pattern: 'app/**/*.ts' }
        ],

        exclude: [
        ],

        ngHtml2JsPreprocessor: {
            stripPrefix: 'app/templates/',
            moduleName: 'templates'
        },

        karmaTypescriptConfig: {
            compilerOptions: {
                "module": "commonjs",
                "moduleResolution": "node",
                "target": "es5",
                "noImplicitAny": false,
                "sourceMap": true,
                "experimentalDecorators": true,
                "noEmitHelpers": true
            },
            bundlerOptions: {
                entrypoints: /\.spec\.ts$/
            }
        },

        reporters: ['progress', 'karma-typescript'],

        port: 9876,

        colors: true,

        logLevel: config.LOG_INFO,

        autoWatch: true,

        browsers: ['PhantomJS'],

        concurrency: Infinity
    });
};

```

**Comment by erikbarke** [comment]
Hey @adamcogx, thanks for your input, it will help narrow this down! What version of `karma-typescript` are you using?

**Comment by adamcogx** [comment]
Here is the relevant section from my packages.json:

```
"devDependencies": {
    "angular-mocks": "1.5.8",
    "browserify": "14.1.0",
    "del": "^2.2.2",
    "exorcist": "0.4.0",
    "gulp": "^3.9.1",
    "gulp-angular-templatecache": "2.0.0",
    "gulp-concat": "^2.6.0",
    "gulp-cssmin": "^0.1.7",
    "gulp-htmlmin": "^2.0.0",
    "gulp-uglify": "^2.0.0",
    "jasmine-core": "2.5.0",
    "karma": "1.5.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-jasmine": "1.1.0",
    "karma-ng-html2js-preprocessor": "^1.0.0",
    "karma-phantomjs-launcher": "1.0.4",
    "karma-sinon": "1.0.5",
    "karma-typescript": "3.0.0-beta.2",
    "merge-stream": "^1.0.0",
    "sinon": "1.17.5",
    "tsify": "3.0.1",
    "typescript": "2.2.1",
    "uglifyify": "3.0.2",
    "vinyl-source-stream": "1.1.0",
    "watchify": "3.9.0"
  },
```

**Comment by erikbarke** [comment]
@adamcogx, your dummy example did the trick, I was finally able to reproduce the error, thanks!

**Comment by erikbarke** [comment]
Hey guys, does it work for you if you install from the master branch now, `npm i github:monounity/karma-typescript`?
If you’re behind a firewall and can’t install from GitHub, you can download the branch as a zip and install manually.

**Comment by adamcogx** [comment]
It seems to work now for me (I added and then removed a throw from a test and it handled it):

14 03 2017 10:03:43.524:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.2.1
14 03 2017 10:03:46.899:INFO [compiler.karma-typescript]: Compiled 88 files in 2789 ms.
14 03 2017 10:03:47.599:INFO [bundler.karma-typescript]: Bundled imports for 75 file(s) in 197 ms.
14 03 2017 10:03:47.799:WARN [karma]: No captured browser, open http://localhost:9876/
14 03 2017 10:03:47.812:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
14 03 2017 10:03:47.813:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
14 03 2017 10:03:47.857:INFO [launcher]: Starting browser PhantomJS
14 03 2017 10:03:50.963:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket YD__hd6SDPjnBA4LAAAA with id 36854650
PhantomJS 2.1.1 (Windows 8 0.0.0) app should start FAILED
        BAM thrown
PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 2 of 2 (1 FAILED) (0.017 secs / 0.002 secs)
14 03 2017 10:04:17.128:INFO [compiler.karma-typescript]: Compiled 88 files in 1790 ms.
14 03 2017 10:04:17.683:INFO [bundler.karma-typescript]: Bundled imports for 1 file(s) in 54 ms.
14 03 2017 10:04:17.685:INFO [watcher]: Changed file "C:/dev/FactoFlowReStart/FactoFlowReStart/app/tests/app.spec.ts".
14 03 2017 10:04:17.696:INFO [watcher]: Changed file "C:/Users/ADAM~1.DOV/AppData/Local/Temp/karma-typescript-bundle-27200hjRlsbJnLs5u.js".
14 03 2017 10:04:17.704:INFO [watcher]: Changed file "C:/Users/ADAM~1.DOV/AppData/Local/Temp/karma-typescript-bundle-27200hjRlsbJnLs5u.js".
PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 2 of 2 SUCCESS (0.016 secs / 0.001 secs)

**Comment by QuantumInformation** [comment]
Not if this is related, but, my test file can't find an npm module that definitely exists

![image](https://cloud.githubusercontent.com/assets/216566/26246322/7560fb50-3c90-11e7-8c47-73e63513e502.png)

**Comment by erikbarke** [comment]
@QuantumInformation, the Typescript compiler resolves imports by looking for corresponding typings files, you have to install or create the missing typings for `vanilla-typescript`.

**Comment by QuantumInformation** [comment]
The typings are there:
![image](https://cloud.githubusercontent.com/assets/216566/26251950/d4ea3fa8-3ca6-11e7-8708-45605e3737b4.png)

**Comment by erikbarke** [comment]
@QuantumInformation, that index.ts file doesn't look like a typings file to me, it's not named .d.ts, it doesn't declare any functions, interfaces, types etc and not even Webstorm seems to recognize it or your module in your first screenshot. Have you tried using [the module template file](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html)?

**Comment by nelsonjd** [comment]
Hi all, I am running into a similar issue running karma-typescript 3.0.5 and I attached my debug log.  Thanks for any help you can provide.
[output.txt](https://github.com/monounity/karma-typescript/files/2077235/output.txt)
One other thing I noticed is that ts-priority-queue which is the package of importance is not in my package-lock.json.  I thought if you have a package in package.json, you always will have an entry in package-lock.json.
