### ISSUE TITLE
not running with typescript 2.2.1

### ISSUE THREAD

**Issue by typedefJorge** [monounity/karma-typescript#95]
when i revert to ts 2.1.5 it works fine

command line output:
> karma start webglKarma.conf.js

25 02 2017 20:15:34.519:INFO [compiler.karma-typescript]: Compiling project using Typescript 2.2.1
25 02 2017 20:15:37.102:INFO [compiler.karma-typescript]: Compiled 29 files in 1983 ms.
25 02 2017 20:15:38.088:WARN [karma]: No captured browser, open http://localhost:9876/
25 02 2017 20:15:38.102:INFO [karma]: Karma v1.5.0 server started at http://0.0.0.0:9876/
25 02 2017 20:15:38.102:INFO [launcher]: Launching browsers PhantomJS, Chrome, Firefox with unlimited concurrency
25 02 2017 20:15:38.112:INFO [launcher]: Starting browser PhantomJS
25 02 2017 20:15:38.132:INFO [launcher]: Starting browser Chrome
25 02 2017 20:15:38.140:INFO [launcher]: Starting browser Firefox
25 02 2017 20:15:39.856:INFO [Chrome 56.0.2924 (Windows 10 0.0.0)]: Connected on socket 2FNizOFMy_3esYzdAAAA with id 7864413
25 02 2017 20:15:40.017:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket aPSrf5RW06iNgnP4AAAB with id 37874298
25 02 2017 20:15:42.403:INFO [Firefox 45.0.0 (Windows 10 0.0.0)]: Connected on socket hQzWtTUD2OkNVBzMAAAC with id 34602514
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  ReferenceError: Can't find variable: exports
  at src/graphics/color.js:2:0 <- src/graphics/color.js:10
PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 0 of 0 ERROR (0.104 secs / 0 secs)
Chrome 56.0.2924 (Windows 10 0.0.0) ERROR
  Uncaught ReferenceError: exports is not defined
  at src/graphics/color.js:2:0 <- src/graphics/color.js:10
Chrome 56.0.2924 (Windows 10 0.0.0): Executed 0 of 0 ERROR (0.185 secs / 0 secs)
Firefox 45.0.0 (Windows 10 0.0.0) ERROR
  ReferenceError: exports is not defined
  at src/graphics/color.js:2:0 <- src/graphics/color.js:10
Firefox 45.0.0 (Windows 10 0.0.0): Executed 0 of 0 ERROR (0.217 secs / 0 secs)

contents of webglKarma.conf.js:
```javascript
// Karma configuration
// Generated on Mon Apr 11 2016 10:01:58 GMT-0400 (Eastern Daylight Time)

module.exports = function(config) {
  config.set({
    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ["jasmine", "karma-typescript"],


    // list of files / patterns to load in the browser
    files: [
        //software under test
        { pattern: "src/**/*.ts" },

        // tests
        { pattern: "spec/utils/vector.spec.ts" },
        { pattern: "spec/graphics/geometry/boundingRectangle.spec.ts" },
        { pattern: "spec/graphics/geometry/midpoint.spec.ts" },

    ],


    preprocessors: {
        "**/*.ts": ["karma-typescript"]
    },


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ["dots", "karma-typescript"],


    // enable / disable colors in the its 
    colors: true,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: [
    	'PhantomJS',
        "Chrome", 
        "Firefox"
    ],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false
  });
}
```

my package.json also, in case its helpful:
```javascript
{
    "name": "webgl-renderer",
    "version": "0.1.2",
    "description": "webGl renderering engine",
    "main": "index.html",
    "scripts": {
        "start": "./node_modules/.bin/webpack-dev-server",
        "test": "./node_modules/.bin/karma start webglKarma.conf.js"
    },
    "dependencies": {
        "@types/react": "^15.0.12",
        "@types/react-dom": "^0.14.23",
        "react": "^15.4.2",
        "react-dom": "^15.4.2"
    },
    "devDependencies": {
        "@types/jasmine": "^2.5.35",
        "jasmine-core": "^2.4.1",
        "karma": "^1.4.1",
        "karma-cli": "^1.0.1",
        "karma-jasmine": "^1.1.0",
        "karma-phantomjs-launcher": "^1.0.2",
        "karma-chrome-launcher": "^2.0.0",
        "karma-firefox-launcher": "^1.0.0",
        "karma-typescript": "2.1.7",
        "source-map-loader": "^0.1.6",
        "typescript": "^2.2.1",
        "ts-loader": "^2.0.0",
        "webpack": "^2.2.1",
        "webpack-dev-server": "^2.3.0"
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/typedefJorge/webgl-renderer.git"
    },
    "author": "typedefjorge",
    "license": "MIT",
    "bugs": {
        "url": "https://github.com/typedefJorge/webgl-renderer/issues"
    },
    "homepage": "https://github.com/typedefJorge/webgl-renderer#readme"
}
```

**Comment by erikbarke** [comment]
Hey @typedefJorge, a lot of things broke with typescript@2.2.1 and have been fixed in the 2.1.8 dev branch, please see #92!

Does it work for you if you install from the latest dev branch, npm install https://github.com/monounity/karma-typescript.git#2.1.8?
If you’re behind a firewall and can’t install from GitHub, you can download the branch as a zip and install manually.

**Comment by sualko** [comment]
@erikbarke At least the mocha example is working again for me. (I am currently setting up my test environment)

**Comment by erikbarke** [comment]
@sualko, great, we're making progress!

**Comment by typedefJorge** [comment]
@erikbarke Yeah it worked perfectly for me with Jasmine and the 2.1.8 dev branch, thanks!
