### ISSUE TITLE
karma-typescript not bundling

### ISSUE THREAD

**Issue by sgen** [monounity/karma-typescript#96]
Im having trouble getting karma-typescript to bundle my typescript. I keep getting the error: `Uncaught ReferenceError: exports is not defined`.

I noticed that the docs state that the docs state that bundling will only occur when an import statement is included. This suggests that my module (which is simple enough to not include import statements) might not be bundled. Shouldnt it be bundled to polyfill the exports statements? If not, how can I bundle my code for the browser / karma browser tests?

This is my karma.conf.js:

```javascript
module.exports = function(config) {
  config.set({
    frameworks: ["jasmine", "karma-typescript"],
    files: [
      {
       pattern: "src/**/*.ts"
      },
    ],
    preprocessors: {
      "**/*.ts": ["karma-typescript"],
    },
    reporters: ["progress", "karma-typescript"],
    browsers: ["Chrome"],
    karmaTypescriptConfig: {
      compilerOptions: {
        module: 'commonjs'
      }
    }
  });
};
```

And Im calling Karma from gulp as per the karma-runner [docs](https://github.com/karma-runner/gulp-karma#tldr).

**Comment by erikbarke** [comment]
Hey @sgen, this sounds like the error in #92, are you using Typescript@2.2.1? If you are, does it work for you if you install from the latest dev branch, npm install https://github.com/monounity/karma-typescript.git#2.1.8?
If you’re behind a firewall and can’t install from GitHub, you can download the branch as a zip and install manually.

**Comment by sgen** [comment]
Sorry to take so long to get back to you. Pinning the version to the 2.1.8 branch didnt fix it.

**Comment by erikbarke** [comment]
Ok, could you post a code example here please?

**Comment by sgen** [comment]
Sure Thing:

Typescript:
```typescript
export class ToDo {
  id: number;
  text: string;
  completed: boolean;
  createdAt: Date;
  completedAt: Date;

  constructor(id: number, text: string, completed?: boolean, createdAt?: Date, completedAt?: Date) {
    this.id = id;
    this.text = text;

    if (completed === undefined) {
      completed = false;
    }

    this.completed = completed;

    if (createdAt === undefined) {
      createdAt = new Date();
    }

    this.createdAt = createdAt;

    if (completedAt === undefined) {
      completedAt = null
    }

    this.completedAt = completedAt;
  }

  complete() {
    if (this.completed) {
      return;
    }

    this.completed = true;
    this.completedAt = new Date();
  }
}

interface ToDoObject {
  id: number;
  text: string;
  completed: boolean;
  createdAt: Date;
  completedAt: Date;
}

export function ToDoFromObj(obj: ToDoObject) {
  let id = obj.id;
  let text = obj.text;
  let completed = obj.completed;
  let createdAt = obj.createdAt;
  let completedAt = obj.completedAt;
  return new ToDo(id, text, completed, createdAt, completedAt);
}

export function ToDoFromJSON(json: string) {
  return ToDoFromObj(JSON.parse(json));
}

export function ToDosFromJSON(json: string) {
  let objs = JSON.parse(json);
  let todos : ToDoObject[] = [];
  objs.forEach((obj: ToDoObject) => {
    todos.push(ToDoFromObj(obj));
  });
  return todos;
}
```

**Comment by erikbarke** [comment]
Ah, now I get it, the bundler should simply count export statements too...

**Comment by sgen** [comment]
Any news on this? I tried installing 3.0.0-beta but Im still getting the same error:
```
  Uncaught ReferenceError: exports is not defined
  at src/todo.model.js:10
```

**Comment by erikbarke** [comment]
Yes, I have a failing integration test that describes your scenario, but solving this issue by counting `export` statements breaks other tests/scenarios. Back to the drawing board...

**Comment by erikbarke** [comment]
A thought...

This Typescript sample:

```js
export function exportedFunction(): string {
    return "";
}
```

Would be compiled to the following javascript (assuming`"module": "commonjs"`):

```js
function exportedFunction() {
    return "";
}
exports.exportedFunction = exportedFunction;
```

This would then be wrapped in a `CommonJS` wrapper by the bundler:

```js
(function(global){
    global.wrappers['/absolutepath/app/src/file.ts']=[function(require,module,exports,__dirname,__filename){
        function exportedFunction() {
            return "";
        }
        exports.exportedFunction = exportedFunction;
    },'src/file.ts',{}];
})(this);
```

(I've omitted the source map for brevity and formatted the wrapper a bit for readability here)

The wrapper emulates the NodeJs module system by injecting the `require` function, the `exports` object etc, and effectively encapsulating the code. Since the code isn't on the global scope, it's only reachable by importing/requiring it from another module.

This is why `karma-typescript` performs a simple static analysis on the compiled code to determine if any module is actually requesting any another module. If not, the code won't get wrapped because it would be meaningless, the test run would just contain a bunch of isolated modules with unreachable code.

I've experimented with modifying the static analysis to make your scenario work, ie "also perform bundling if any `export`statement is encountered". But then I end up with an isolated module that can't be executed from a test... Unless I import the module in the test, rendering my analysis tweak unnecessary since modules are now requesting other modules...

My point is: I'm worried this won't work at all, how are you testing your exported functions?

**Comment by sgen** [comment]
I actually didnt have a test file setup. Simply importing it in another files solves the problem. I had just assumed that it would bundle without being imported by a test file. Maybe a warning when no modules are imported or a warning in the docs could keep this from happening again.

**Comment by erikbarke** [comment]
This is intentional behavior requested by, for instance, users using the Typescript module system, I've tried to shed some light on the bundler logic in the readme, hope that helps!

**Comment by sgen** [comment]
It makes perfect sense! Why bundle something you're not using? It's confusing when you're trying to get started with a new build setup and green lighting. Thanks for the readme note!

**Comment by Downchuck** [comment]
While I appreciate the feature, the potential for side effects in this is too costly; I need to know if this is following some path that meets up with webpack and/or ts-jest.

Present situation is tsc || ts-jest || karma-webpack+ts-loader now, as I can't figure out how to maintain a karma-typescript build with imports.
