### ISSUE TITLE
Coverage for javascript files as well as typescript files.

### ISSUE THREAD

**Issue by wawyed** [monounity/karma-typescript#97]
Is there any way to generate coverage for javascript files as well as typescript files? I have an hybrid app that uses angularJs and angular and I'd like to have coverage for both ts and js files.

I manage to get it working more or less by doing this in the config:

```javascript
{
    preprocessors: {
      'src/**/*.js': ['coverage'],
      'src/**/*.ts': ['karma-typescript', 'coverage'],
      'test/**/*.ts': ['karma-typescript']
    },

    coverageReporter: {
      type: 'in-memory'
    },

    karmaTypescriptConfig: {
      tsconfig: './tsconfig.json',
      include: ['test/**/*.ts', 'src/**/*.ts'],
      reports: {
        'text-summary': null,
        html: {
          directory: globals.paths.karma.coverage,
          filename: '.'
        },
        'json-summary': {
          directory: globals.paths.karma.coverage,
          filename: 'coverage.json'
        }
      },
      remapOptions: {
        /* eslint-disable lodash/prefer-noop */
        warn: function() {
        }
        /* eslint-enable */
      }
    },

    reporters: ['dots', 'coverage', 'karma-typescript'],
}
```

Unfortunately now I'm getting spec.ts files showing in the coverage. 

Any advice on how to stop that from happening.

Thanks.

**Comment by erikbarke** [comment]
Hey @wawyed, `karmaTypescriptConfig.coverageOptions.exclude` excludes ".d.ts", ".spec.ts", ".test.ts" by default, try setting it to exclude ".d.ts" and folders with the name "/test/":

```javascript
{
    preprocessors: {
      'src/**/*.js': ['coverage'],
      'src/**/*.ts': ['karma-typescript', 'coverage'],
      'test/**/*.ts': ['karma-typescript']
    },

    coverageReporter: {
      type: 'in-memory'
    },

    karmaTypescriptConfig: {
      tsconfig: './tsconfig.json',
      coverageOptions: {
        exclude: [/(\/test\/.*|\.d)\.ts/i]
      },
      include: ['test/**/*.ts', 'src/**/*.ts'],
      reports: {
        'text-summary': null,
        html: {
          directory: globals.paths.karma.coverage,
          filename: '.'
        },
        'json-summary': {
          directory: globals.paths.karma.coverage,
          filename: 'coverage.json'
        }
      },
    },

    reporters: ['dots', 'coverage', 'karma-typescript'],
}
```

**Comment by wawyed** [comment]
I'm confused @erikbarke , how would that help me? I don't want coverage of my spec.ts files.,

**Comment by erikbarke** [comment]
Ah, ok, your unit test files *are* named *.spec.ts... Is this line causing your problems?
 
`reporters: ['dots', 'coverage', 'karma-typescript']`. 

Doesn't this mean that all *.js and *.ts files get reported by `karma-coverage`? If that is the case, this scenario isn't supported as of now, but I'll take a look to see if I can come up with a solution, but I'm guessing it'll take some effort to get this up and running, I'll keep you posted!

**Comment by wawyed** [comment]
Yes, my test files are named *.spec.ts. Looking into it I found out that my problem is that this line is the problem:

` 'src/**/*.ts': ['karma-typescript', 'coverage'],`

I can't find a way to make coverage ignore the spec.ts files as karma-typescript does. I also found this issue https://github.com/karma-runner/karma-coverage/issues/13 which relates to it.

**Comment by wawyed** [comment]
I managed to get the desired behavior by changing the preprocessors object to look like this: 

```
    preprocessors: {
      'src/**/*.html': ['ng-html2js'],
      'src/**/*.js': ['coverage'],
      'src/**/!(*.spec).ts': ['karma-typescript', 'coverage'],
      'src/**/*.spec.ts': ['karma-typescript']
    },
```

**Comment by erikbarke** [comment]
Nice work! So everything works now?

**Comment by wawyed** [comment]
Yes, even though I wonder if I'm abusing how coverage interacts with karma-typescript to make this work and there should be an easier way to make karma-typescript accept javascript files for coverage purposes.

I'd like to hear your thoughts on it.

**Comment by erikbarke** [comment]
Hmm, are you really getting remapped coverage for your Typescript files?

**Comment by wawyed** [comment]
Yes, with that configuration I get remapped coverage for typescript files and normal coverage for javascript files.

**Comment by erikbarke** [comment]
Well, in that case I really don't think you're abusing karma-coverage/karma-typescript. Imho you've come up with a quite elegant solution to your problem, it's short and concise. I'm gonna keep this issue open, maybe I can come up with a more obvious way to achieve what you want.

**Comment by erikbarke** [comment]
The approach in #159 seems to actually solve this issue! Just use `allowJs` in the Typescript compiler options and pipe all `.js` and `.ts` files through karma-typescript:

```js
files: [
    { pattern: "src/**/*.+(js|ts)" },
],

frameworks: ["karma-typescript"],

preprocessors: {
    "src/**/*.+(js|ts)": ["karma-typescript"],
}

reporters: ["progress", "karma-typescript"],
```

This produces code coverage for both `.js` and `.ts` files ☺️
