### ISSUE TITLE
require try-catch behavior

### ISSUE THREAD

**Issue by AlexVangelov** [monounity/karma-typescript#99]
I have a test that includes ws npm.
In the file [https://github.com/websockets/ws/blob/v1.x/lib/BufferUtil.js](https://github.com/websockets/ws/blob/v1.x/lib/BufferUtil.js) there is a code:
```
try {
  module.exports = require('bufferutil');
} catch (e) {
  module.exports = require('./BufferUtil.fallback');
}
```
What can be done, so the `karma-typescript/lib/bundler.js` to make this code happy?
```
ERROR [karma]: Error: Cannot find module 'bufferutil' from '.'
    at Function.module.exports [as sync] (/Users/alex/workspace/extface/ef-client/node_modules/resolve/lib/sync.js:33:11)
    at Function.resolve.sync (/Users/alex/workspace/extface/ef-client/node_modules/browser-resolve/index.js:321:21)
    at resolve (/Users/alex/workspace/extface/ef-client/node_modules/karma-typescript/lib/bundler.js:263:50)
```
Thanks

**Comment by erikbarke** [comment]
Hey @AlexVangelov! Does it work if you install `bufferutil@1.3.0`as suggested in https://github.com/websockets/ws/issues/1010?

**Comment by AlexVangelov** [comment]
The `bufferutil` case is just an example. 
My question is about `try - require - catch` blocks.

**Comment by erikbarke** [comment]
Ah, you want the fallback in the catch clause? This worked for me:

`npm install ws` (but not `bufferutil`)

```
karmaTypescriptConfig: {
    bundlerOptions: {
        exclude: ["bufferutil", "utf-8-validate"]
    }
}
```

```
import * as WebSocket from "ws";

let ws = new WebSocket("https://host");

// etc...
```

Is this what you're looking for?

**Comment by AlexVangelov** [comment]
Yes, it works.
A nice solution with bundlerOptions.
Thank  you for your time @erikbarke
